import type { MacroDataSource, MacroGroup, MacroUnit } from "@/lib/types"

export interface MacroIndicatorMeta {
  /** Stable identifier (used as React key and indicator url). For Yahoo this is the ticker; for FRED it is the series id. */
  symbol: string
  /** Provider-specific identifier; defaults to `symbol` if omitted. */
  providerSymbol?: string
  name: string
  group: MacroGroup
  unit: MacroUnit
  source: MacroDataSource
  /** Lower number = more important. Used for sorting + selecting "实时" KPI strip. */
  priority: number
  description: string
  audience: string[]
  frequency: string
  transform?: (value: number) => number
}

const dividedByTen = (value: number) => value / 10

/**
 * Full indicator registry — covers ~85 series across rates / inflation / employment /
 * liquidity / credit / equity / volatility / FX / commodity / growth / real-estate /
 * crypto / on-chain / sentiment / cross-asset.
 *
 * Priority is hand-tuned for the "什么最重要" view used in macro analysis combining
 *股票 / 量化 / 期货 / 加密 best practices.
 *
 * Indicators marked Yahoo Finance: free, no key.
 * Indicators marked FRED: require FRED_API_KEY env var. They are silently skipped if missing.
 * Indicators marked DefiLlama / Blockchain.com / Alternative.me / CoinGecko: free public endpoints.
 */
export const MACRO_INDICATORS: MacroIndicatorMeta[] = [
  // ============================================================
  // TIER 1 — Critical daily watch (1-15)
  // ============================================================
  {
    symbol: "FRED:DFF",
    providerSymbol: "DFF",
    source: "FRED",
    name: "Fed Funds Effective Rate",
    group: "Rates",
    unit: "percent",
    priority: 1,
    frequency: "Daily",
    audience: ["宏观", "股票", "加密", "期货"],
    description:
      "美联储有效联邦基金利率，全球无风险利率的锚。\n直接决定贴现率，对美股估值、BTC、黄金和美元定价影响最大。\n上行：紧缩；下行：放水。",
  },
  {
    symbol: "FRED:DGS10",
    providerSymbol: "DGS10",
    source: "FRED",
    name: "U.S. 10Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 2,
    frequency: "Daily",
    audience: ["宏观", "股票", "加密"],
    description:
      "美国 10 年期国债收益率，全球资产定价的核心折现率。\n上行通常压制成长股 / BTC，支撑美元；下行反之。",
  },
  {
    symbol: "FRED:DGS2",
    providerSymbol: "DGS2",
    source: "FRED",
    name: "U.S. 2Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 3,
    frequency: "Daily",
    audience: ["宏观", "债券", "加密"],
    description: "2 年期国债收益率，对市场加息/降息预期最敏感的端点，常用于看 Fed 路径定价。",
  },
  {
    symbol: "FRED:DFII10",
    providerSymbol: "DFII10",
    source: "FRED",
    name: "10Y TIPS Real Yield",
    group: "Rates",
    unit: "percent",
    priority: 4,
    frequency: "Daily",
    audience: ["宏观", "加密", "黄金"],
    description: "通胀挂钩国债（TIPS）10 年期实际利率。\n实际利率上行 = 非生息资产（黄金 / BTC）压制；下行 = 利好。",
  },
  {
    symbol: "DX-Y.NYB",
    source: "Yahoo Finance",
    name: "U.S. Dollar Index (DXY)",
    group: "FX",
    unit: "index",
    priority: 5,
    frequency: "Realtime",
    audience: ["宏观", "FX", "加密"],
    description: "美元对一篮子主要货币的加权指数。美元走强通常压制 BTC、黄金、新兴市场和大宗商品。",
  },
  {
    symbol: "^IXIC",
    source: "Yahoo Finance",
    name: "Nasdaq Composite",
    group: "Equity",
    unit: "index",
    priority: 6,
    frequency: "Realtime",
    audience: ["股票", "加密"],
    description: "纳斯达克综合指数，科技股权重最大。与 BTC、高 Beta 资产的相关系数常超过 0.7。",
  },
  {
    symbol: "^NDX",
    source: "Yahoo Finance",
    name: "Nasdaq 100",
    group: "Equity",
    unit: "index",
    priority: 7,
    frequency: "Realtime",
    audience: ["股票", "加密"],
    description: "纳斯达克 100，100 只非金融大型成长公司的市值加权指数。BTC 同向相关度极高。",
  },
  {
    symbol: "QQQ",
    source: "Yahoo Finance",
    name: "Invesco QQQ Trust (QQQ)",
    group: "Equity",
    unit: "usd",
    priority: 7.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "科技"],
    description: "Nasdaq 100 可交易 ETF。量化交易中常用于替代 NDX 现货指数，流动性高、期权链活跃。",
  },
  {
    symbol: "^GSPC",
    source: "Yahoo Finance",
    name: "S&P 500",
    group: "Equity",
    unit: "index",
    priority: 8,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "美股 500 大蓝筹综合，全球风险偏好基准。",
  },
  {
    symbol: "SPY",
    source: "Yahoo Finance",
    name: "SPDR S&P 500 ETF (SPY)",
    group: "Equity",
    unit: "usd",
    priority: 8.1,
    frequency: "Realtime",
    audience: ["股票", "量化"],
    description: "S&P 500 可交易 ETF。用于观察真实成交、期权、机构对冲和盘中风险偏好。",
  },
  {
    symbol: "^VIX",
    source: "Yahoo Finance",
    name: "CBOE VIX",
    group: "Volatility",
    unit: "index",
    priority: 9,
    frequency: "Realtime",
    audience: ["宏观", "股票", "加密"],
    description: "S&P 500 隐含波动率（恐慌指数）。\n>30 高度恐慌；20-30 警戒；<15 极度乐观。",
  },
  {
    symbol: "FRED:CPIAUCSL",
    providerSymbol: "CPIAUCSL",
    source: "FRED",
    name: "U.S. CPI (Headline)",
    group: "Inflation",
    unit: "index",
    priority: 10,
    frequency: "Monthly",
    audience: ["宏观", "债券", "加密"],
    description: "美国 CPI 总体指数（季调）。每月公布，是市场对 Fed 政策路径定价的核心变量之一。",
  },
  {
    symbol: "FRED:CPILFESL",
    providerSymbol: "CPILFESL",
    source: "FRED",
    name: "U.S. Core CPI (ex Food & Energy)",
    group: "Inflation",
    unit: "index",
    priority: 11,
    frequency: "Monthly",
    audience: ["宏观", "债券"],
    description: "美国核心 CPI（剔除食品和能源）。Fed 决策更看重，黏性强意味着降息预期推迟。",
  },
  {
    symbol: "FRED:PCEPI",
    providerSymbol: "PCEPI",
    source: "FRED",
    name: "U.S. PCE Price Index",
    group: "Inflation",
    unit: "index",
    priority: 12,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国个人消费支出物价指数。Fed 设定 2% 通胀目标的官方度量。",
  },
  {
    symbol: "FRED:PCEPILFE",
    providerSymbol: "PCEPILFE",
    source: "FRED",
    name: "U.S. Core PCE",
    group: "Inflation",
    unit: "index",
    priority: 13,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "核心 PCE（剔除食品和能源），Fed 最偏好的通胀指标。",
  },
  {
    symbol: "FRED:UNRATE",
    providerSymbol: "UNRATE",
    source: "FRED",
    name: "U.S. Unemployment Rate",
    group: "Employment",
    unit: "percent",
    priority: 14,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国失业率。上行 0.5% 以上常对应 Sahm Rule 衰退信号，催化降息预期。",
  },
  {
    symbol: "FRED:PAYEMS",
    providerSymbol: "PAYEMS",
    source: "FRED",
    name: "Nonfarm Payrolls (Level)",
    group: "Employment",
    unit: "count",
    priority: 15,
    frequency: "Monthly",
    audience: ["宏观", "股票"],
    description: "非农就业总人数水平（千人）。月差即为新增 NFP，市场最关注的就业指标。",
  },

  // ============================================================
  // TIER 2 — Liquidity & Credit (16-30)
  // ============================================================
  {
    symbol: "FRED:WALCL",
    providerSymbol: "WALCL",
    source: "FRED",
    name: "Fed Balance Sheet",
    group: "Liquidity",
    unit: "usd",
    priority: 16,
    frequency: "Weekly",
    audience: ["宏观", "加密"],
    description: "联储总资产规模（百万美元）。QE 扩张时增长，QT 时收缩。直接驱动全球美元流动性。",
    transform: (value) => value * 1_000_000, // FRED reports in millions
  },
  {
    symbol: "FRED:TOTRESNS",
    providerSymbol: "TOTRESNS",
    source: "FRED",
    name: "Bank Reserves (Total)",
    group: "Liquidity",
    unit: "usd",
    priority: 17,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国存款机构在联储的准备金总额（百万美元）。金融体系流动性核心指标。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:RRPONTSYD",
    providerSymbol: "RRPONTSYD",
    source: "FRED",
    name: "Overnight Reverse Repo",
    group: "Liquidity",
    unit: "usd",
    priority: 18,
    frequency: "Daily",
    audience: ["宏观", "加密"],
    description: "纽约联储隔夜逆回购余额。RRP 下降 = 货币市场基金释放美元到银行体系（放水）。",
    transform: (value) => value * 1_000_000_000, // FRED reports in billions
  },
  {
    symbol: "FRED:WTREGEN",
    providerSymbol: "WTREGEN",
    source: "FRED",
    name: "Treasury General Account (TGA)",
    group: "Liquidity",
    unit: "usd",
    priority: 19,
    frequency: "Weekly",
    audience: ["宏观", "加密"],
    description: "美国财政部在联储的现金账户余额（百万美元）。TGA 上升 = 财政部抽水；下降 = 放水。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:M2SL",
    providerSymbol: "M2SL",
    source: "FRED",
    name: "U.S. M2 Money Supply",
    group: "Liquidity",
    unit: "usd",
    priority: 20,
    frequency: "Monthly",
    audience: ["宏观", "加密"],
    description: "美国 M2 货币供应（十亿美元）。宽货币周期对风险资产中长期支撑。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:M1SL",
    providerSymbol: "M1SL",
    source: "FRED",
    name: "U.S. M1 Money Supply",
    group: "Liquidity",
    unit: "usd",
    priority: 21,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "M1 短端货币（活期 + 现金），反映短期流动性。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:BAMLH0A0HYM2",
    providerSymbol: "BAMLH0A0HYM2",
    source: "FRED",
    name: "U.S. HY Credit Spread (OAS)",
    group: "Credit",
    unit: "percent",
    priority: 22,
    frequency: "Daily",
    audience: ["宏观", "信用", "加密"],
    description:
      "ICE BofA 美国高收益债期权调整利差（OAS）。\n上行 = 信用风险走差，常领先股市下跌；< 3% 风险偏好高。",
  },
  {
    symbol: "FRED:BAMLC0A0CM",
    providerSymbol: "BAMLC0A0CM",
    source: "FRED",
    name: "U.S. IG Credit Spread (OAS)",
    group: "Credit",
    unit: "percent",
    priority: 23,
    frequency: "Daily",
    audience: ["信用", "债券"],
    description: "投资级公司债 OAS。优质信用市场的紧张程度。",
  },
  {
    symbol: "FRED:T10Y2Y",
    providerSymbol: "T10Y2Y",
    source: "FRED",
    name: "10Y-2Y Treasury Spread",
    group: "Rates",
    unit: "percent",
    priority: 24,
    frequency: "Daily",
    audience: ["宏观"],
    description: "10Y 减 2Y 利差。倒挂（<0）历史上是经典的衰退领先指标，平均提前 12-18 个月。",
  },
  {
    symbol: "FRED:T10Y3M",
    providerSymbol: "T10Y3M",
    source: "FRED",
    name: "10Y-3M Treasury Spread",
    group: "Rates",
    unit: "percent",
    priority: 25,
    frequency: "Daily",
    audience: ["宏观"],
    description: "10Y 减 3M 利差。NY Fed 衰退概率模型核心输入。",
  },
  {
    symbol: "FRED:DGS3MO",
    providerSymbol: "DGS3MO",
    source: "FRED",
    name: "U.S. 3M Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 26,
    frequency: "Daily",
    audience: ["宏观"],
    description: "3 个月国库券收益率，最贴近政策利率的市场报价。",
  },
  {
    symbol: "FRED:DGS5",
    providerSymbol: "DGS5",
    source: "FRED",
    name: "U.S. 5Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 27,
    frequency: "Daily",
    audience: ["宏观"],
    description: "5 年期国债收益率。反映 5 年内通胀和增长预期，加密 + 金融条件中点。",
  },
  {
    symbol: "FRED:DGS30",
    providerSymbol: "DGS30",
    source: "FRED",
    name: "U.S. 30Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 28,
    frequency: "Daily",
    audience: ["宏观"],
    description: "30 年期长债收益率，反映长期通胀和期限溢价。",
  },

  // ============================================================
  // TIER 3 — Equity indices + sectors (29-50)
  // ============================================================
  {
    symbol: "^DJI",
    source: "Yahoo Finance",
    name: "Dow Jones Industrial Average",
    group: "Equity",
    unit: "index",
    priority: 29,
    frequency: "Realtime",
    audience: ["股票"],
    description: "道琼斯工业 30 指数，偏价值/周期股。",
  },
  {
    symbol: "^RUT",
    source: "Yahoo Finance",
    name: "Russell 2000 (Small Caps)",
    group: "Equity",
    unit: "index",
    priority: 30,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "美国小盘股指数，对本土经济、信贷、利率最敏感。",
  },
  {
    symbol: "IWM",
    source: "Yahoo Finance",
    name: "iShares Russell 2000 ETF (IWM)",
    group: "Equity",
    unit: "usd",
    priority: 30.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "小盘"],
    description: "Russell 2000 可交易 ETF。小盘股 Beta、融资条件和风险偏好的盘中代理。",
  },
  {
    symbol: "^SOX",
    source: "Yahoo Finance",
    name: "PHLX Semiconductor (SOX)",
    group: "Equity",
    unit: "index",
    priority: 31,
    frequency: "Realtime",
    audience: ["股票", "科技"],
    description: "费城半导体指数，AI / 科技 / BTC 风险偏好的核心代理，领先纳指。",
  },
  {
    symbol: "SMH",
    source: "Yahoo Finance",
    name: "VanEck Semiconductor ETF (SMH)",
    group: "Equity",
    unit: "usd",
    priority: 31.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "半导体"],
    description: "半导体 ETF，NVDA / TSM / AVGO 权重高，是 AI 和全球科技资本开支的高流动性代理。",
  },
  {
    symbol: "XLK",
    source: "Yahoo Finance",
    name: "Technology Select Sector SPDR (XLK)",
    group: "Equity",
    unit: "usd",
    priority: 31.2,
    frequency: "Realtime",
    audience: ["股票", "量化", "科技"],
    description: "美股科技板块 ETF。用于分离指数上涨中科技权重的贡献。",
  },
  {
    symbol: "XLF",
    source: "Yahoo Finance",
    name: "Financial Select Sector SPDR (XLF)",
    group: "Equity",
    unit: "usd",
    priority: 31.3,
    frequency: "Realtime",
    audience: ["股票", "量化", "金融"],
    description: "美股金融板块 ETF。对收益率曲线、信用利差和银行风险敏感。",
  },
  {
    symbol: "KRE",
    source: "Yahoo Finance",
    name: "SPDR S&P Regional Banking ETF (KRE)",
    group: "Equity",
    unit: "usd",
    priority: 31.4,
    frequency: "Realtime",
    audience: ["股票", "量化", "银行"],
    description: "美国区域银行 ETF。金融压力、存款外流和信用收缩的高敏感代理。",
  },
  {
    symbol: "XLE",
    source: "Yahoo Finance",
    name: "Energy Select Sector SPDR (XLE)",
    group: "Equity",
    unit: "usd",
    priority: 31.5,
    frequency: "Realtime",
    audience: ["股票", "量化", "能源"],
    description: "美股能源板块 ETF。与油价、通胀和周期股轮动高度相关。",
  },
  {
    symbol: "ARKK",
    source: "Yahoo Finance",
    name: "ARK Innovation ETF (ARKK)",
    group: "Equity",
    unit: "usd",
    priority: 32,
    frequency: "Realtime",
    audience: ["股票", "加密"],
    description: "高 Beta 创新 / 成长股 ETF，BTC 同步性强；流动性边际信号。",
  },
  {
    symbol: "KWEB",
    source: "Yahoo Finance",
    name: "KraneShares CSI China Internet (KWEB)",
    group: "Equity",
    unit: "usd",
    priority: 33,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "中国互联网中概股 ETF，反映海外资金对中国资产的态度。",
  },
  {
    symbol: "EEM",
    source: "Yahoo Finance",
    name: "MSCI Emerging Markets ETF (EEM)",
    group: "Equity",
    unit: "usd",
    priority: 34,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "新兴市场 ETF，对美元/美债收益率敏感；BTC 的风险偏好镜像。",
  },
  {
    symbol: "ACWI",
    source: "Yahoo Finance",
    name: "MSCI All Country World ETF",
    group: "Equity",
    unit: "usd",
    priority: 35,
    frequency: "Realtime",
    audience: ["股票"],
    description: "MSCI 全球股票市场 ETF。全球风险偏好综合代理。",
  },
  {
    symbol: "^HSI",
    source: "Yahoo Finance",
    name: "Hang Seng Index",
    group: "Equity",
    unit: "index",
    priority: 36,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "香港恒生指数，反映港股、中资科技/金融。",
  },
  {
    symbol: "^HSCE",
    source: "Yahoo Finance",
    name: "Hang Seng China Enterprises (H-Shares)",
    group: "Equity",
    unit: "index",
    priority: 37,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "国企指数，港股中资金融/能源大型公司加权。",
  },
  {
    symbol: "000300.SS",
    source: "Yahoo Finance",
    name: "CSI 300 (沪深 300)",
    group: "Equity",
    unit: "index",
    priority: 38,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "沪深 300 指数，A 股核心宽基。",
  },
  {
    symbol: "000001.SS",
    source: "Yahoo Finance",
    name: "Shanghai Composite (上证)",
    group: "Equity",
    unit: "index",
    priority: 39,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "上证综合指数，A 股大盘风险偏好基准。",
  },
  {
    symbol: "399006.SZ",
    source: "Yahoo Finance",
    name: "ChiNext (创业板指)",
    group: "Equity",
    unit: "index",
    priority: 40,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "创业板指数，A 股成长股代表，对利率和风险偏好敏感。",
  },
  {
    symbol: "^N225",
    source: "Yahoo Finance",
    name: "Nikkei 225",
    group: "Equity",
    unit: "index",
    priority: 41,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "日经 225，与 USDJPY 同向：日元贬值常拉升日股。",
  },
  {
    symbol: "^GDAXI",
    source: "Yahoo Finance",
    name: "DAX 40",
    group: "Equity",
    unit: "index",
    priority: 42,
    frequency: "Realtime",
    audience: ["股票", "欧洲"],
    description: "德国 DAX 40，欧元区核心制造业风向标。",
  },
  {
    symbol: "^FTSE",
    source: "Yahoo Finance",
    name: "FTSE 100",
    group: "Equity",
    unit: "index",
    priority: 43,
    frequency: "Realtime",
    audience: ["股票", "欧洲"],
    description: "英国富时 100，能源/金融权重高。",
  },
  {
    symbol: "^KS11",
    source: "Yahoo Finance",
    name: "KOSPI",
    group: "Equity",
    unit: "index",
    priority: 44,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "韩国综合指数，半导体出口的全球科技周期领先指标。",
  },

  // Volatility (sub-tier 45-50)
  {
    symbol: "^VXN",
    source: "Yahoo Finance",
    name: "Nasdaq 100 Volatility (VXN)",
    group: "Volatility",
    unit: "index",
    priority: 45,
    frequency: "Realtime",
    audience: ["波动率", "科技"],
    description: "纳指 100 隐含波动率，对科技股 / BTC 风险更敏感。",
  },
  {
    symbol: "^VVIX",
    source: "Yahoo Finance",
    name: "VVIX (Vol of Vol)",
    group: "Volatility",
    unit: "index",
    priority: 46,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "VIX 自身的波动率。突发事件风险溢价的二阶指标。",
  },
  {
    symbol: "^SKEW",
    source: "Yahoo Finance",
    name: "CBOE SKEW Index",
    group: "Volatility",
    unit: "index",
    priority: 47,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "S&P 500 期权左尾偏度。值越高，市场对“黑天鹅”的定价越贵。",
  },
  {
    symbol: "^OVX",
    source: "Yahoo Finance",
    name: "Crude Oil VIX",
    group: "Volatility",
    unit: "index",
    priority: 48,
    frequency: "Realtime",
    audience: ["波动率", "商品"],
    description: "WTI 原油隐含波动率，能源风险定价。",
  },
  {
    symbol: "^GVZ",
    source: "Yahoo Finance",
    name: "Gold VIX",
    group: "Volatility",
    unit: "index",
    priority: 49,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "黄金隐含波动率，避险/通胀情绪的二阶代理。",
  },

  // ============================================================
  // TIER 4 — Employment / Growth / Real Estate (51-75)
  // ============================================================
  {
    symbol: "FRED:ICSA",
    providerSymbol: "ICSA",
    source: "FRED",
    name: "Initial Jobless Claims",
    group: "Employment",
    unit: "count",
    priority: 51,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "每周首次申请失业救济人数。劳动力市场最高频拐点指标。",
  },
  {
    symbol: "FRED:CCSA",
    providerSymbol: "CCSA",
    source: "FRED",
    name: "Continuing Jobless Claims",
    group: "Employment",
    unit: "count",
    priority: 52,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "持续申请失业救济总人数，反映再就业速度。",
  },
  {
    symbol: "FRED:JTSJOL",
    providerSymbol: "JTSJOL",
    source: "FRED",
    name: "JOLTS Job Openings",
    group: "Employment",
    unit: "count",
    priority: 53,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "JOLTS 职位空缺数（千个）。劳动力需求强弱的核心指标。",
    transform: (value) => value * 1000,
  },
  {
    symbol: "FRED:CES0500000003",
    providerSymbol: "CES0500000003",
    source: "FRED",
    name: "Avg Hourly Earnings (Private)",
    group: "Employment",
    unit: "usd",
    priority: 54,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "私营部门平均时薪（美元/小时）。工资通胀的核心来源。",
  },
  {
    symbol: "FRED:UMCSENT",
    providerSymbol: "UMCSENT",
    source: "FRED",
    name: "U. of Michigan Consumer Sentiment",
    group: "Sentiment",
    unit: "index",
    priority: 55,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "密歇根大学消费者信心指数。消费支出和零售前景的领先指标。",
  },
  {
    symbol: "FRED:MICH",
    providerSymbol: "MICH",
    source: "FRED",
    name: "UMich 1Y Inflation Expectations",
    group: "Inflation",
    unit: "percent",
    priority: 56,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "密歇根大学 1 年通胀预期。Fed 对「通胀预期是否锚定」的关键参考。",
  },
  {
    symbol: "FRED:T5YIE",
    providerSymbol: "T5YIE",
    source: "FRED",
    name: "5Y Breakeven Inflation Rate",
    group: "Inflation",
    unit: "percent",
    priority: 56.5,
    frequency: "Daily",
    audience: ["宏观", "债券", "加密"],
    description: "5 年期隐含通胀预期（名义国债 - TIPS 实际利率）。\n上升 = 市场预期通胀走高；下降 = 通胀预期回落。",
  },
  {
    symbol: "FRED:T10YIE",
    providerSymbol: "T10YIE",
    source: "FRED",
    name: "10Y Breakeven Inflation Rate",
    group: "Inflation",
    unit: "percent",
    priority: 56.6,
    frequency: "Daily",
    audience: ["宏观", "债券"],
    description: "10 年期隐含通胀预期。市场对中长期通胀的定价，影响实际利率和资产估值。",
  },
  {
    symbol: "FRED:PPIACO",
    providerSymbol: "PPIACO",
    source: "FRED",
    name: "Producer Price Index (PPI)",
    group: "Inflation",
    unit: "index",
    priority: 57,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "生产者价格指数（所有商品）。企业成本端，CPI / PCE 的领先信号。",
  },
  {
    symbol: "FRED:RSAFS",
    providerSymbol: "RSAFS",
    source: "FRED",
    name: "U.S. Retail Sales",
    group: "Growth",
    unit: "usd",
    priority: 58,
    frequency: "Monthly",
    audience: ["宏观", "消费"],
    description: "美国零售销售（百万美元，季调）。消费韧性的核心月度数据。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:INDPRO",
    providerSymbol: "INDPRO",
    source: "FRED",
    name: "Industrial Production Index",
    group: "Growth",
    unit: "index",
    priority: 59,
    frequency: "Monthly",
    audience: ["宏观", "商品"],
    description: "美国工业生产指数。实体制造业景气度。",
  },
  {
    symbol: "FRED:TCU",
    providerSymbol: "TCU",
    source: "FRED",
    name: "Capacity Utilization (Total)",
    group: "Growth",
    unit: "percent",
    priority: 60,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "总产能利用率（%）。供需紧张程度，影响成本和通胀压力。",
  },
  {
    symbol: "FRED:DGORDER",
    providerSymbol: "DGORDER",
    source: "FRED",
    name: "Durable Goods Orders",
    group: "Growth",
    unit: "usd",
    priority: 61,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "耐用品订单（百万美元）。企业资本开支前瞻。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:GDP",
    providerSymbol: "GDP",
    source: "FRED",
    name: "U.S. Nominal GDP (Quarterly)",
    group: "Growth",
    unit: "usd",
    priority: 62,
    frequency: "Quarterly",
    audience: ["宏观"],
    description: "美国名义 GDP（十亿美元，季度）。经济总量周期。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:GDPNOW",
    providerSymbol: "GDPNOW",
    source: "FRED",
    name: "Atlanta Fed GDPNow",
    group: "Growth",
    unit: "percent",
    priority: 62.5,
    frequency: "Weekly",
    audience: ["宏观", "股票"],
    description: "亚特兰大联储 GDPNow 实时 GDP 预测（季度环比年化）。\n高频跟踪当季 GDP 增速预期变化，领先官方数据发布。",
  },
  {
    symbol: "FRED:NFCI",
    providerSymbol: "NFCI",
    source: "FRED",
    name: "Chicago Fed NFCI",
    group: "Credit",
    unit: "index",
    priority: 22.5,
    frequency: "Weekly",
    audience: ["宏观", "信用", "加密"],
    description: "芝加哥联储国家金融条件指数。\n负值 = 金融条件宽松；正值 = 金融条件紧张。\n> 0 通常压制风险资产。",
  },
  {
    symbol: "FRED:MORTGAGE30US",
    providerSymbol: "MORTGAGE30US",
    source: "FRED",
    name: "30Y Fixed Mortgage Rate",
    group: "RealEstate",
    unit: "percent",
    priority: 63,
    frequency: "Weekly",
    audience: ["地产"],
    description: "美国 30 年固定房贷利率（Freddie Mac）。居民部门利率压力的核心指标。",
  },
  {
    symbol: "FRED:HSN1F",
    providerSymbol: "HSN1F",
    source: "FRED",
    name: "New Home Sales",
    group: "RealEstate",
    unit: "count",
    priority: 64,
    frequency: "Monthly",
    audience: ["地产"],
    description: "美国新屋销售年化率（千套）。利率敏感的需求端。",
    transform: (value) => value * 1000,
  },
  {
    symbol: "FRED:PERMIT",
    providerSymbol: "PERMIT",
    source: "FRED",
    name: "Building Permits",
    group: "RealEstate",
    unit: "count",
    priority: 65,
    frequency: "Monthly",
    audience: ["地产"],
    description: "美国营建许可（千套，年化）。住宅建设的领先指标。",
    transform: (value) => value * 1000,
  },

  // ============================================================
  // TIER 5 — FX (66-75)
  // ============================================================
  {
    symbol: "EURUSD=X",
    source: "Yahoo Finance",
    name: "EUR/USD",
    group: "FX",
    unit: "ratio",
    priority: 66,
    frequency: "Realtime",
    audience: ["FX", "宏观"],
    description: "全球交易量最大的货币对，DXY 主成分。",
  },
  {
    symbol: "USDJPY=X",
    source: "Yahoo Finance",
    name: "USD/JPY",
    group: "FX",
    unit: "ratio",
    priority: 67,
    frequency: "Realtime",
    audience: ["FX", "套息交易"],
    description: "美日汇率。套息交易核心，与美债收益率高度相关。",
  },
  {
    symbol: "USDCNH=X",
    source: "Yahoo Finance",
    name: "USD/CNH (离岸人民币)",
    group: "FX",
    unit: "ratio",
    priority: 68,
    frequency: "Realtime",
    audience: ["FX", "中国"],
    description: "美元兑离岸人民币。中美利差 + 人民币市场化预期。",
  },
  {
    symbol: "GBPUSD=X",
    source: "Yahoo Finance",
    name: "GBP/USD",
    group: "FX",
    unit: "ratio",
    priority: 69,
    frequency: "Realtime",
    audience: ["FX"],
    description: "英镑兑美元，与英国利率/政治情绪密切相关。",
  },
  {
    symbol: "AUDUSD=X",
    source: "Yahoo Finance",
    name: "AUD/USD",
    group: "FX",
    unit: "ratio",
    priority: 70,
    frequency: "Realtime",
    audience: ["FX", "商品"],
    description: "澳元兑美元，大宗商品代理货币，与中国经济相关。",
  },
  {
    symbol: "USDKRW=X",
    source: "Yahoo Finance",
    name: "USD/KRW",
    group: "FX",
    unit: "ratio",
    priority: 71,
    frequency: "Realtime",
    audience: ["FX", "亚太"],
    description: "美韩汇率，亚洲风险偏好和半导体周期的领先信号之一。",
  },

  // ============================================================
  // TIER 6 — Commodities (72-90)
  // ============================================================
  {
    symbol: "GC=F",
    source: "Yahoo Finance",
    name: "Gold Futures",
    group: "Commodity",
    unit: "usd",
    priority: 72,
    frequency: "Realtime",
    audience: ["商品", "避险"],
    description: "COMEX 黄金期货。避险、抗通胀、与实际利率反向。",
  },
  {
    symbol: "CL=F",
    source: "Yahoo Finance",
    name: "WTI Crude Oil",
    group: "Commodity",
    unit: "usd",
    priority: 73,
    frequency: "Realtime",
    audience: ["商品", "通胀"],
    description: "WTI 原油期货，美国基准油价；通胀核心驱动。",
  },
  {
    symbol: "BZ=F",
    source: "Yahoo Finance",
    name: "Brent Crude Oil",
    group: "Commodity",
    unit: "usd",
    priority: 74,
    frequency: "Realtime",
    audience: ["商品"],
    description: "布伦特原油，欧亚基准油价。",
  },
  {
    symbol: "SI=F",
    source: "Yahoo Finance",
    name: "Silver Futures",
    group: "Commodity",
    unit: "usd",
    priority: 75,
    frequency: "Realtime",
    audience: ["商品"],
    description: "COMEX 白银期货，弹性比黄金大，含工业属性。",
  },
  {
    symbol: "HG=F",
    source: "Yahoo Finance",
    name: "Copper (Dr. Copper)",
    group: "Commodity",
    unit: "usd",
    priority: 76,
    frequency: "Realtime",
    audience: ["商品", "宏观"],
    description: "铜期货，全球工业景气和中国需求的领先指标。",
  },
  {
    symbol: "NG=F",
    source: "Yahoo Finance",
    name: "Natural Gas",
    group: "Commodity",
    unit: "usd",
    priority: 77,
    frequency: "Realtime",
    audience: ["商品"],
    description: "亨利港天然气期货，季节性极强。",
  },
  {
    symbol: "PL=F",
    source: "Yahoo Finance",
    name: "Platinum Futures",
    group: "Commodity",
    unit: "usd",
    priority: 78,
    frequency: "Realtime",
    audience: ["商品"],
    description: "铂金期货，工业 + 贵金属属性兼具。",
  },
  {
    symbol: "ZC=F",
    source: "Yahoo Finance",
    name: "Corn Futures",
    group: "Commodity",
    unit: "usd",
    priority: 79,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 玉米期货，受气候、乙醇需求、饲料驱动。",
  },
  {
    symbol: "ZW=F",
    source: "Yahoo Finance",
    name: "Wheat Futures",
    group: "Commodity",
    unit: "usd",
    priority: 80,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 小麦期货，地缘 + 气候敏感品种。",
  },
  {
    symbol: "ZS=F",
    source: "Yahoo Finance",
    name: "Soybean Futures",
    group: "Commodity",
    unit: "usd",
    priority: 81,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 大豆期货，中美贸易/南美天气敏感。",
  },
  {
    symbol: "DBC",
    source: "Yahoo Finance",
    name: "Invesco DB Commodity Index (DBC)",
    group: "Commodity",
    unit: "usd",
    priority: 82,
    frequency: "Realtime",
    audience: ["商品", "宏观"],
    description: "广义商品指数 ETF（能源 + 农产品 + 金属）。CRB 指数的可投资代理。",
  },

  // Equity Futures
  {
    symbol: "ES=F",
    source: "Yahoo Finance",
    name: "S&P 500 E-mini Futures",
    group: "Equity",
    unit: "index",
    priority: 83,
    frequency: "Realtime",
    audience: ["期货"],
    description: "S&P 500 电子迷你期货 (ES)，盘前/盘后定价工具。",
  },
  {
    symbol: "NQ=F",
    source: "Yahoo Finance",
    name: "Nasdaq 100 Futures",
    group: "Equity",
    unit: "index",
    priority: 84,
    frequency: "Realtime",
    audience: ["期货"],
    description: "纳斯达克 100 期货 (NQ)。",
  },
  {
    symbol: "ZN=F",
    source: "Yahoo Finance",
    name: "10Y Treasury Note Futures",
    group: "Rates",
    unit: "usd",
    priority: 85,
    frequency: "Realtime",
    audience: ["期货", "债券"],
    description: "10Y 美债期货 (ZN)，机构对冲利率风险的核心。",
  },
  {
    symbol: "ZB=F",
    source: "Yahoo Finance",
    name: "30Y Treasury Bond Futures",
    group: "Rates",
    unit: "usd",
    priority: 86,
    frequency: "Realtime",
    audience: ["期货", "债券"],
    description: "30Y 长债期货 (ZB)，期限溢价 / 通胀预期衍生工具。",
  },

  // ============================================================
  // TIER 7 — Credit ETFs (87-92)
  // ============================================================
  {
    symbol: "TLT",
    source: "Yahoo Finance",
    name: "iShares 20+Y Treasury (TLT)",
    group: "Rates",
    unit: "usd",
    priority: 87,
    frequency: "Realtime",
    audience: ["债券"],
    description: "长债 ETF，价格与长债收益率反向。",
  },
  {
    symbol: "IEF",
    source: "Yahoo Finance",
    name: "iShares 7-10Y Treasury (IEF)",
    group: "Rates",
    unit: "usd",
    priority: 88,
    frequency: "Realtime",
    audience: ["债券"],
    description: "7-10Y 美债 ETF，经典股债组合的债端。",
  },
  {
    symbol: "TIP",
    source: "Yahoo Finance",
    name: "TIPS ETF (Real Yield Proxy)",
    group: "Rates",
    unit: "usd",
    priority: 89,
    frequency: "Realtime",
    audience: ["债券"],
    description: "通胀挂钩国债 ETF，反映实际利率/通胀预期变化。",
  },
  {
    symbol: "HYG",
    source: "Yahoo Finance",
    name: "iBoxx HY Credit ETF (HYG)",
    group: "Credit",
    unit: "usd",
    priority: 90,
    frequency: "Realtime",
    audience: ["信用"],
    description: "美国高收益债 ETF。下跌常领先股市风险偏好转弱。",
  },
  {
    symbol: "LQD",
    source: "Yahoo Finance",
    name: "iBoxx IG Credit ETF (LQD)",
    group: "Credit",
    unit: "usd",
    priority: 91,
    frequency: "Realtime",
    audience: ["信用"],
    description: "投资级公司债 ETF。",
  },
  {
    symbol: "EMB",
    source: "Yahoo Finance",
    name: "EM Bond ETF (EMB)",
    group: "Credit",
    unit: "usd",
    priority: 92,
    frequency: "Realtime",
    audience: ["新兴市场"],
    description: "新兴市场美元主权债 ETF。",
  },

  // ============================================================
  // TIER 8 — Crypto / On-chain (93-130)
  // ============================================================
  {
    symbol: "BTC-USD",
    source: "Yahoo Finance",
    name: "Bitcoin Spot (Yahoo)",
    group: "Crypto",
    unit: "usd",
    priority: 93,
    frequency: "Realtime",
    audience: ["加密"],
    description: "比特币现货，Yahoo 24/7 数据；可与传统资产同界面比较。",
  },
  {
    symbol: "ETH-USD",
    source: "Yahoo Finance",
    name: "Ethereum Spot",
    group: "Crypto",
    unit: "usd",
    priority: 94,
    frequency: "Realtime",
    audience: ["加密"],
    description: "以太坊现货。ETH/BTC 比反映山寨季强度。",
  },
  {
    symbol: "IBIT",
    source: "Yahoo Finance",
    name: "iShares Bitcoin Trust (IBIT)",
    group: "Crypto",
    unit: "usd",
    priority: 95,
    frequency: "Realtime",
    audience: ["机构加密"],
    description: "BlackRock 现货 BTC ETF。机构买盘强弱代理。",
  },
  {
    symbol: "FBTC",
    source: "Yahoo Finance",
    name: "Fidelity Bitcoin ETF (FBTC)",
    group: "Crypto",
    unit: "usd",
    priority: 96,
    frequency: "Realtime",
    audience: ["机构加密"],
    description: "Fidelity 现货 BTC ETF。",
  },
  {
    symbol: "GBTC",
    source: "Yahoo Finance",
    name: "Grayscale Bitcoin Trust (GBTC)",
    group: "Crypto",
    unit: "usd",
    priority: 97,
    frequency: "Realtime",
    audience: ["机构加密"],
    description: "Grayscale BTC 信托，历史抛压来源。",
  },
  {
    symbol: "ETHE",
    source: "Yahoo Finance",
    name: "Grayscale Ethereum Trust (ETHE)",
    group: "Crypto",
    unit: "usd",
    priority: 98,
    frequency: "Realtime",
    audience: ["机构加密"],
    description: "Grayscale ETH 信托。",
  },

  // On-chain via Blockchain.com
  {
    symbol: "BLOCKCHAIN:hash-rate",
    providerSymbol: "hash-rate",
    source: "Blockchain.com",
    name: "BTC Hash Rate",
    group: "OnChain",
    unit: "count",
    priority: 110,
    frequency: "Daily",
    audience: ["加密", "矿工"],
    description: "比特币全网算力（TH/s）。网络安全和矿工健康度。\n大幅下降常对应矿难或硬件迁徙。",
  },
  {
    symbol: "BLOCKCHAIN:difficulty",
    providerSymbol: "difficulty",
    source: "Blockchain.com",
    name: "BTC Mining Difficulty",
    group: "OnChain",
    unit: "count",
    priority: 111,
    frequency: "Bi-weekly",
    audience: ["加密", "矿工"],
    description: "比特币挖矿难度。每 2016 个区块（约 2 周）调整一次。",
  },
  {
    symbol: "BLOCKCHAIN:n-unique-addresses",
    providerSymbol: "n-unique-addresses",
    source: "Blockchain.com",
    name: "BTC Active Addresses",
    group: "OnChain",
    unit: "count",
    priority: 112,
    frequency: "Daily",
    audience: ["加密"],
    description: "每日唯一活跃地址数。网络真实使用度。",
  },
  {
    symbol: "BLOCKCHAIN:n-transactions",
    providerSymbol: "n-transactions",
    source: "Blockchain.com",
    name: "BTC Transactions/day",
    group: "OnChain",
    unit: "count",
    priority: 113,
    frequency: "Daily",
    audience: ["加密"],
    description: "每日链上交易笔数。",
  },
  {
    symbol: "BLOCKCHAIN:estimated-transaction-volume-usd",
    providerSymbol: "estimated-transaction-volume-usd",
    source: "Blockchain.com",
    name: "BTC On-chain Volume (USD)",
    group: "OnChain",
    unit: "usd",
    priority: 114,
    frequency: "Daily",
    audience: ["加密"],
    description: "每日链上估计转账总额（美元）。大额转移和网络活跃度。",
  },
  {
    symbol: "BLOCKCHAIN:market-cap",
    providerSymbol: "market-cap",
    source: "Blockchain.com",
    name: "BTC Market Cap (History)",
    group: "Crypto",
    unit: "usd",
    priority: 115,
    frequency: "Daily",
    audience: ["加密"],
    description: "BTC 历史市值曲线（USD）。",
  },

  // Stablecoin liquidity via DefiLlama
  {
    symbol: "DEFILLAMA:stablecoins-total",
    providerSymbol: "stablecoins-total",
    source: "DefiLlama",
    name: "Stablecoin Total Market Cap",
    group: "Crypto",
    unit: "usd",
    priority: 116,
    frequency: "Daily",
    audience: ["加密", "流动性"],
    description:
      '加密市场"场内美元"总额。下行 = 流出；上行 = 流入。\nBTC 牛熊周期常领先于 stablecoin 总市值变化。',
  },
  {
    symbol: "DEFILLAMA:tvl-defi",
    providerSymbol: "tvl-defi",
    source: "DefiLlama",
    name: "Total DeFi TVL",
    group: "Crypto",
    unit: "usd",
    priority: 117,
    frequency: "Daily",
    audience: ["加密", "DeFi"],
    description: "DeFi 协议总锁仓量（USD）。链上资金活跃度。",
  },

  // Sentiment
  {
    symbol: "ALTERNATIVE:fng",
    providerSymbol: "fng",
    source: "Alternative.me",
    name: "Crypto Fear & Greed",
    group: "Sentiment",
    unit: "index",
    priority: 130,
    frequency: "Daily",
    audience: ["加密", "情绪"],
    description: "Alternative.me 综合波动率、动量、社交、调查的恐慌贪婪指数（0-100）。",
  },
]

// =====================================================================
// Indicators we deliberately do NOT integrate (paid / unavailable APIs).
// Listed here so the team has a single source of truth on coverage gaps.
// =====================================================================
export const SKIPPED_INDICATORS = [
  {
    name: "CME FedWatch / Fed Funds Implied Probability",
    reason: "需要 CME Group 付费数据 (CME Direct / FedWatch API)",
  },
  { name: "CFTC Commitments of Traders (COT)", reason: "CFTC 提供周报 ZIP，需要单独解析与清洗" },
  { name: "China M2 / TSF / New Loans / Credit", reason: "PBoC 无开放 JSON API，可走 akshare 等离线数据源" },
  { name: "China NBS 数据（CPI/PPI/GDP/PMI/零售/进出口）", reason: "需要 akshare/Wind/同花顺等本地数据源" },
  { name: "Glassnode / CryptoQuant 高级链上 (MVRV、NUPL、SOPR、矿工储备、交易所余额)", reason: "全部付费 API" },
  { name: "Deribit BTC 期权 IV / Skew / Max Pain", reason: "Deribit API 限流 + 计算成本高" },
  { name: "BTC ETF 净流入 (Farside)", reason: "Farside 是 HTML 表格，已被反爬；BlackRock 13F 季度披露" },
  { name: "Bloomberg / Reuters NLP 新闻情绪", reason: "需要 Bloomberg/Reuters 终端订阅" },
  { name: "X / Reddit / Google Trends / 百度指数", reason: "API 付费或速率限制严" },
  { name: "美股 Put/Call Ratio / Cboe 期权数据", reason: "Cboe DataShop 付费" },
  { name: "ICE MOVE Index", reason: "ICE BofA 付费；FRED 上没有；可用 ^TYX 波动率自算近似" },
  { name: "Goldman / Fed 金融条件指数 FCI", reason: "需 Bloomberg；可用 ChicagoFed FRED NFCI 近似" },
  { name: "美股 EPS 预期 / Forward PE / ERP", reason: "FactSet / Bloomberg 付费" },
  { name: "ETF 资金流 / 共同基金资金流 / A股北向 / 港股南向", reason: "需要 ICI / 港交所付费源" },
]

export const MACRO_INDICATOR_MAP: Record<string, MacroIndicatorMeta> = Object.fromEntries(
  MACRO_INDICATORS.map((entry) => [entry.symbol, entry]),
)

export const MACRO_PRIMARY_SYMBOLS: string[] = MACRO_INDICATORS.filter((entry) => entry.priority <= 12).map(
  (entry) => entry.symbol,
)
