import type { MacroDataSource, MacroGroup, MacroUnit } from "@/lib/types"

export interface MacroIndicatorMeta {
  /** Stable identifier (used as React key and indicator url). For Yahoo this is the ticker; for FRED it is the series id. */
  symbol: string
  /** Provider-specific identifier; defaults to `symbol` if omitted. */
  providerSymbol?: string
  name: string
  group: MacroGroup
  unit: MacroUnit
  source: MacroDataSource
  /** Lower number = more important. Used for sorting + selecting "实时" KPI strip. */
  priority: number
  description: string
  audience: string[]
  frequency: string
  macroRank?: number
  macroCategory?: string
  meaning?: string
  impact?: string
  sourceNote?: string
  transform?: (value: number) => number
}

const dividedByTen = (value: number) => value / 10

interface MacroPriorityCategory {
  rank: number
  label: string
  symbols: readonly string[]
  meaning: string
  impact: string
  sourceNote: string
}

export const MACRO_PRIORITY_CATEGORIES: readonly MacroPriorityCategory[] = [
  {
    rank: 1,
    label: "1 利率 / 央行政策",
    symbols: ["FRED:DFF", "FRED:DGS2", "FRED:DGS3MO", "FRED:T10Y2Y", "FRED:T10Y3M", "EM:CN_LPR_1Y", "EM:CN_LPR_5Y", "EM:CN_RRR_LARGE", "EM:CN_RRR_SMALL"],
    meaning: "Fed funds and short-end Treasury rates show the policy-rate anchor and market-implied easing/tightening path.",
    impact: "Rates up usually compress valuations and liquidity; rates down usually support duration assets and equities.",
    sourceNote: "FRED for U.S. policy-rate proxies; China LPR (1Y/5Y) and big-bank RRR via Eastmoney datacenter (PBoC releases). MLF is still not wired.",
  },
  {
    rank: 2,
    label: "2 10年期国债收益率",
    symbols: ["FRED:DGS10", "FRED:DFII10", "FRED:DGS5", "FRED:DGS30", "EM:CN_10Y", "EM:CN_2Y", "EM:CN_10Y_2Y", "ZN=F", "ZB=F", "TLT", "IEF", "TIP"],
    meaning: "10Y nominal and real yields are the core discount-rate inputs for global asset valuation.",
    impact: "Yield up pressures growth stocks and gold; yield down usually supports valuations and risk appetite.",
    sourceNote: "FRED and Yahoo for U.S.; China 2Y/10Y treasury yields (中债估值) via Eastmoney datacenter.",
  },
  {
    rank: 3,
    label: "3 通胀数据",
    symbols: ["FRED:CPIAUCSL", "FRED:CPILFESL", "FRED:PCEPI", "FRED:PCEPILFE", "FRED:PPIACO", "FRED:MICH", "FRED:T5YIE", "FRED:T10YIE", "EM:CN_CPI_YOY", "EM:CN_CPI_MOM", "EM:CN_PPI_YOY", "FRED:CHNCPIALLMINMEI"],
    meaning: "CPI, core CPI, PCE, core PCE, PPI and inflation expectations decide whether central banks can ease.",
    impact: "Hot inflation delays cuts and hurts long-duration assets; cooling inflation supports easing expectations.",
    sourceNote: "FRED U.S. inflation stack; China CPI/PPI YoY via Eastmoney (NBS monthly release) plus OECD CPI level via FRED.",
  },
  {
    rank: 4,
    label: "4 就业数据",
    symbols: ["FRED:UNRATE", "FRED:PAYEMS", "FRED:ICSA", "FRED:CCSA", "FRED:JTSJOL", "FRED:CES0500000003", "SNAP:NBS_UNEMPLOYMENT"],
    meaning:
      "Payrolls, unemployment, wages, job openings and claims are the second pillar of the Fed's dual mandate alongside inflation. Bauer-Swanson (2023) shows employment surprises are the second-largest driver of Fed policy surprises; elevated from rank 7.",
    impact: "Too-hot labor delays cuts and keeps rates higher-for-longer; Sahm-rule unemployment rise raises recession odds and pulls forward easing expectations.",
    sourceNote: "FRED U.S. labor-market stack.",
  },
  {
    rank: 5,
    label: "5 社融 / M2 / 信贷",
    symbols: [
      "FRED:M2SL",
      "FRED:M1SL",
      "FRED:M2REAL",
      "FRED:M2V",
      "FRED:BOGMBASE",
      "FRED:MYAGM2CNM189N",
      "FRED:MYAGM1CNM189N",
      "EM:CN_M2",
      "EM:CN_M2_YOY",
      "EM:CN_M1",
      "EM:CN_M1_YOY",
      "EM:CN_M0",
      "EM:CN_M0_YOY",
      "EM:CN_M1_M2_GAP",
      "EM:CN_NEW_LOANS",
      "EM:CN_NEW_LOANS_YTD",
      "FRED:TOTLL",
      "FRED:WALCL",
      "FRED:TOTRESNS",
      "FRED:RRPONTSYD",
      "FRED:WTREGEN",
      "FRED:BAMLH0A0HYM2",
      "FRED:BAMLC0A0CM",
      "FRED:NFCI",
    ],
    meaning: "Money supply, bank credit, reserves and credit spreads describe liquidity and credit-cycle breadth — the transmission mechanism from Fed policy to asset prices.",
    impact: "Credit and money expanding is usually risk-supportive; credit spreads or financial conditions rising is risk-negative.",
    sourceNote: "U.S. via FRED; China current M0/M1/M2 levels + YoY and monthly new RMB loans via Eastmoney (PBoC release). 社融 (TSF) still needs the PBoC/mofcom feed — see gap list.",
  },
  {
    rank: 6,
    label: "6 PMI",
    symbols: ["FRED:IPMAN", "EM:CN_PMI_MFG", "EM:CN_PMI_NONMFG"],
    meaning:
      "PMI is the preferred leading survey signal for business cycle expansion/contraction; this stable stack uses manufacturing production as the fallback activity proxy.",
    impact: "PMI/proxy rising supports cyclicals and risk; falling warns on growth and manufacturing pressure.",
    sourceNote: "FRED manufacturing hard-data proxy for the U.S.; China official NBS manufacturing / non-manufacturing PMI via Eastmoney. Live ISM still needs a paid feed.",
  },
  {
    rank: 7,
    label: "7 GDP增速",
    symbols: ["FRED:GDPC1", "FRED:GDP", "FRED:GDPNOW", "EM:CN_GDP_YOY", "EM:CN_GDP_YTD"],
    meaning: "Real GDP, nominal GDP and GDPNow show the broad growth direction and nowcast revisions. GDP is a lagging confirmation; PMI (#6) and employment (#4) are more timely.",
    impact: "Growth acceleration supports earnings and cyclicals; sharp slowing raises recession and policy-easing odds.",
    sourceNote: "FRED / Atlanta Fed for U.S.; China quarterly real GDP YoY via Eastmoney (NBS).",
  },
  {
    rank: 8,
    label: "8 汇率",
    symbols: ["DX-Y.NYB", "CNY=X", "USDCNH=X", "FRED:DEXCHUS", "EURCNY=X", "CNYJPY=X", "EURUSD=X", "USDJPY=X", "GBPUSD=X", "AUDUSD=X", "USDKRW=X"],
    meaning: "DXY and key crosses show dollar liquidity, carry pressure and capital-flow stress.",
    impact: "A stronger USD usually pressures commodities, EM and Hong Kong/China risk assets; weaker USD helps.",
    sourceNote: "Yahoo Finance FX chart data.",
  },
  {
    rank: 9,
    label: "9 房地产数据",
    symbols: ["FRED:MORTGAGE30US", "FRED:HSN1F", "FRED:PERMIT", "FRED:PRFI", "SNAP:BIS_HPI_CN", "SNAP:PBOC_MORTGAGE_RATE", "SNAP:NBS_SALES", "SNAP:NBS_INVESTMENT", "SNAP:NBS_STARTS", "SNAP:NBS_COMPLETIONS", "SNAP:NBS_INVENTORY", "SNAP:NBS_MORTGAGE_FLOW", "SNAP:BIS_HPI_US", "SNAP:BIS_HPI_JP", "SNAP:BIS_HPI_DE", "SNAP:BIS_HPI_UK", "SNAP:BIS_HPI_AU"],
    meaning: "Mortgage rates, new home sales, permits and residential investment show rate-sensitive housing demand.",
    impact: "Housing demand/investment up supports cyclicals; mortgage-rate spikes or weak sales pressure growth.",
    sourceNote: "FRED U.S. housing proxies; China housing sales/starts/completions/inventory/按揭 from NBS 统计公报 and PBoC mortgage rates (versioned snapshot, annual); BIS real house price indices for CN/US/JP/DE/UK/AU (quarterly).",
  },
  {
    rank: 10,
    label: "10 消费数据",
    symbols: ["FRED:RSAFS", "FRED:DSPIC96", "FRED:UMCSENT", "EM:CN_RETAIL_SALES", "EM:CN_RETAIL_YOY", "EM:CN_CONSUMER_CONFIDENCE", "SNAP:NBS_INCOME", "SNAP:NBS_URBAN_INCOME", "SNAP:NBS_INCOME_MEDIAN", "SNAP:NBS_DEPOSITS", "SNAP:NBS_URBAN_POPULATION"],
    meaning: "Retail sales, real disposable income and consumer sentiment explain household spending power.",
    impact: "Stronger consumption supports earnings; weak consumption hurts consumer, internet, travel and discretionary assets.",
    sourceNote: "FRED U.S. consumption proxies; China retail sales YoY and consumer confidence via Eastmoney (NBS); per-capita income, median income, household deposits and urban population from NBS 统计公报 snapshot.",
  },
  {
    rank: 11,
    label: "11 工业生产数据",
    symbols: ["FRED:INDPRO", "FRED:IPMAN", "FRED:TCU", "FRED:DGORDER", "EM:CN_INDUSTRIAL_YOY"],
    meaning: "Industrial production, capacity utilization and durable orders track manufacturing and cyclical demand.",
    impact: "Improvement supports industrials, materials and commodities; deterioration warns on cyclical slowdown.",
    sourceNote: "FRED U.S. hard-data proxies; China industrial value-added YoY via Eastmoney (NBS).",
  },
  {
    rank: 12,
    label: "12 固定资产投资",
    symbols: ["FRED:GPDI", "FRED:PNFI", "EM:CN_FAI_YTD_YOY"],
    meaning: "Private domestic and nonresidential fixed investment show capex strength.",
    impact: "Investment up supports machinery, materials and semis; investment down warns on business-cycle pressure.",
    sourceNote: "FRED U.S. investment proxies; China fixed-asset investment YoY via Eastmoney (NBS).",
  },
  {
    rank: 13,
    label: "13 企业盈利数据",
    symbols: ["FRED:CP", "^GSPC", "SPY", "^NDX", "QQQ", "^FTW5000"],
    meaning: "Corporate profits and broad equity indices connect macro conditions to the earnings cycle.",
    impact: "Profits and margin trends up support equities; profit pressure usually caps rallies and raises credit risk.",
    sourceNote: "FRED corporate profits plus Yahoo broad-market proxies; forward EPS needs paid data.",
  },
  {
    rank: 14,
    label: "14 市场资金流向",
    symbols: ["HYG", "LQD", "EMB", "ARKK", "KWEB", "EEM"],
    meaning: "Public proxies for money moving into equity and credit risk assets.",
    impact: "Proxy strength supports short- to medium-term risk appetite; proxy weakness warns on de-risking.",
    sourceNote: "Public market proxies only; ETF flow, northbound/southbound and margin-financing feeds need dedicated providers.",
  },
  {
    rank: 15,
    label: "15 成交额 / 换手率",
    symbols: ["FRED:DDDM02USA156NWDB", "FRED:DDDM02CNA156NWDB", "FRED:DDDM01USA156NWDB", "FRED:DDDM01CNA156NWDB", "EM:CN_A_TOTAL_MCAP", "EM:CN_A_TURNOVER"],
    meaning: "Stock value traded / GDP and market cap / GDP measure market activity and scale versus the real economy.",
    impact: "Higher turnover/market-cap ratios imply stronger market heat; falling ratios imply lower risk appetite.",
    sourceNote: "World Bank via FRED (annual, lagged) plus current SH+SZ total market cap and monthly turnover via Eastmoney (交易所统计).",
  },
  {
    rank: 16,
    label: "16 大宗商品价格",
    symbols: ["CL=F", "BZ=F", "GC=F", "HG=F", "SI=F", "NG=F", "PL=F", "DBC", "ZC=F", "ZW=F", "ZS=F"],
    meaning: "Oil, copper, gold and broad commodities show inflation pressure, industrial demand and safe-haven behavior.",
    impact: "Oil/copper up can lift cyclicals but pressure inflation; gold up often reflects real-rate or risk stress.",
    sourceNote: "Yahoo futures and ETF proxies.",
  },
  {
    rank: 17,
    label: "17 出口 / 贸易数据",
    symbols: ["FRED:EXPGS", "FRED:IMPGS", "EM:CN_EXPORTS", "EM:CN_IMPORTS", "EM:CN_TRADE_BALANCE", "EM:CN_TRADE_BALANCE_YTD", "EM:CN_EXPORTS_YOY", "EM:CN_IMPORTS_YOY", "FRED:XTNTVA01CNM667S", "EEM", "AUDUSD=X", "USDKRW=X"],
    meaning: "Exports/imports and trade-sensitive market proxies show external-demand strength.",
    impact: "Export strength supports manufacturing and FX; weak trade pressures cyclicals and EM risk appetite.",
    sourceNote: "FRED U.S. trade; China monthly exports/imports/balance via Eastmoney (海关总署) with OECD net-trade cross-check via FRED.",
  },
  {
    rank: 18,
    label: "18 财政政策数据",
    symbols: ["FRED:FGEXPND", "FRED:GFDEGDQ188S", "FRED:WTREGEN", "EM:CN_FISCAL_REVENUE"],
    meaning: "Government spending, debt/GDP and Treasury cash balances show fiscal impulse and liquidity withdrawal/injection.",
    impact: "Fiscal expansion supports demand but can lift yields; TGA rising withdraws liquidity, TGA falling releases liquidity.",
    sourceNote: "FRED fiscal and Treasury-account proxies.",
  },
  {
    rank: 19,
    label: "19 行业景气数据",
    symbols: ["^SOX", "SMH", "XLK", "XLE", "XLF", "KRE", "ARKK", "XLE", "^N225", "^KS11"],
    meaning: "Sector and regional proxies reveal where the business cycle is strongest or weakest.",
    impact: "Leadership in semis/tech/cyclicals signals risk appetite; bank or cyclical weakness warns on credit/growth stress.",
    sourceNote: "Yahoo liquid index/ETF proxies; granular industry data need specialized feeds.",
  },
  {
    rank: 20,
    label: "20 政策 / 监管信号",
    symbols: ["KWEB", "^HSI", "^HSCE", "000300.SS", "000001.SS", "399006.SZ", "EEM"],
    meaning: "Policy-sensitive China/HK/EM assets act as liquid proxies for regulatory, property and capital-market policy tone.",
    impact: "Policy easing or regulatory relief lifts these proxies; tightening, property stress or platform regulation hurts them.",
    sourceNote: "Yahoo market proxies; direct policy/news classification is not part of the stable API stack.",
  },
  {
    rank: 21,
    label: "21 人民币 / 跨境资金",
    symbols: [
      "EM:CN_US_10Y_SPREAD",
      "FRED:RBCNBIS",
      "FRED:NBCNBIS",
      "FRED:TRESEGCNM052N",
      "EM:CN_FX_RESERVES",
      "EM:CN_FX_RESERVES_YOY",
      "EM:CN_GOLD_RESERVES",
      "EM:CN_FX_DEPOSITS",
      "EM:CN_FX_LOANS",
      "EM:CN_FDI",
      "EM:CN_FDI_YTD_YOY",
    ],
    meaning:
      "RMB pressure is driven by the U.S.–China rate differential, the trade-weighted (effective) exchange rate, FX reserve changes and how much foreign currency banks/firms are holding onshore rather than converting. Together they show whether appreciation/depreciation pressure is building before the spot rate moves.",
    impact:
      "Narrowing US–CN 10Y spread and rising FX deposits typically precede RMB appreciation; widening spread, falling reserves or rising FX loans warn on depreciation and capital-outflow pressure, which usually hurts A/H equities and helps exporters.",
    sourceNote:
      "BIS effective rates and IMF reserves via FRED (monthly, ~1-2 month lag); PBoC FX reserves, gold, FX deposits/loans and 中债 yields via Eastmoney datacenter. SAFE 结售汇 / 涉外收付款 and CFETS index are still manual — see the gap list.",
  },
]

const PRIORITY_CATEGORY_BY_SYMBOL = new Map<string, MacroPriorityCategory>()
for (const category of MACRO_PRIORITY_CATEGORIES) {
  for (const symbol of category.symbols) {
    if (!PRIORITY_CATEGORY_BY_SYMBOL.has(symbol)) {
      PRIORITY_CATEGORY_BY_SYMBOL.set(symbol, category)
    }
  }
}

const withPriorityCategory = (meta: MacroIndicatorMeta): MacroIndicatorMeta => {
  const category = PRIORITY_CATEGORY_BY_SYMBOL.get(meta.symbol)
  if (!category) return meta

  return {
    ...meta,
    macroRank: category.rank,
    macroCategory: category.label,
    meaning: category.meaning,
    impact: category.impact,
    sourceNote: category.sourceNote,
  }
}

/**
 * Full indicator registry — covers ~85 series across rates / inflation / employment /
 * liquidity / credit / equity / volatility / FX / commodity / growth / real-estate /
 * sentiment / cross-asset.
 *
 * Priority is hand-tuned for the "什么最重要" view used in macro analysis combining
 *股票 / 量化 / 期货 best practices.
 *
 * Indicators marked Yahoo Finance: free, no key.
 * Indicators marked FRED: require FRED_API_KEY env var. They are silently skipped if missing.
 * Indicators marked Eastmoney: free keyless JSON from data.eastmoney.com/cjsj (PBoC / NBS / 海关 / 中债 releases).
 * Indicators marked NBS/PBoC/BIS Snapshot: versioned JSON in lib/data, refreshed by script, never fail at runtime.
 */
const BASE_MACRO_INDICATORS: MacroIndicatorMeta[] = [
  // ============================================================
  // TIER 1 — Critical daily watch (1-15)
  // ============================================================
  {
    symbol: "FRED:DFF",
    providerSymbol: "DFF",
    source: "FRED",
    name: "Fed Funds Effective Rate",
    group: "Rates",
    unit: "percent",
    priority: 1,
    frequency: "Daily",
    audience: ["宏观", "股票", "期货"],
    description:
      "美联储有效联邦基金利率，全球无风险利率的锚。\n直接决定贴现率，对美股估值、黄金和美元定价影响最大。\n上行：紧缩；下行：放水。",
  },
  {
    symbol: "FRED:DGS10",
    providerSymbol: "DGS10",
    source: "FRED",
    name: "U.S. 10Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 2,
    frequency: "Daily",
    audience: ["宏观", "股票"],
    description:
      "美国 10 年期国债收益率，全球资产定价的核心折现率。\n上行通常压制成长股，支撑美元；下行反之。",
  },
  {
    symbol: "FRED:DGS2",
    providerSymbol: "DGS2",
    source: "FRED",
    name: "U.S. 2Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 3,
    frequency: "Daily",
    audience: ["宏观", "债券"],
    description: "2 年期国债收益率，对市场加息/降息预期最敏感的端点，常用于看 Fed 路径定价。",
  },
  {
    symbol: "FRED:DFII10",
    providerSymbol: "DFII10",
    source: "FRED",
    name: "10Y TIPS Real Yield",
    group: "Rates",
    unit: "percent",
    priority: 4,
    frequency: "Daily",
    audience: ["宏观", "黄金"],
    description: "通胀挂钩国债（TIPS）10 年期实际利率。\n实际利率上行 = 非生息资产（黄金）压制；下行 = 利好。",
  },
  {
    symbol: "DX-Y.NYB",
    source: "Yahoo Finance",
    name: "U.S. Dollar Index (DXY)",
    group: "FX",
    unit: "index",
    priority: 5,
    frequency: "Realtime",
    audience: ["宏观", "FX"],
    description: "美元对一篮子主要货币的加权指数。美元走强通常压制黄金、新兴市场和大宗商品。",
  },
  {
    symbol: "^IXIC",
    source: "Yahoo Finance",
    name: "Nasdaq Composite",
    group: "Equity",
    unit: "index",
    priority: 6,
    frequency: "Realtime",
    audience: ["股票"],
    description: "纳斯达克综合指数，科技股权重最大，是高 Beta 风险偏好的核心代理。",
  },
  {
    symbol: "^NDX",
    source: "Yahoo Finance",
    name: "Nasdaq 100",
    group: "Equity",
    unit: "index",
    priority: 7,
    frequency: "Realtime",
    audience: ["股票"],
    description: "纳斯达克 100，100 只非金融大型成长公司的市值加权指数。",
  },
  {
    symbol: "QQQ",
    source: "Yahoo Finance",
    name: "Invesco QQQ Trust (QQQ)",
    group: "Equity",
    unit: "usd",
    priority: 7.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "科技"],
    description: "Nasdaq 100 可交易 ETF。量化交易中常用于替代 NDX 现货指数，流动性高、期权链活跃。",
  },
  {
    symbol: "^GSPC",
    source: "Yahoo Finance",
    name: "S&P 500",
    group: "Equity",
    unit: "index",
    priority: 8,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "美股 500 大蓝筹综合，全球风险偏好基准。",
  },
  {
    symbol: "SPY",
    source: "Yahoo Finance",
    name: "SPDR S&P 500 ETF (SPY)",
    group: "Equity",
    unit: "usd",
    priority: 8.1,
    frequency: "Realtime",
    audience: ["股票", "量化"],
    description: "S&P 500 可交易 ETF。用于观察真实成交、期权、机构对冲和盘中风险偏好。",
  },
  {
    symbol: "^FTW5000",
    source: "Yahoo Finance",
    name: "FT Wilshire 5000 Total Market",
    group: "Equity",
    unit: "index",
    priority: 8.2,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description:
      "FT Wilshire 5000 全市场指数，美股总市值表现的宽基代理。比 S&P 500 更接近美国上市股票整体市值周期。",
  },
  {
    symbol: "^VIX",
    source: "Yahoo Finance",
    name: "CBOE VIX",
    group: "Volatility",
    unit: "index",
    priority: 9,
    frequency: "Realtime",
    audience: ["宏观", "股票"],
    description: "S&P 500 隐含波动率（恐慌指数）。\n>30 高度恐慌；20-30 警戒；<15 极度乐观。",
  },
  {
    symbol: "FRED:CPIAUCSL",
    providerSymbol: "CPIAUCSL",
    source: "FRED",
    name: "U.S. CPI (Headline)",
    group: "Inflation",
    unit: "index",
    priority: 10,
    frequency: "Monthly",
    audience: ["宏观", "债券"],
    description: "美国 CPI 总体指数（季调）。每月公布，是市场对 Fed 政策路径定价的核心变量之一。",
  },
  {
    symbol: "FRED:CPILFESL",
    providerSymbol: "CPILFESL",
    source: "FRED",
    name: "U.S. Core CPI (ex Food & Energy)",
    group: "Inflation",
    unit: "index",
    priority: 11,
    frequency: "Monthly",
    audience: ["宏观", "债券"],
    description: "美国核心 CPI（剔除食品和能源）。Fed 决策更看重，黏性强意味着降息预期推迟。",
  },
  {
    symbol: "FRED:PCEPI",
    providerSymbol: "PCEPI",
    source: "FRED",
    name: "U.S. PCE Price Index",
    group: "Inflation",
    unit: "index",
    priority: 12,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国个人消费支出物价指数。Fed 设定 2% 通胀目标的官方度量。",
  },
  {
    symbol: "FRED:PCEPILFE",
    providerSymbol: "PCEPILFE",
    source: "FRED",
    name: "U.S. Core PCE",
    group: "Inflation",
    unit: "index",
    priority: 13,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "核心 PCE（剔除食品和能源），Fed 最偏好的通胀指标。",
  },
  {
    symbol: "FRED:UNRATE",
    providerSymbol: "UNRATE",
    source: "FRED",
    name: "U.S. Unemployment Rate",
    group: "Employment",
    unit: "percent",
    priority: 14,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国失业率。上行 0.5% 以上常对应 Sahm Rule 衰退信号，催化降息预期。",
  },
  {
    symbol: "FRED:PAYEMS",
    providerSymbol: "PAYEMS",
    source: "FRED",
    name: "Nonfarm Payrolls (Level)",
    group: "Employment",
    unit: "count",
    priority: 15,
    frequency: "Monthly",
    audience: ["宏观", "股票"],
    description: "非农就业总人数水平（千人）。月差即为新增 NFP，市场最关注的就业指标。",
  },

  // ============================================================
  // TIER 2 — Liquidity & Credit (16-30)
  // ============================================================
  {
    symbol: "FRED:WALCL",
    providerSymbol: "WALCL",
    source: "FRED",
    name: "Fed Balance Sheet",
    group: "Liquidity",
    unit: "usd",
    priority: 16,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "联储总资产规模（百万美元）。QE 扩张时增长，QT 时收缩。直接驱动全球美元流动性。",
    transform: (value) => value * 1_000_000, // FRED reports in millions
  },
  {
    symbol: "FRED:TOTRESNS",
    providerSymbol: "TOTRESNS",
    source: "FRED",
    name: "Bank Reserves (Total)",
    group: "Liquidity",
    unit: "usd",
    priority: 17,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国存款机构在联储的准备金总额（百万美元）。金融体系流动性核心指标。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:RRPONTSYD",
    providerSymbol: "RRPONTSYD",
    source: "FRED",
    name: "Overnight Reverse Repo",
    group: "Liquidity",
    unit: "usd",
    priority: 18,
    frequency: "Daily",
    audience: ["宏观"],
    description: "纽约联储隔夜逆回购余额。RRP 下降 = 货币市场基金释放美元到银行体系（放水）。",
    transform: (value) => value * 1_000_000_000, // FRED reports in billions
  },
  {
    symbol: "FRED:WTREGEN",
    providerSymbol: "WTREGEN",
    source: "FRED",
    name: "Treasury General Account (TGA)",
    group: "Liquidity",
    unit: "usd",
    priority: 19,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "美国财政部在联储的现金账户余额（百万美元）。TGA 上升 = 财政部抽水；下降 = 放水。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:M2SL",
    providerSymbol: "M2SL",
    source: "FRED",
    name: "U.S. M2 Money Supply",
    group: "Liquidity",
    unit: "usd",
    priority: 20,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "美国 M2 货币供应（十亿美元）。宽货币周期对风险资产中长期支撑。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:M1SL",
    providerSymbol: "M1SL",
    source: "FRED",
    name: "U.S. M1 Money Supply",
    group: "Liquidity",
    unit: "usd",
    priority: 21,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "M1 短端货币（活期 + 现金），反映短期流动性。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:TOTLL",
    providerSymbol: "TOTLL",
    source: "FRED",
    name: "U.S. Loans & Leases",
    group: "Credit",
    unit: "usd",
    priority: 21.05,
    frequency: "Weekly",
    audience: ["宏观", "信用"],
    description: "美国商业银行贷款和租赁总额（十亿美元）。比 M2 更接近实体信用扩张。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:M2REAL",
    providerSymbol: "M2REAL",
    source: "FRED",
    name: "U.S. Real M2 Money Supply",
    group: "Liquidity",
    unit: "usd",
    priority: 21.1,
    frequency: "Monthly",
    audience: ["宏观"],
    description:
      "美国实际 M2（以 CPI 折算为 1982-84 年美元）。用于区分名义货币扩张和真实购买力扩张；实际 M2 上行通常代表真实流动性改善。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:M2V",
    providerSymbol: "M2V",
    source: "FRED",
    name: "U.S. M2 Velocity",
    group: "Liquidity",
    unit: "ratio",
    priority: 21.2,
    frequency: "Quarterly",
    audience: ["宏观"],
    description:
      "M2 流通速度（名义 GDP / M2）。上行代表货币周转加快，常与名义增长、通胀和信贷活跃度改善相关；下行说明货币更多停留在储蓄/金融体系。",
  },
  {
    symbol: "FRED:BOGMBASE",
    providerSymbol: "BOGMBASE",
    source: "FRED",
    name: "U.S. Monetary Base",
    group: "Liquidity",
    unit: "usd",
    priority: 21.3,
    frequency: "Monthly",
    audience: ["宏观"],
    description:
      "美国货币基础（流通中现金 + 准备金余额，十亿美元）。与联储资产负债表、银行准备金共同观察基础流动性。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:MYAGM2CNM189N",
    providerSymbol: "MYAGM2CNM189N",
    source: "FRED",
    name: "China M2 Money Supply (Historical)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.4,
    frequency: "Monthly · historical to 2019",
    audience: ["宏观", "中国"],
    description:
      "中国 M2 货币供应，IMF IFS 经 FRED 发布，单位为人民币。稳定 API 覆盖到 2019 年 8 月，作为历史周期参考；不是当前 PBoC 最新月度值。",
  },
  {
    symbol: "FRED:MYAGM1CNM189N",
    providerSymbol: "MYAGM1CNM189N",
    source: "FRED",
    name: "China M1 Money Supply (Historical)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.5,
    frequency: "Monthly · historical to 2019",
    audience: ["宏观", "中国"],
    description:
      "中国 M1 货币供应，IMF IFS 经 FRED 发布，单位为人民币。稳定 API 覆盖到 2019 年 8 月，适合看历史流动性结构，不代表最新 PBoC 数据。",
  },
  {
    symbol: "FRED:BAMLH0A0HYM2",
    providerSymbol: "BAMLH0A0HYM2",
    source: "FRED",
    name: "U.S. HY Credit Spread (OAS)",
    group: "Credit",
    unit: "percent",
    priority: 22,
    frequency: "Daily",
    audience: ["宏观", "信用"],
    description:
      "ICE BofA 美国高收益债期权调整利差（OAS）。\n上行 = 信用风险走差，常领先股市下跌；< 3% 风险偏好高。",
  },
  {
    symbol: "FRED:BAMLC0A0CM",
    providerSymbol: "BAMLC0A0CM",
    source: "FRED",
    name: "U.S. IG Credit Spread (OAS)",
    group: "Credit",
    unit: "percent",
    priority: 23,
    frequency: "Daily",
    audience: ["信用", "债券"],
    description: "投资级公司债 OAS。优质信用市场的紧张程度。",
  },
  {
    symbol: "FRED:T10Y2Y",
    providerSymbol: "T10Y2Y",
    source: "FRED",
    name: "10Y-2Y Treasury Spread",
    group: "Rates",
    unit: "percent",
    priority: 24,
    frequency: "Daily",
    audience: ["宏观"],
    description: "10Y 减 2Y 利差。倒挂（<0）历史上是经典的衰退领先指标，平均提前 12-18 个月。",
  },
  {
    symbol: "FRED:T10Y3M",
    providerSymbol: "T10Y3M",
    source: "FRED",
    name: "10Y-3M Treasury Spread",
    group: "Rates",
    unit: "percent",
    priority: 25,
    frequency: "Daily",
    audience: ["宏观"],
    description: "10Y 减 3M 利差。NY Fed 衰退概率模型核心输入。",
  },
  {
    symbol: "FRED:DGS3MO",
    providerSymbol: "DGS3MO",
    source: "FRED",
    name: "U.S. 3M Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 26,
    frequency: "Daily",
    audience: ["宏观"],
    description: "3 个月国库券收益率，最贴近政策利率的市场报价。",
  },
  {
    symbol: "FRED:DGS5",
    providerSymbol: "DGS5",
    source: "FRED",
    name: "U.S. 5Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 27,
    frequency: "Daily",
    audience: ["宏观"],
    description: "5 年期国债收益率。反映 5 年内通胀、增长预期和金融条件中点。",
  },
  {
    symbol: "FRED:DGS30",
    providerSymbol: "DGS30",
    source: "FRED",
    name: "U.S. 30Y Treasury Yield",
    group: "Rates",
    unit: "percent",
    priority: 28,
    frequency: "Daily",
    audience: ["宏观"],
    description: "30 年期长债收益率，反映长期通胀和期限溢价。",
  },

  // ============================================================
  // TIER 3 — Equity indices + sectors (29-50)
  // ============================================================
  {
    symbol: "^DJI",
    source: "Yahoo Finance",
    name: "Dow Jones Industrial Average",
    group: "Equity",
    unit: "index",
    priority: 29,
    frequency: "Realtime",
    audience: ["股票"],
    description: "道琼斯工业 30 指数，偏价值/周期股。",
  },
  {
    symbol: "^RUT",
    source: "Yahoo Finance",
    name: "Russell 2000 (Small Caps)",
    group: "Equity",
    unit: "index",
    priority: 30,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "美国小盘股指数，对本土经济、信贷、利率最敏感。",
  },
  {
    symbol: "IWM",
    source: "Yahoo Finance",
    name: "iShares Russell 2000 ETF (IWM)",
    group: "Equity",
    unit: "usd",
    priority: 30.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "小盘"],
    description: "Russell 2000 可交易 ETF。小盘股 Beta、融资条件和风险偏好的盘中代理。",
  },
  {
    symbol: "^SOX",
    source: "Yahoo Finance",
    name: "PHLX Semiconductor (SOX)",
    group: "Equity",
    unit: "index",
    priority: 31,
    frequency: "Realtime",
    audience: ["股票", "科技"],
    description: "费城半导体指数，AI / 科技风险偏好的核心代理，领先纳指。",
  },
  {
    symbol: "SMH",
    source: "Yahoo Finance",
    name: "VanEck Semiconductor ETF (SMH)",
    group: "Equity",
    unit: "usd",
    priority: 31.1,
    frequency: "Realtime",
    audience: ["股票", "量化", "半导体"],
    description: "半导体 ETF，NVDA / TSM / AVGO 权重高，是 AI 和全球科技资本开支的高流动性代理。",
  },
  {
    symbol: "XLK",
    source: "Yahoo Finance",
    name: "Technology Select Sector SPDR (XLK)",
    group: "Equity",
    unit: "usd",
    priority: 31.2,
    frequency: "Realtime",
    audience: ["股票", "量化", "科技"],
    description: "美股科技板块 ETF。用于分离指数上涨中科技权重的贡献。",
  },
  {
    symbol: "XLF",
    source: "Yahoo Finance",
    name: "Financial Select Sector SPDR (XLF)",
    group: "Equity",
    unit: "usd",
    priority: 31.3,
    frequency: "Realtime",
    audience: ["股票", "量化", "金融"],
    description: "美股金融板块 ETF。对收益率曲线、信用利差和银行风险敏感。",
  },
  {
    symbol: "KRE",
    source: "Yahoo Finance",
    name: "SPDR S&P Regional Banking ETF (KRE)",
    group: "Equity",
    unit: "usd",
    priority: 31.4,
    frequency: "Realtime",
    audience: ["股票", "量化", "银行"],
    description: "美国区域银行 ETF。金融压力、存款外流和信用收缩的高敏感代理。",
  },
  {
    symbol: "XLE",
    source: "Yahoo Finance",
    name: "Energy Select Sector SPDR (XLE)",
    group: "Equity",
    unit: "usd",
    priority: 31.5,
    frequency: "Realtime",
    audience: ["股票", "量化", "能源"],
    description: "美股能源板块 ETF。与油价、通胀和周期股轮动高度相关。",
  },
  {
    symbol: "ARKK",
    source: "Yahoo Finance",
    name: "ARK Innovation ETF (ARKK)",
    group: "Equity",
    unit: "usd",
    priority: 32,
    frequency: "Realtime",
    audience: ["股票"],
    description: "高 Beta 创新 / 成长股 ETF，是流动性边际和风险偏好的高敏感代理。",
  },
  {
    symbol: "KWEB",
    source: "Yahoo Finance",
    name: "KraneShares CSI China Internet (KWEB)",
    group: "Equity",
    unit: "usd",
    priority: 33,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "中国互联网中概股 ETF，反映海外资金对中国资产的态度。",
  },
  {
    symbol: "EEM",
    source: "Yahoo Finance",
    name: "MSCI Emerging Markets ETF (EEM)",
    group: "Equity",
    unit: "usd",
    priority: 34,
    frequency: "Realtime",
    audience: ["股票", "宏观"],
    description: "新兴市场 ETF，对美元/美债收益率敏感，是全球风险偏好的镜像。",
  },
  {
    symbol: "ACWI",
    source: "Yahoo Finance",
    name: "MSCI All Country World ETF",
    group: "Equity",
    unit: "usd",
    priority: 35,
    frequency: "Realtime",
    audience: ["股票"],
    description: "MSCI 全球股票市场 ETF。全球风险偏好综合代理。",
  },
  {
    symbol: "FRED:DDDM01USA156NWDB",
    providerSymbol: "DDDM01USA156NWDB",
    source: "FRED",
    name: "U.S. Stock Market Cap / GDP",
    group: "Equity",
    unit: "percent",
    priority: 35.1,
    frequency: "Annual · lagged",
    audience: ["宏观", "股票"],
    description:
      "美国上市股票总市值 / GDP（World Bank，经 FRED 发布）。常被称为 Buffett Indicator，用于观察股票整体估值与实体经济规模的关系；年度数据有明显滞后。",
  },
  {
    symbol: "FRED:DDDM01CNA156NWDB",
    providerSymbol: "DDDM01CNA156NWDB",
    source: "FRED",
    name: "China Stock Market Cap / GDP",
    group: "Equity",
    unit: "percent",
    priority: 35.2,
    frequency: "Annual · lagged",
    audience: ["宏观", "中国", "股票"],
    description:
      "中国上市股票总市值 / GDP（World Bank，经 FRED 发布）。用于观察 A/H 股市场规模相对实体经济的变化；年度数据有明显滞后。",
  },
  {
    symbol: "FRED:DDDM02USA156NWDB",
    providerSymbol: "DDDM02USA156NWDB",
    source: "FRED",
    name: "U.S. Stock Value Traded / GDP",
    group: "Equity",
    unit: "percent",
    priority: 35.3,
    frequency: "Annual · lagged",
    audience: ["宏观", "股票", "量化"],
    description:
      "美国股票成交总额 / GDP（World Bank，经 FRED 发布）。衡量市场换手与金融市场活跃度，年度数据有明显滞后。",
  },
  {
    symbol: "FRED:DDDM02CNA156NWDB",
    providerSymbol: "DDDM02CNA156NWDB",
    source: "FRED",
    name: "China Stock Value Traded / GDP",
    group: "Equity",
    unit: "percent",
    priority: 35.4,
    frequency: "Annual · lagged",
    audience: ["宏观", "中国", "股票"],
    description:
      "中国股票成交总额 / GDP（World Bank，经 FRED 发布）。用于观察市场交易活跃度与实体经济规模的关系，年度数据有明显滞后。",
  },
  {
    symbol: "^HSI",
    source: "Yahoo Finance",
    name: "Hang Seng Index",
    group: "Equity",
    unit: "index",
    priority: 36,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "香港恒生指数，反映港股、中资科技/金融。",
  },
  {
    symbol: "^HSCE",
    source: "Yahoo Finance",
    name: "Hang Seng China Enterprises (H-Shares)",
    group: "Equity",
    unit: "index",
    priority: 37,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "国企指数，港股中资金融/能源大型公司加权。",
  },
  {
    symbol: "000300.SS",
    source: "Yahoo Finance",
    name: "CSI 300 (沪深 300)",
    group: "Equity",
    unit: "index",
    priority: 38,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "沪深 300 指数，A 股核心宽基。",
  },
  {
    symbol: "000001.SS",
    source: "Yahoo Finance",
    name: "Shanghai Composite (上证)",
    group: "Equity",
    unit: "index",
    priority: 39,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "上证综合指数，A 股大盘风险偏好基准。",
  },
  {
    symbol: "399006.SZ",
    source: "Yahoo Finance",
    name: "ChiNext (创业板指)",
    group: "Equity",
    unit: "index",
    priority: 40,
    frequency: "Realtime",
    audience: ["股票", "中国"],
    description: "创业板指数，A 股成长股代表，对利率和风险偏好敏感。",
  },
  {
    symbol: "^N225",
    source: "Yahoo Finance",
    name: "Nikkei 225",
    group: "Equity",
    unit: "index",
    priority: 41,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "日经 225，与 USDJPY 同向：日元贬值常拉升日股。",
  },
  {
    symbol: "^GDAXI",
    source: "Yahoo Finance",
    name: "DAX 40",
    group: "Equity",
    unit: "index",
    priority: 42,
    frequency: "Realtime",
    audience: ["股票", "欧洲"],
    description: "德国 DAX 40，欧元区核心制造业风向标。",
  },
  {
    symbol: "^FTSE",
    source: "Yahoo Finance",
    name: "FTSE 100",
    group: "Equity",
    unit: "index",
    priority: 43,
    frequency: "Realtime",
    audience: ["股票", "欧洲"],
    description: "英国富时 100，能源/金融权重高。",
  },
  {
    symbol: "^KS11",
    source: "Yahoo Finance",
    name: "KOSPI",
    group: "Equity",
    unit: "index",
    priority: 44,
    frequency: "Realtime",
    audience: ["股票", "亚太"],
    description: "韩国综合指数，半导体出口的全球科技周期领先指标。",
  },

  // Volatility (sub-tier 45-50)
  {
    symbol: "^VXN",
    source: "Yahoo Finance",
    name: "Nasdaq 100 Volatility (VXN)",
    group: "Volatility",
    unit: "index",
    priority: 45,
    frequency: "Realtime",
    audience: ["波动率", "科技"],
    description: "纳指 100 隐含波动率，对科技股风险更敏感。",
  },
  {
    symbol: "^VVIX",
    source: "Yahoo Finance",
    name: "VVIX (Vol of Vol)",
    group: "Volatility",
    unit: "index",
    priority: 46,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "VIX 自身的波动率。突发事件风险溢价的二阶指标。",
  },
  {
    symbol: "^SKEW",
    source: "Yahoo Finance",
    name: "CBOE SKEW Index",
    group: "Volatility",
    unit: "index",
    priority: 47,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "S&P 500 期权左尾偏度。值越高，市场对“黑天鹅”的定价越贵。",
  },
  {
    symbol: "^OVX",
    source: "Yahoo Finance",
    name: "Crude Oil VIX",
    group: "Volatility",
    unit: "index",
    priority: 48,
    frequency: "Realtime",
    audience: ["波动率", "商品"],
    description: "WTI 原油隐含波动率，能源风险定价。",
  },
  {
    symbol: "^GVZ",
    source: "Yahoo Finance",
    name: "Gold VIX",
    group: "Volatility",
    unit: "index",
    priority: 49,
    frequency: "Realtime",
    audience: ["波动率"],
    description: "黄金隐含波动率，避险/通胀情绪的二阶代理。",
  },

  // ============================================================
  // TIER 4 — Employment / Growth / Real Estate (51-75)
  // ============================================================
  {
    symbol: "FRED:ICSA",
    providerSymbol: "ICSA",
    source: "FRED",
    name: "Initial Jobless Claims",
    group: "Employment",
    unit: "count",
    priority: 51,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "每周首次申请失业救济人数。劳动力市场最高频拐点指标。",
  },
  {
    symbol: "FRED:CCSA",
    providerSymbol: "CCSA",
    source: "FRED",
    name: "Continuing Jobless Claims",
    group: "Employment",
    unit: "count",
    priority: 52,
    frequency: "Weekly",
    audience: ["宏观"],
    description: "持续申请失业救济总人数，反映再就业速度。",
  },
  {
    symbol: "FRED:JTSJOL",
    providerSymbol: "JTSJOL",
    source: "FRED",
    name: "JOLTS Job Openings",
    group: "Employment",
    unit: "count",
    priority: 53,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "JOLTS 职位空缺数（千个）。劳动力需求强弱的核心指标。",
    transform: (value) => value * 1000,
  },
  {
    symbol: "FRED:CES0500000003",
    providerSymbol: "CES0500000003",
    source: "FRED",
    name: "Avg Hourly Earnings (Private)",
    group: "Employment",
    unit: "usd",
    priority: 54,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "私营部门平均时薪（美元/小时）。工资通胀的核心来源。",
  },
  {
    symbol: "FRED:UMCSENT",
    providerSymbol: "UMCSENT",
    source: "FRED",
    name: "U. of Michigan Consumer Sentiment",
    group: "Sentiment",
    unit: "index",
    priority: 55,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "密歇根大学消费者信心指数。消费支出和零售前景的领先指标。",
  },
  {
    symbol: "FRED:MICH",
    providerSymbol: "MICH",
    source: "FRED",
    name: "UMich 1Y Inflation Expectations",
    group: "Inflation",
    unit: "percent",
    priority: 56,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "密歇根大学 1 年通胀预期。Fed 对「通胀预期是否锚定」的关键参考。",
  },
  {
    symbol: "FRED:T5YIE",
    providerSymbol: "T5YIE",
    source: "FRED",
    name: "5Y Breakeven Inflation Rate",
    group: "Inflation",
    unit: "percent",
    priority: 56.5,
    frequency: "Daily",
    audience: ["宏观", "债券"],
    description: "5 年期隐含通胀预期（名义国债 - TIPS 实际利率）。\n上升 = 市场预期通胀走高；下降 = 通胀预期回落。",
  },
  {
    symbol: "FRED:T10YIE",
    providerSymbol: "T10YIE",
    source: "FRED",
    name: "10Y Breakeven Inflation Rate",
    group: "Inflation",
    unit: "percent",
    priority: 56.6,
    frequency: "Daily",
    audience: ["宏观", "债券"],
    description: "10 年期隐含通胀预期。市场对中长期通胀的定价，影响实际利率和资产估值。",
  },
  {
    symbol: "FRED:PPIACO",
    providerSymbol: "PPIACO",
    source: "FRED",
    name: "Producer Price Index (PPI)",
    group: "Inflation",
    unit: "index",
    priority: 57,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "生产者价格指数（所有商品）。企业成本端，CPI / PCE 的领先信号。",
  },
  {
    symbol: "FRED:RSAFS",
    providerSymbol: "RSAFS",
    source: "FRED",
    name: "U.S. Retail Sales",
    group: "Growth",
    unit: "usd",
    priority: 58,
    frequency: "Monthly",
    audience: ["宏观", "消费"],
    description: "美国零售销售（百万美元，季调）。消费韧性的核心月度数据。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:DSPIC96",
    providerSymbol: "DSPIC96",
    source: "FRED",
    name: "Real Disposable Personal Income",
    group: "Growth",
    unit: "usd",
    priority: 58.2,
    frequency: "Monthly",
    audience: ["宏观", "消费"],
    description: "美国实际可支配个人收入（十亿 2017 链式美元，年化）。居民消费能力的收入端。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:INDPRO",
    providerSymbol: "INDPRO",
    source: "FRED",
    name: "Industrial Production Index",
    group: "Growth",
    unit: "index",
    priority: 59,
    frequency: "Monthly",
    audience: ["宏观", "商品"],
    description: "美国工业生产指数。实体制造业景气度。",
  },
  {
    symbol: "FRED:TCU",
    providerSymbol: "TCU",
    source: "FRED",
    name: "Capacity Utilization (Total)",
    group: "Growth",
    unit: "percent",
    priority: 60,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "总产能利用率（%）。供需紧张程度，影响成本和通胀压力。",
  },
  {
    symbol: "FRED:DGORDER",
    providerSymbol: "DGORDER",
    source: "FRED",
    name: "Durable Goods Orders",
    group: "Growth",
    unit: "usd",
    priority: 61,
    frequency: "Monthly",
    audience: ["宏观"],
    description: "耐用品订单（百万美元）。企业资本开支前瞻。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "FRED:IPMAN",
    providerSymbol: "IPMAN",
    source: "FRED",
    name: "Manufacturing Activity Proxy (IPMAN)",
    group: "Growth",
    unit: "index",
    priority: 61.5,
    frequency: "Monthly",
    audience: ["宏观", "制造业"],
    description:
      "美国制造业工业生产指数（NAICS）。FRED 不再稳定提供 ISM PMI，本序列作为制造业景气的硬数据 proxy。",
  },
  {
    symbol: "FRED:GDPC1",
    providerSymbol: "GDPC1",
    source: "FRED",
    name: "U.S. Real GDP",
    group: "Growth",
    unit: "usd",
    priority: 61.8,
    frequency: "Quarterly",
    audience: ["宏观"],
    description: "美国实际 GDP（十亿 2017 链式美元，季度年化）。剔除通胀后的经济总量。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:GDP",
    providerSymbol: "GDP",
    source: "FRED",
    name: "U.S. Nominal GDP (Quarterly)",
    group: "Growth",
    unit: "usd",
    priority: 62,
    frequency: "Quarterly",
    audience: ["宏观"],
    description: "美国名义 GDP（十亿美元，季度）。经济总量周期。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:GPDI",
    providerSymbol: "GPDI",
    source: "FRED",
    name: "Gross Private Domestic Investment",
    group: "Growth",
    unit: "usd",
    priority: 62.1,
    frequency: "Quarterly",
    audience: ["宏观", "投资"],
    description: "美国私人国内总投资（十亿美元，季度年化）。衡量资本开支和库存周期的总投资 proxy。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:PNFI",
    providerSymbol: "PNFI",
    source: "FRED",
    name: "Private Nonresidential Fixed Investment",
    group: "Growth",
    unit: "usd",
    priority: 62.2,
    frequency: "Quarterly",
    audience: ["宏观", "投资"],
    description: "美国私人非住宅固定投资（十亿美元，季度年化）。企业资本开支和制造业投资强弱。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:GDPNOW",
    providerSymbol: "GDPNOW",
    source: "FRED",
    name: "Atlanta Fed GDPNow",
    group: "Growth",
    unit: "percent",
    priority: 62.5,
    frequency: "Weekly",
    audience: ["宏观", "股票"],
    description: "亚特兰大联储 GDPNow 实时 GDP 预测（季度环比年化）。\n高频跟踪当季 GDP 增速预期变化，领先官方数据发布。",
  },
  {
    symbol: "FRED:NFCI",
    providerSymbol: "NFCI",
    source: "FRED",
    name: "Chicago Fed NFCI",
    group: "Credit",
    unit: "index",
    priority: 22.5,
    frequency: "Weekly",
    audience: ["宏观", "信用"],
    description: "芝加哥联储国家金融条件指数。\n负值 = 金融条件宽松；正值 = 金融条件紧张。\n> 0 通常压制风险资产。",
  },
  {
    symbol: "FRED:MORTGAGE30US",
    providerSymbol: "MORTGAGE30US",
    source: "FRED",
    name: "30Y Fixed Mortgage Rate",
    group: "RealEstate",
    unit: "percent",
    priority: 63,
    frequency: "Weekly",
    audience: ["地产"],
    description: "美国 30 年固定房贷利率（Freddie Mac）。居民部门利率压力的核心指标。",
  },
  {
    symbol: "FRED:HSN1F",
    providerSymbol: "HSN1F",
    source: "FRED",
    name: "New Home Sales",
    group: "RealEstate",
    unit: "count",
    priority: 64,
    frequency: "Monthly",
    audience: ["地产"],
    description: "美国新屋销售年化率（千套）。利率敏感的需求端。",
    transform: (value) => value * 1000,
  },
  {
    symbol: "FRED:PERMIT",
    providerSymbol: "PERMIT",
    source: "FRED",
    name: "Building Permits",
    group: "RealEstate",
    unit: "count",
    priority: 65,
    frequency: "Monthly",
    audience: ["地产"],
    description: "美国营建许可（千套，年化）。住宅建设的领先指标。",
    transform: (value) => value * 1000,
  },
  {
    symbol: "FRED:PRFI",
    providerSymbol: "PRFI",
    source: "FRED",
    name: "Private Residential Fixed Investment",
    group: "RealEstate",
    unit: "usd",
    priority: 65.5,
    frequency: "Quarterly",
    audience: ["地产", "宏观"],
    description: "美国私人住宅固定投资（十亿美元，季度年化）。比房价更贴近地产投资对 GDP 的拖累/支撑。",
    transform: (value) => value * 1_000_000_000,
  },

  // ============================================================
  // TIER 5 — FX (66-75)
  // ============================================================
  {
    symbol: "EURUSD=X",
    source: "Yahoo Finance",
    name: "EUR/USD",
    group: "FX",
    unit: "ratio",
    priority: 66,
    frequency: "Realtime",
    audience: ["FX", "宏观"],
    description: "全球交易量最大的货币对，DXY 主成分。",
  },
  {
    symbol: "USDJPY=X",
    source: "Yahoo Finance",
    name: "USD/JPY",
    group: "FX",
    unit: "ratio",
    priority: 67,
    frequency: "Realtime",
    audience: ["FX", "套息交易"],
    description: "美日汇率。套息交易核心，与美债收益率高度相关。",
  },
  {
    symbol: "USDCNH=X",
    source: "Yahoo Finance",
    name: "USD/CNH (离岸人民币)",
    group: "FX",
    unit: "ratio",
    priority: 68,
    frequency: "Realtime",
    audience: ["FX", "中国"],
    description: "美元兑离岸人民币。中美利差 + 人民币市场化预期。",
  },
  {
    symbol: "CNY=X",
    source: "Yahoo Finance",
    name: "USD/CNY (在岸人民币)",
    group: "FX",
    unit: "ratio",
    priority: 68.1,
    frequency: "Realtime",
    audience: ["FX", "中国"],
    description: "美元兑在岸人民币。与 USDCNH 联合观察人民币压力和内外盘价差。",
  },
  {
    symbol: "GBPUSD=X",
    source: "Yahoo Finance",
    name: "GBP/USD",
    group: "FX",
    unit: "ratio",
    priority: 69,
    frequency: "Realtime",
    audience: ["FX"],
    description: "英镑兑美元，与英国利率/政治情绪密切相关。",
  },
  {
    symbol: "AUDUSD=X",
    source: "Yahoo Finance",
    name: "AUD/USD",
    group: "FX",
    unit: "ratio",
    priority: 70,
    frequency: "Realtime",
    audience: ["FX", "商品"],
    description: "澳元兑美元，大宗商品代理货币，与中国经济相关。",
  },
  {
    symbol: "USDKRW=X",
    source: "Yahoo Finance",
    name: "USD/KRW",
    group: "FX",
    unit: "ratio",
    priority: 71,
    frequency: "Realtime",
    audience: ["FX", "亚太"],
    description: "美韩汇率，亚洲风险偏好和半导体周期的领先信号之一。",
  },

  // ============================================================
  // TIER 6 — Commodities (72-90)
  // ============================================================
  {
    symbol: "GC=F",
    source: "Yahoo Finance",
    name: "Gold Futures",
    group: "Commodity",
    unit: "usd",
    priority: 72,
    frequency: "Realtime",
    audience: ["商品", "避险"],
    description: "COMEX 黄金期货。避险、抗通胀、与实际利率反向。",
  },
  {
    symbol: "CL=F",
    source: "Yahoo Finance",
    name: "WTI Crude Oil",
    group: "Commodity",
    unit: "usd",
    priority: 73,
    frequency: "Realtime",
    audience: ["商品", "通胀"],
    description: "WTI 原油期货，美国基准油价；通胀核心驱动。",
  },
  {
    symbol: "BZ=F",
    source: "Yahoo Finance",
    name: "Brent Crude Oil",
    group: "Commodity",
    unit: "usd",
    priority: 74,
    frequency: "Realtime",
    audience: ["商品"],
    description: "布伦特原油，欧亚基准油价。",
  },
  {
    symbol: "SI=F",
    source: "Yahoo Finance",
    name: "Silver Futures",
    group: "Commodity",
    unit: "usd",
    priority: 75,
    frequency: "Realtime",
    audience: ["商品"],
    description: "COMEX 白银期货，弹性比黄金大，含工业属性。",
  },
  {
    symbol: "HG=F",
    source: "Yahoo Finance",
    name: "Copper (Dr. Copper)",
    group: "Commodity",
    unit: "usd",
    priority: 76,
    frequency: "Realtime",
    audience: ["商品", "宏观"],
    description: "铜期货，全球工业景气和中国需求的领先指标。",
  },
  {
    symbol: "NG=F",
    source: "Yahoo Finance",
    name: "Natural Gas",
    group: "Commodity",
    unit: "usd",
    priority: 77,
    frequency: "Realtime",
    audience: ["商品"],
    description: "亨利港天然气期货，季节性极强。",
  },
  {
    symbol: "PL=F",
    source: "Yahoo Finance",
    name: "Platinum Futures",
    group: "Commodity",
    unit: "usd",
    priority: 78,
    frequency: "Realtime",
    audience: ["商品"],
    description: "铂金期货，工业 + 贵金属属性兼具。",
  },
  {
    symbol: "ZC=F",
    source: "Yahoo Finance",
    name: "Corn Futures",
    group: "Commodity",
    unit: "usd",
    priority: 79,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 玉米期货，受气候、乙醇需求、饲料驱动。",
  },
  {
    symbol: "ZW=F",
    source: "Yahoo Finance",
    name: "Wheat Futures",
    group: "Commodity",
    unit: "usd",
    priority: 80,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 小麦期货，地缘 + 气候敏感品种。",
  },
  {
    symbol: "ZS=F",
    source: "Yahoo Finance",
    name: "Soybean Futures",
    group: "Commodity",
    unit: "usd",
    priority: 81,
    frequency: "Realtime",
    audience: ["农产品"],
    description: "CBOT 大豆期货，中美贸易/南美天气敏感。",
  },
  {
    symbol: "DBC",
    source: "Yahoo Finance",
    name: "Invesco DB Commodity Index (DBC)",
    group: "Commodity",
    unit: "usd",
    priority: 82,
    frequency: "Realtime",
    audience: ["商品", "宏观"],
    description: "广义商品指数 ETF（能源 + 农产品 + 金属）。CRB 指数的可投资代理。",
  },

  // Equity Futures
  {
    symbol: "ES=F",
    source: "Yahoo Finance",
    name: "S&P 500 E-mini Futures",
    group: "Equity",
    unit: "index",
    priority: 83,
    frequency: "Realtime",
    audience: ["期货"],
    description: "S&P 500 电子迷你期货 (ES)，盘前/盘后定价工具。",
  },
  {
    symbol: "NQ=F",
    source: "Yahoo Finance",
    name: "Nasdaq 100 Futures",
    group: "Equity",
    unit: "index",
    priority: 84,
    frequency: "Realtime",
    audience: ["期货"],
    description: "纳斯达克 100 期货 (NQ)。",
  },
  {
    symbol: "FRED:CP",
    providerSymbol: "CP",
    source: "FRED",
    name: "Corporate Profits After Tax",
    group: "Equity",
    unit: "usd",
    priority: 84.5,
    frequency: "Quarterly",
    audience: ["股票", "宏观"],
    description: "美国企业税后利润（十亿美元，季度）。利润周期最终决定股价长期趋势。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "ZN=F",
    source: "Yahoo Finance",
    name: "10Y Treasury Note Futures",
    group: "Rates",
    unit: "usd",
    priority: 85,
    frequency: "Realtime",
    audience: ["期货", "债券"],
    description: "10Y 美债期货 (ZN)，机构对冲利率风险的核心。",
  },
  {
    symbol: "ZB=F",
    source: "Yahoo Finance",
    name: "30Y Treasury Bond Futures",
    group: "Rates",
    unit: "usd",
    priority: 86,
    frequency: "Realtime",
    audience: ["期货", "债券"],
    description: "30Y 长债期货 (ZB)，期限溢价 / 通胀预期衍生工具。",
  },

  // ============================================================
  // TIER 7 — Credit ETFs (87-92)
  // ============================================================
  {
    symbol: "TLT",
    source: "Yahoo Finance",
    name: "iShares 20+Y Treasury (TLT)",
    group: "Rates",
    unit: "usd",
    priority: 87,
    frequency: "Realtime",
    audience: ["债券"],
    description: "长债 ETF，价格与长债收益率反向。",
  },
  {
    symbol: "IEF",
    source: "Yahoo Finance",
    name: "iShares 7-10Y Treasury (IEF)",
    group: "Rates",
    unit: "usd",
    priority: 88,
    frequency: "Realtime",
    audience: ["债券"],
    description: "7-10Y 美债 ETF，经典股债组合的债端。",
  },
  {
    symbol: "TIP",
    source: "Yahoo Finance",
    name: "TIPS ETF (Real Yield Proxy)",
    group: "Rates",
    unit: "usd",
    priority: 89,
    frequency: "Realtime",
    audience: ["债券"],
    description: "通胀挂钩国债 ETF，反映实际利率/通胀预期变化。",
  },
  {
    symbol: "HYG",
    source: "Yahoo Finance",
    name: "iBoxx HY Credit ETF (HYG)",
    group: "Credit",
    unit: "usd",
    priority: 90,
    frequency: "Realtime",
    audience: ["信用"],
    description: "美国高收益债 ETF。下跌常领先股市风险偏好转弱。",
  },
  {
    symbol: "LQD",
    source: "Yahoo Finance",
    name: "iBoxx IG Credit ETF (LQD)",
    group: "Credit",
    unit: "usd",
    priority: 91,
    frequency: "Realtime",
    audience: ["信用"],
    description: "投资级公司债 ETF。",
  },
  {
    symbol: "EMB",
    source: "Yahoo Finance",
    name: "EM Bond ETF (EMB)",
    group: "Credit",
    unit: "usd",
    priority: 92,
    frequency: "Realtime",
    audience: ["新兴市场"],
    description: "新兴市场美元主权债 ETF。",
  },
  {
    symbol: "FRED:EXPGS",
    providerSymbol: "EXPGS",
    source: "FRED",
    name: "U.S. Exports of Goods & Services",
    group: "Growth",
    unit: "usd",
    priority: 92.2,
    frequency: "Quarterly",
    audience: ["宏观", "贸易"],
    description: "美国商品和服务出口（十亿美元，季度年化）。外需和全球贸易周期 proxy。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:IMPGS",
    providerSymbol: "IMPGS",
    source: "FRED",
    name: "U.S. Imports of Goods & Services",
    group: "Growth",
    unit: "usd",
    priority: 92.3,
    frequency: "Quarterly",
    audience: ["宏观", "贸易"],
    description: "美国商品和服务进口（十亿美元，季度年化）。内需和全球供应链需求 proxy。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:FGEXPND",
    providerSymbol: "FGEXPND",
    source: "FRED",
    name: "Federal Government Expenditures",
    group: "Growth",
    unit: "usd",
    priority: 92.4,
    frequency: "Quarterly",
    audience: ["宏观", "财政"],
    description: "美国联邦政府经常支出（十亿美元，季度年化）。财政托底和需求拉动 proxy。",
    transform: (value) => value * 1_000_000_000,
  },
  {
    symbol: "FRED:GFDEGDQ188S",
    providerSymbol: "GFDEGDQ188S",
    source: "FRED",
    name: "U.S. Federal Debt / GDP",
    group: "Credit",
    unit: "percent",
    priority: 92.5,
    frequency: "Quarterly",
    audience: ["宏观", "财政"],
    description: "美国联邦债务 / GDP。观察财政空间、长期利率和期限溢价压力。",
  },

  // ============================================================
  // CHINA / RMB BLOCK — current PBoC / NBS / 海关 / 中债 via Eastmoney,
  // BIS / IMF / OECD via FRED, and NBS/PBoC/BIS versioned snapshots.
  // ============================================================
  {
    symbol: "EM:CN_US_10Y_SPREAD",
    providerSymbol: "US_CN_10Y_SPREAD",
    source: "Eastmoney",
    name: "US–CN 10Y Yield Spread (中美利差)",
    group: "FX",
    unit: "percent",
    priority: 8.5,
    frequency: "Daily",
    audience: ["FX", "宏观", "中国"],
    description:
      "美国 10 年期国债收益率减中国 10 年期国债收益率（百分点）。利差为正且扩大时人民币面临贬值和资金流出压力；利差收窄或转负通常领先人民币升值。是人民币中期方向最重要的单一变量。",
  },
  {
    symbol: "EM:CN_10Y",
    providerSymbol: "CN_10Y",
    source: "Eastmoney",
    name: "China 10Y Treasury Yield (中债 10Y)",
    group: "Rates",
    unit: "percent",
    priority: 8.6,
    frequency: "Daily",
    audience: ["宏观", "中国", "债券"],
    description: "中国 10 年期国债到期收益率（中债估值）。国内无风险利率锚，反映增长/通胀预期和货币政策松紧。",
  },
  {
    symbol: "EM:CN_2Y",
    providerSymbol: "CN_2Y",
    source: "Eastmoney",
    name: "China 2Y Treasury Yield (中债 2Y)",
    group: "Rates",
    unit: "percent",
    priority: 8.7,
    frequency: "Daily",
    audience: ["宏观", "中国", "债券"],
    description: "中国 2 年期国债收益率，对央行政策利率和资金面最敏感的短端锚。",
  },
  {
    symbol: "EM:CN_10Y_2Y",
    providerSymbol: "CN_10Y_2Y",
    source: "Eastmoney",
    name: "China 10Y–2Y Term Spread",
    group: "Rates",
    unit: "percent",
    priority: 8.8,
    frequency: "Daily",
    audience: ["宏观", "中国", "债券"],
    description: "中国国债 10Y-2Y 期限利差。走平/倒挂反映市场对增长悲观或宽松预期不足。",
  },
  {
    symbol: "EM:CN_LPR_1Y",
    providerSymbol: "CN_LPR_1Y",
    source: "Eastmoney",
    name: "China 1Y LPR",
    group: "Rates",
    unit: "percent",
    priority: 8.9,
    frequency: "Monthly (20th)",
    audience: ["宏观", "中国"],
    description: "1 年期贷款市场报价利率，企业短期贷款定价基准，每月 20 日公布。",
  },
  {
    symbol: "EM:CN_LPR_5Y",
    providerSymbol: "CN_LPR_5Y",
    source: "Eastmoney",
    name: "China 5Y LPR (房贷锚)",
    group: "Rates",
    unit: "percent",
    priority: 9.0,
    frequency: "Monthly (20th)",
    audience: ["宏观", "中国", "地产"],
    description: "5 年期以上 LPR，个人住房贷款利率的定价锚。下调直接降低新增房贷成本。",
  },
  {
    symbol: "EM:CN_RRR_LARGE",
    providerSymbol: "CN_RRR_LARGE",
    source: "Eastmoney",
    name: "China RRR (大型机构存款准备金率)",
    group: "Liquidity",
    unit: "percent",
    priority: 9.1,
    frequency: "Event",
    audience: ["宏观", "中国"],
    description: "大型金融机构存款准备金率（调整后）。每次降准释放长期流动性；历史高点 21.5% 是外汇占款对冲时期的产物。",
  },
  {
    symbol: "FRED:DEXCHUS",
    providerSymbol: "DEXCHUS",
    source: "FRED",
    name: "USD/CNY Fed H.10 Fixing",
    group: "FX",
    unit: "ratio",
    priority: 68.15,
    frequency: "Daily",
    audience: ["FX", "中国"],
    description: "纽约中午买入价，美联储 H.10 官方汇率，1981 年起完整日线。用于长周期（MAX）对比，实时看 CNY=X / USDCNH。",
  },
  {
    symbol: "FRED:RBCNBIS",
    providerSymbol: "RBCNBIS",
    source: "FRED",
    name: "China Real Effective Exchange Rate (BIS REER)",
    group: "FX",
    unit: "index",
    priority: 68.2,
    frequency: "Monthly",
    audience: ["FX", "宏观", "中国"],
    description:
      "BIS 中国实际有效汇率指数（2020=100，经通胀调整、贸易加权）。这是央行'参考一篮子'真正盯的口径：对美元升值但 REER 持平，说明只是美元走弱而非人民币走强。",
  },
  {
    symbol: "FRED:NBCNBIS",
    providerSymbol: "NBCNBIS",
    source: "FRED",
    name: "China Nominal Effective Exchange Rate (BIS NEER)",
    group: "FX",
    unit: "index",
    priority: 68.3,
    frequency: "Monthly",
    audience: ["FX", "宏观", "中国"],
    description: "BIS 中国名义有效汇率指数（2020=100）。与 CFETS 人民币汇率指数走势高度一致，可作为其免费替代。",
  },
  {
    symbol: "EURCNY=X",
    source: "Yahoo Finance",
    name: "EUR/CNY",
    group: "FX",
    unit: "ratio",
    priority: 68.4,
    frequency: "Realtime",
    audience: ["FX", "中国"],
    description: "欧元兑人民币。观察人民币对非美货币方向，剔除美元自身强弱。",
  },
  {
    symbol: "CNYJPY=X",
    source: "Yahoo Finance",
    name: "CNY/JPY",
    group: "FX",
    unit: "ratio",
    priority: 68.5,
    frequency: "Realtime",
    audience: ["FX", "中国"],
    description: "人民币兑日元。中日出口在第三方市场直接竞争，此交叉盘反映亚洲出口竞争力相对变化。",
  },
  {
    symbol: "FRED:TRESEGCNM052N",
    providerSymbol: "TRESEGCNM052N",
    source: "FRED",
    name: "China FX Reserves ex-Gold (IMF)",
    group: "Liquidity",
    unit: "usd",
    priority: 21.6,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description: "IMF IFS 中国外汇储备（不含黄金，美元）。与 Eastmoney 国家外汇储备互为校验，IMF 口径滞后 1-2 个月但历史更长。",
    transform: (value) => value * 1_000_000,
  },
  {
    symbol: "EM:CN_FX_RESERVES",
    providerSymbol: "CN_FX_RESERVES",
    source: "Eastmoney",
    name: "China FX Reserves (外管局)",
    group: "Liquidity",
    unit: "usd",
    priority: 21.7,
    frequency: "Monthly (7th)",
    audience: ["宏观", "中国", "FX"],
    description:
      "国家外汇储备余额（美元）。当月变化 = 交易性变动 + 估值效应；连续下降且与贸易顺差背离时说明央行在卖美元托汇率或资本在流出。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_GOLD_RESERVES",
    providerSymbol: "CN_GOLD_RESERVES",
    source: "Eastmoney",
    name: "China Gold Reserves (万盎司)",
    group: "Liquidity",
    unit: "count",
    priority: 21.8,
    frequency: "Monthly (7th)",
    audience: ["宏观", "中国"],
    description: "央行黄金储备（万盎司）。持续增持反映储备去美元化和对美债信用的对冲意图。",
  },
  {
    symbol: "EM:CN_FX_DEPOSITS",
    providerSymbol: "CN_FX_DEPOSITS",
    source: "Eastmoney",
    name: "China Onshore FX Deposits (外汇存款余额)",
    group: "Liquidity",
    unit: "usd",
    priority: 21.9,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description:
      "金融机构外汇存款余额（美元）。企业和居民'囤美元不结汇'的直接证据：余额上升 = 贬值预期或等待更好汇率；余额下降 = 结汇意愿回升，往往领先人民币升值。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_FX_LOANS",
    providerSymbol: "CN_FX_LOANS",
    source: "Eastmoney",
    name: "China Onshore FX Loans (外汇贷款余额)",
    group: "Credit",
    unit: "usd",
    priority: 22.0,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description: "金融机构外汇贷款余额（美元）。企业借美元意愿：升值预期下借美元套利增加，贬值预期下主动偿还美元债。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_M2",
    providerSymbol: "CN_M2",
    source: "Eastmoney",
    name: "China M2 (PBoC current)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.2,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "广义货币 M2 余额（人民币），PBoC 最新月度值。替代 FRED/IMF 停更于 2019 年的历史序列。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_M2_YOY",
    providerSymbol: "CN_M2_YOY",
    source: "Eastmoney",
    name: "China M2 YoY",
    group: "Liquidity",
    unit: "percent",
    priority: 21.21,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "M2 同比增速。与名义 GDP 增速的差值反映货币是否'空转'或流入资产市场。",
  },
  {
    symbol: "EM:CN_M1_YOY",
    providerSymbol: "CN_M1_YOY",
    source: "Eastmoney",
    name: "China M1 YoY (企业活期)",
    group: "Liquidity",
    unit: "percent",
    priority: 21.22,
    frequency: "Monthly",
    audience: ["宏观", "中国", "股票"],
    description: "M1 同比。M1-M2 剪刀差是 A 股经典领先指标：M1 回升说明企业活期资金增加、经营活跃度回暖。2024 年起口径纳入个人活期和非银支付备付金。",
  },
  {
    symbol: "EM:CN_M0_YOY",
    providerSymbol: "CN_M0_YOY",
    source: "Eastmoney",
    name: "China M0 YoY (流通现金)",
    group: "Liquidity",
    unit: "percent",
    priority: 21.23,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "流通中现金同比。春节效应显著，需看剔除季节性的趋势。",
  },
  {
    symbol: "EM:CN_NEW_LOANS",
    providerSymbol: "CN_NEW_LOANS",
    source: "Eastmoney",
    name: "China New RMB Loans (当月新增)",
    group: "Credit",
    unit: "cny",
    priority: 21.3,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "当月新增人民币贷款（元）。信贷投放是社融最大分项，1 月'开门红'和季末冲量的季节性很强，看同比而非环比。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_CPI_YOY",
    providerSymbol: "CN_CPI_YOY",
    source: "Eastmoney",
    name: "China CPI YoY",
    group: "Inflation",
    unit: "percent",
    priority: 15.5,
    frequency: "Monthly (9th-10th)",
    audience: ["宏观", "中国"],
    description: "全国居民消费价格同比。与美国 CPI 之差决定实际利差，是中长期人民币购买力平价的基础。",
  },
  {
    symbol: "EM:CN_PPI_YOY",
    providerSymbol: "CN_PPI_YOY",
    source: "Eastmoney",
    name: "China PPI YoY",
    group: "Inflation",
    unit: "percent",
    priority: 15.6,
    frequency: "Monthly (9th-10th)",
    audience: ["宏观", "中国", "股票"],
    description: "工业生产者出厂价格同比。PPI 转正通常对应工业企业利润修复和周期股行情；持续为负是通缩压力信号。",
  },
  {
    symbol: "FRED:CHNCPIALLMINMEI",
    providerSymbol: "CHNCPIALLMINMEI",
    source: "FRED",
    name: "China CPI Level (OECD, 2015=100)",
    group: "Inflation",
    unit: "index",
    priority: 15.7,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "OECD 口径中国 CPI 定基指数。用于与美国 CPIAUCSL 直接比较价格水平走势，滞后约 2 个月。",
  },
  {
    symbol: "EM:CN_PMI_MFG",
    providerSymbol: "CN_PMI_MFG",
    source: "Eastmoney",
    name: "China Manufacturing PMI (官方)",
    group: "Growth",
    unit: "index",
    priority: 24.5,
    frequency: "Monthly (month-end)",
    audience: ["宏观", "中国"],
    description: "国家统计局制造业 PMI，50 为荣枯线。每月最后一天公布，是最早的当月景气读数。",
  },
  {
    symbol: "EM:CN_PMI_NONMFG",
    providerSymbol: "CN_PMI_NONMFG",
    source: "Eastmoney",
    name: "China Non-Manufacturing PMI",
    group: "Growth",
    unit: "index",
    priority: 24.6,
    frequency: "Monthly (month-end)",
    audience: ["宏观", "中国"],
    description: "非制造业商务活动指数，覆盖服务业和建筑业。",
  },
  {
    symbol: "EM:CN_GDP_YOY",
    providerSymbol: "CN_GDP_YOY",
    source: "Eastmoney",
    name: "China Real GDP YoY",
    group: "Growth",
    unit: "percent",
    priority: 27.5,
    frequency: "Quarterly",
    audience: ["宏观", "中国"],
    description: "国内生产总值累计同比（不变价）。",
  },
  {
    symbol: "EM:CN_INDUSTRIAL_YOY",
    providerSymbol: "CN_INDUSTRIAL_YOY",
    source: "Eastmoney",
    name: "China Industrial Value-Added YoY",
    group: "Growth",
    unit: "percent",
    priority: 43.5,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "规模以上工业增加值同比。1-2 月合并公布。",
  },
  {
    symbol: "EM:CN_FAI_YTD_YOY",
    providerSymbol: "CN_FAI_YTD_YOY",
    source: "Eastmoney",
    name: "China Fixed-Asset Investment YoY",
    group: "Growth",
    unit: "percent",
    priority: 45.5,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "固定资产投资（不含农户）同比。基建、制造业、房地产三大分项方向常常背离。",
  },
  {
    symbol: "EM:CN_RETAIL_YOY",
    providerSymbol: "CN_RETAIL_YOY",
    source: "Eastmoney",
    name: "China Retail Sales YoY",
    group: "Growth",
    unit: "percent",
    priority: 41.5,
    frequency: "Monthly",
    audience: ["宏观", "中国", "消费"],
    description: "社会消费品零售总额同比，内需最直接的月度读数。",
  },
  {
    symbol: "EM:CN_CONSUMER_CONFIDENCE",
    providerSymbol: "CN_CONSUMER_CONFIDENCE",
    source: "Eastmoney",
    name: "China Consumer Confidence Index",
    group: "Sentiment",
    unit: "index",
    priority: 41.6,
    frequency: "Monthly",
    audience: ["宏观", "中国", "消费"],
    description: "国家统计局消费者信心指数（100 为中性）。2022 年 4 月断崖式下跌后长期低于 90。",
  },
  {
    symbol: "EM:CN_EXPORTS",
    providerSymbol: "CN_EXPORTS",
    source: "Eastmoney",
    name: "China Exports (当月，美元)",
    group: "Trade",
    unit: "usd",
    priority: 90.1,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易"],
    description: "海关总署当月出口金额（美元）。出口总额而非顺差才是贸易繁荣度指标。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_IMPORTS",
    providerSymbol: "CN_IMPORTS",
    source: "Eastmoney",
    name: "China Imports (当月，美元)",
    group: "Trade",
    unit: "usd",
    priority: 90.2,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易"],
    description: "海关总署当月进口金额（美元）。进口塌得比出口快形成的'衰退型顺差'不是好信号。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_TRADE_BALANCE",
    providerSymbol: "CN_TRADE_BALANCE",
    source: "Eastmoney",
    name: "China Trade Balance (当月顺差)",
    group: "Trade",
    unit: "usd",
    priority: 90.3,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易", "FX"],
    description: "当月出口减进口（美元）。经常项目顺差是人民币升值压力的根本来源；顺差扩大但外储不增、外汇存款上升，说明美元留在了企业手里。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_EXPORTS_YOY",
    providerSymbol: "CN_EXPORTS_YOY",
    source: "Eastmoney",
    name: "China Exports YoY",
    group: "Trade",
    unit: "percent",
    priority: 90.4,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易"],
    description: "出口金额同比（美元计价）。",
  },
  {
    symbol: "EM:CN_IMPORTS_YOY",
    providerSymbol: "CN_IMPORTS_YOY",
    source: "Eastmoney",
    name: "China Imports YoY",
    group: "Trade",
    unit: "percent",
    priority: 90.5,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易"],
    description: "进口金额同比（美元计价），内需和大宗商品需求代理。",
  },
  {
    symbol: "FRED:XTNTVA01CNM667S",
    providerSymbol: "XTNTVA01CNM667S",
    source: "FRED",
    name: "China Net Trade (OECD, USD)",
    group: "Trade",
    unit: "usd",
    priority: 90.6,
    frequency: "Monthly",
    audience: ["宏观", "中国", "贸易"],
    description: "OECD MEI 中国货物净出口（美元）。与海关口径交叉验证，历史序列更长。",
  },
  {
    symbol: "EM:CN_A_TOTAL_MCAP",
    providerSymbol: "CN_A_TOTAL_MCAP",
    source: "Eastmoney",
    name: "A-Share Total Market Cap (沪深合计)",
    group: "Equity",
    unit: "cny",
    priority: 39.5,
    frequency: "Monthly",
    audience: ["股票", "中国"],
    description: "上海 + 深圳市价总值（元）。除以名义 GDP 即中国版'巴菲特指标'，World Bank 年度口径的月度补充。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_A_TURNOVER",
    providerSymbol: "CN_A_TURNOVER",
    source: "Eastmoney",
    name: "A-Share Monthly Turnover (沪深成交额)",
    group: "Equity",
    unit: "cny",
    priority: 39.6,
    frequency: "Monthly",
    audience: ["股票", "中国"],
    description: "上海 + 深圳当月成交金额（元）。成交额/市值 = 换手率，衡量市场热度。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_FISCAL_REVENUE",
    providerSymbol: "CN_FISCAL_REVENUE",
    source: "Eastmoney",
    name: "China Fiscal Revenue (当月财政收入)",
    group: "Growth",
    unit: "cny",
    priority: 92.6,
    frequency: "Monthly",
    audience: ["宏观", "中国", "财政"],
    description: "全国一般公共预算收入当月值（元）。土地出让金不在此口径，需另看政府性基金收入。",
    transform: (value) => value * 100_000_000,
  },
  // --- Additional PBoC / NBS / 海关 series (Eastmoney datacenter) ---
  {
    symbol: "EM:CN_M1",
    providerSymbol: "CN_M1",
    source: "Eastmoney",
    name: "China M1 (PBoC current)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.215,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "狭义货币 M1 余额（元，2024 年起新口径含个人活期与非银支付备付金）。企业活期存款为主，是实体经济“想花钱”的资金。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_M0",
    providerSymbol: "CN_M0",
    source: "Eastmoney",
    name: "China M0 (流通中现金)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.225,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "流通中现金余额（元）。春节前后季节性最强；持续高增长往往对应现金偏好上升与非正规经济活跃。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_M1_M2_GAP",
    providerSymbol: "CN_M1_M2_GAP",
    source: "Eastmoney",
    name: "China M1–M2 剪刀差",
    group: "Liquidity",
    unit: "percent",
    priority: 21.226,
    frequency: "Monthly",
    audience: ["宏观", "中国", "股票"],
    description: "M1 同比减 M2 同比（百分点）。为负且走阔说明资金定期化、企业不愿投资；转正回升通常领先 A 股与 PPI 上行 3-6 个月。",
  },
  {
    symbol: "EM:CN_NEW_LOANS_YTD",
    providerSymbol: "CN_NEW_LOANS_YTD",
    source: "Eastmoney",
    name: "China New RMB Loans YTD (累计新增贷款)",
    group: "Credit",
    unit: "cny",
    priority: 21.31,
    frequency: "Monthly",
    audience: ["宏观", "中国"],
    description: "年初至今新增人民币贷款累计值（元）。剔除单月季节性后看信贷投放节奏。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_FX_RESERVES_YOY",
    providerSymbol: "CN_FX_RESERVES_YOY",
    source: "Eastmoney",
    name: "China FX Reserves YoY",
    group: "FX",
    unit: "percent",
    priority: 21.71,
    frequency: "Monthly (7th)",
    audience: ["宏观", "中国", "FX"],
    description: "外汇储备同比。剔除估值效应后持续为负是央行卖出美元托底汇率的信号；2015-16 年曾连续两位数下滑。",
  },
  {
    symbol: "EM:CN_RRR_SMALL",
    providerSymbol: "CN_RRR_SMALL",
    source: "Eastmoney",
    name: "China RRR (中小机构存款准备金率)",
    group: "Liquidity",
    unit: "percent",
    priority: 9.11,
    frequency: "Event",
    audience: ["宏观", "中国"],
    description: "中小型金融机构存款准备金率（调整后）。定向降准时与大型机构分化，反映对小微/县域信贷的倾斜。",
  },
  {
    symbol: "EM:CN_CPI_MOM",
    providerSymbol: "CN_CPI_MOM",
    source: "Eastmoney",
    name: "China CPI MoM",
    group: "Inflation",
    unit: "percent",
    priority: 15.55,
    frequency: "Monthly (9th-10th)",
    audience: ["宏观", "中国"],
    description: "CPI 环比。比同比更早反映猪价、油价和服务价格的转向。",
  },
  {
    symbol: "EM:CN_GDP_YTD",
    providerSymbol: "CN_GDP_YTD",
    source: "Eastmoney",
    name: "China Nominal GDP YTD (累计)",
    group: "Growth",
    unit: "cny",
    priority: 27.51,
    frequency: "Quarterly",
    audience: ["宏观", "中国"],
    description: "名义 GDP 年初至今累计值（元）。与 M2 相除得货币化率，与总市值相除得巴菲特指标。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_RETAIL_SALES",
    providerSymbol: "CN_RETAIL_SALES",
    source: "Eastmoney",
    name: "China Retail Sales (社零当月)",
    group: "Growth",
    unit: "cny",
    priority: 41.51,
    frequency: "Monthly",
    audience: ["宏观", "中国", "消费"],
    description: "社会消费品零售总额当月值（元）。1-2 月合并公布，季节性强，看同比更稳。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_TRADE_BALANCE_YTD",
    providerSymbol: "CN_TRADE_BALANCE_YTD",
    source: "Eastmoney",
    name: "China Trade Balance YTD (累计顺差)",
    group: "Trade",
    unit: "usd",
    priority: 90.31,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description: "年初至今累计货物贸易顺差（美元）。顺差是人民币升值压力的基本面来源；结售汇顺差远小于贸易顺差时说明企业在囤美元。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_FDI",
    providerSymbol: "CN_FDI",
    source: "Eastmoney",
    name: "China FDI (实际使用外资当月)",
    group: "FX",
    unit: "usd",
    priority: 22.1,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description: "实际使用外资金额当月值（美元）。直接投资项下的美元流入，与贸易顺差共同构成结售汇的供给端。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "EM:CN_FDI_YTD_YOY",
    providerSymbol: "CN_FDI_YTD_YOY",
    source: "Eastmoney",
    name: "China FDI YTD YoY",
    group: "FX",
    unit: "percent",
    priority: 22.11,
    frequency: "Monthly",
    audience: ["宏观", "中国", "FX"],
    description: "实际使用外资累计同比。2023 年后持续负增长，是外资撤离/观望情绪的直接量化。",
  },
  {
    symbol: "SNAP:NBS_UNEMPLOYMENT",
    providerSymbol: "NBS_UNEMPLOYMENT",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Urban Surveyed Unemployment (年末)",
    group: "Employment",
    unit: "percent",
    priority: 18.5,
    frequency: "Annual",
    audience: ["宏观", "中国"],
    description: "城镇调查失业率年末值（统计公报口径）。月度值需 NBS 月报；此处为年度锚点。",
  },
  // --- NBS 统计公报 / PBoC / BIS snapshot (ported from bridge-win/house) ---
  {
    symbol: "SNAP:NBS_INCOME",
    providerSymbol: "NBS_INCOME",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Per-Capita Disposable Income (人均可支配收入)",
    group: "Growth",
    unit: "cny",
    priority: 41.7,
    frequency: "Annual",
    audience: ["宏观", "中国", "消费"],
    description: "全国居民人均可支配收入（元/人/年），国家统计局年度公报。覆盖全体居民，包含工资、经营、财产和转移收入；平均数不代表典型家庭。",
  },
  {
    symbol: "SNAP:NBS_URBAN_INCOME",
    providerSymbol: "NBS_URBAN_INCOME",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Urban Per-Capita Income (城镇人均可支配收入)",
    group: "Growth",
    unit: "cny",
    priority: 41.71,
    frequency: "Annual",
    audience: ["宏观", "中国", "消费"],
    description: "城镇居民人均可支配收入（元/人/年）。",
  },
  {
    symbol: "SNAP:NBS_INCOME_MEDIAN",
    providerSymbol: "NBS_INCOME_MEDIAN",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Median Disposable Income (收入中位数)",
    group: "Growth",
    unit: "cny",
    priority: 41.72,
    frequency: "Annual",
    audience: ["宏观", "中国", "消费"],
    description: "全国居民人均可支配收入中位数（元/人/年）。中位数/平均数比值下降意味着分配更不均。2015 年起公布。",
  },
  {
    symbol: "SNAP:NBS_DEPOSITS",
    providerSymbol: "NBS_DEPOSITS",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Household RMB Deposits (住户存款余额)",
    group: "Liquidity",
    unit: "cny",
    priority: 21.4,
    frequency: "Annual",
    audience: ["宏观", "中国", "消费"],
    description: "住户人民币存款余额（亿元→元）。存款也可能因预防性储蓄、理财赎回和少买房而上升；不等于居民总财富。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "SNAP:NBS_URBAN_POPULATION",
    providerSymbol: "NBS_URBAN_POPULATION",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Urban Population (城镇常住人口)",
    group: "Growth",
    unit: "count",
    priority: 41.73,
    frequency: "Annual",
    audience: ["宏观", "中国"],
    description: "城镇常住人口（万人）。2020 年人口普查与前期公报不可直接同比。",
  },
  {
    symbol: "SNAP:PBOC_MORTGAGE_RATE",
    providerSymbol: "PBOC_MORTGAGE_RATE",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China New Mortgage Rate (12月新发放房贷利率)",
    group: "RealEstate",
    unit: "percent",
    priority: 33.5,
    frequency: "Annual (Dec)",
    audience: ["宏观", "中国", "地产"],
    description: "每年 12 月新发放个人住房贷款加权平均利率，来自央行货币政策执行报告。比 5Y LPR 更接近真实住房融资条件。",
  },
  {
    symbol: "SNAP:BIS_HPI_CN",
    providerSymbol: "BIS_HPI_CN",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.6,
    frequency: "Quarterly",
    audience: ["宏观", "中国", "地产"],
    description: "BIS 中国实际住宅价格指数（2010=100，经 CPI 调整）。2016 年口径切换，之前的数据仅供参考。",
  },
  {
    symbol: "SNAP:NBS_SALES",
    providerSymbol: "NBS_SALES",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Residential Sales Area (商品住宅销售面积)",
    group: "RealEstate",
    unit: "count",
    priority: 33.7,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "商品住宅销售面积（万平方米/年），不含二手房。",
  },
  {
    symbol: "SNAP:NBS_INVESTMENT",
    providerSymbol: "NBS_INVESTMENT",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Real Estate Development Investment (房地产开发投资)",
    group: "RealEstate",
    unit: "cny",
    priority: 33.71,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "房地产开发投资（亿元→元）。2023 年起统计公报才单列，历史较短。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "SNAP:NBS_STARTS",
    providerSymbol: "NBS_STARTS",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Housing Starts (住宅新开工面积)",
    group: "RealEstate",
    unit: "count",
    priority: 33.72,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "住宅新开工面积（万平方米/年），未来供给管线和开发商信心。",
  },
  {
    symbol: "SNAP:NBS_COMPLETIONS",
    providerSymbol: "NBS_COMPLETIONS",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Housing Completions (住宅竣工面积)",
    group: "RealEstate",
    unit: "count",
    priority: 33.73,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "住宅竣工面积（万平方米/年），受保交房政策影响。",
  },
  {
    symbol: "SNAP:NBS_INVENTORY",
    providerSymbol: "NBS_INVENTORY",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Unsold Housing Inventory (商品住宅待售面积)",
    group: "RealEstate",
    unit: "count",
    priority: 33.74,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "商品住宅待售面积（万平方米），狭义现房库存。",
  },
  {
    symbol: "SNAP:NBS_MORTGAGE_FLOW",
    providerSymbol: "NBS_MORTGAGE_FLOW",
    source: "NBS/PBoC/BIS Snapshot",
    name: "China Developer Mortgage Receipts (开发企业到位资金-个人按揭)",
    group: "RealEstate",
    unit: "cny",
    priority: 33.75,
    frequency: "Annual",
    audience: ["宏观", "中国", "地产"],
    description: "房地产开发企业到位资金中的个人按揭贷款（亿元→元），新房购房融资流入。",
    transform: (value) => value * 100_000_000,
  },
  {
    symbol: "SNAP:BIS_HPI_US",
    providerSymbol: "BIS_HPI_US",
    source: "NBS/PBoC/BIS Snapshot",
    name: "U.S. Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.8,
    frequency: "Quarterly",
    audience: ["宏观", "地产"],
    description: "BIS 美国实际住宅价格指数（2010=100）。",
  },
  {
    symbol: "SNAP:BIS_HPI_JP",
    providerSymbol: "BIS_HPI_JP",
    source: "NBS/PBoC/BIS Snapshot",
    name: "Japan Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.81,
    frequency: "Quarterly",
    audience: ["宏观", "地产"],
    description: "BIS 日本实际住宅价格指数（2010=100），1955 年起，覆盖完整泡沫周期，是中国地产的经典对照组。",
  },
  {
    symbol: "SNAP:BIS_HPI_DE",
    providerSymbol: "BIS_HPI_DE",
    source: "NBS/PBoC/BIS Snapshot",
    name: "Germany Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.82,
    frequency: "Quarterly",
    audience: ["宏观", "地产"],
    description: "BIS 德国实际住宅价格指数（2010=100）。",
  },
  {
    symbol: "SNAP:BIS_HPI_UK",
    providerSymbol: "BIS_HPI_UK",
    source: "NBS/PBoC/BIS Snapshot",
    name: "U.K. Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.83,
    frequency: "Quarterly",
    audience: ["宏观", "地产"],
    description: "BIS 英国实际住宅价格指数（2010=100）。",
  },
  {
    symbol: "SNAP:BIS_HPI_AU",
    providerSymbol: "BIS_HPI_AU",
    source: "NBS/PBoC/BIS Snapshot",
    name: "Australia Real House Price Index (BIS)",
    group: "RealEstate",
    unit: "index",
    priority: 33.84,
    frequency: "Quarterly",
    audience: ["宏观", "地产"],
    description: "BIS 澳大利亚实际住宅价格指数（2010=100）。",
  },
]

export const MACRO_INDICATORS: MacroIndicatorMeta[] = BASE_MACRO_INDICATORS.map(withPriorityCategory)

// =====================================================================
// Indicators we still do NOT integrate (paid / no stable JSON endpoint).
// Single source of truth on coverage gaps; rendered on /macro.
// =====================================================================
export interface SkippedIndicator {
  name: string
  reason: string
  /** Where the data lives when it exists publicly, so a future provider can be wired. */
  url?: string
}

export const SKIPPED_INDICATORS: readonly SkippedIndicator[] = [
  {
    name: "SAFE 银行结售汇 / 代客涉外收付款 / 结汇率·售汇率",
    reason:
      "外管局每月以 HTML 表格 + Excel 发布，没有稳定 JSON API。这是判断'企业是否囤美元'最直接的流量数据，与外汇存款余额互补；需写解析脚本做成快照。",
    url: "https://www.safe.gov.cn/safe/yhjsh/index.html",
  },
  {
    name: "社会融资规模增量 / 存量（TSF）",
    reason:
      "PBoC 月度发布，Eastmoney 数据中心无对应报表；商务部数据中心有 POST 接口（datamofcom shrzgmQuery）但 TLS 配置特殊、未验证稳定性。当前用新增人民币贷款作为最大分项代理。",
    url: "http://www.pbc.gov.cn/diaochatongjisi/116219/116319/index.html",
  },
  {
    name: "CFETS 人民币汇率指数 / 每日中间价",
    reason:
      "中国外汇交易中心网页发布，无公开 JSON。BIS NEER（FRED NBCNBIS）走势与 CFETS 指数高度一致，作为免费替代；中间价可用金十 exchange_rate.json 但属第三方镜像。",
    url: "https://www.chinamoney.com.cn/chinese/bkccpr/",
  },
  {
    name: "MLF 利率 / 逆回购利率 / DR007",
    reason: "PBoC 公开市场业务公告为 HTML；DR007 在外汇交易中心网页。LPR 和 RRR 已接入，政策利率本身仍缺。",
    url: "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/index.html",
  },
  {
    name: "国际收支平衡表（BOP）/ 国际投资头寸表（IIP）",
    reason: "外管局季度 Excel 发布，滞后一个季度；适合做快照而非实时。",
    url: "https://www.safe.gov.cn/safe/gjshpht/index.html",
  },
  {
    name: "CME FedWatch / Fed Funds Implied Probability",
    reason: "需要 CME Group 付费数据 (CME Direct / FedWatch API)",
  },
  { name: "CFTC Commitments of Traders (COT)", reason: "CFTC 提供周报 ZIP，需要单独解析与清洗" },
  {
    name: "Live ISM / S&P Global PMI",
    reason: "FRED 已不稳定提供 ISM PMI；当前用 FRED 制造业工业生产 IPMAN 作为稳定 proxy",
  },
  { name: "Bloomberg / Reuters NLP 新闻情绪", reason: "需要 Bloomberg/Reuters 终端订阅" },
  { name: "X / Reddit / Google Trends / 百度指数", reason: "API 付费或速率限制严" },
  { name: "美股 Put/Call Ratio / Cboe 期权数据", reason: "Cboe DataShop 付费" },
  { name: "ICE MOVE Index", reason: "ICE BofA 付费；FRED 上没有；可用 ^TYX 波动率自算近似" },
  { name: "Goldman / Fed 金融条件指数 FCI", reason: "需 Bloomberg；可用 ChicagoFed FRED NFCI 近似" },
  { name: "美股 EPS 预期 / Forward PE / ERP", reason: "FactSet / Bloomberg 付费" },
  {
    name: "ETF 资金流 / 共同基金资金流 / A股北向 / 港股南向 / 两融余额",
    reason: "需要 ICI / 港交所 / 交易所专门数据源；当前只展示可公开拉取的价格/市值/信用 proxy",
  },
]

export const MACRO_INDICATOR_MAP: Record<string, MacroIndicatorMeta> = Object.fromEntries(
  MACRO_INDICATORS.map((entry) => [entry.symbol, entry]),
)

export const MACRO_PRIMARY_SYMBOLS: string[] = MACRO_INDICATORS.filter((entry) => entry.priority <= 12).map(
  (entry) => entry.symbol,
)
