export type SignalFamily =
  | "trend"
  | "momentum"
  | "value"
  | "quality"
  | "carry"
  | "volatility"
  | "liquidity"
  | "positioning"
  | "macro"
  | "sentiment"
  | "event"
  | "ml"
  | "risk"
  | "onchain"
  | "microstructure"
  | "options"

export type PractitionerPriority = "P0" | "P1" | "P2"

export interface ResearchPaper {
  id: string
  title: string
  authors: string
  year: number
  url: string
  market: string
  families: readonly SignalFamily[]
  takeaway: string
  caveat: string
}

export interface PractitionerSignalMethod {
  id: string
  category: string
  method: string
  source: string
  url: string
  dataRequired: string
  interpretation: string
  failureMode: string
  priority: PractitionerPriority
}

export interface SignalLayer {
  id: string
  title: string
  description: string
  primaryFamilies: readonly SignalFamily[]
  dataSources: readonly string[]
  actionRule: string
}

export interface SourceGroup {
  id: string
  title: string
  status: "wired" | "planned" | "research"
  url: string
  useCase: string
}

export const PAPER_RESEARCH_CORPUS: readonly ResearchPaper[] = [
  { id: "p001", title: "Portfolio Selection", authors: "Markowitz", year: 1952, url: "https://doi.org/10.1111/j.1540-6261.1952.tb01525.x", market: "multi-asset", families: ["risk"], takeaway: "Start every signal stack with sizing, covariance, and diversification.", caveat: "Expected returns and covariances are unstable inputs." },
  { id: "p002", title: "The Cross-Section of Expected Stock Returns", authors: "Fama and French", year: 1992, url: "https://doi.org/10.1111/j.1540-6261.1992.tb04398.x", market: "equities", families: ["value"], takeaway: "Size and book-to-market remain core equity ranking variables.", caveat: "Factor interpretation and live implementability vary by regime." },
  { id: "p003", title: "Common Risk Factors in the Returns on Stocks and Bonds", authors: "Fama and French", year: 1993, url: "https://ideas.repec.org/a/eee/jfinec/v33y1993i1p3-56.html", market: "stocks and bonds", families: ["value", "risk"], takeaway: "Use factor exposures to separate alpha from broad risk.", caveat: "Attribution factors are not automatically standalone trades." },
  { id: "p004", title: "A Five-Factor Asset Pricing Model", authors: "Fama and French", year: 2015, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2287202", market: "equities", families: ["value", "quality"], takeaway: "Profitability and investment improve equity selection frameworks.", caveat: "HML can be partly subsumed and factor returns decay." },
  { id: "p005", title: "Returns to Buying Winners and Selling Losers", authors: "Jegadeesh and Titman", year: 1993, url: "https://doi.org/10.1111/j.1540-6261.1993.tb04702.x", market: "equities", families: ["momentum"], takeaway: "Cross-sectional momentum is a durable ranking signal.", caveat: "Crashes, turnover, and crowding matter." },
  { id: "p006", title: "On Persistence in Mutual Fund Performance", authors: "Carhart", year: 1997, url: "https://doi.org/10.1111/j.1540-6261.1997.tb03808.x", market: "funds and equities", families: ["momentum", "risk"], takeaway: "Momentum belongs in baseline performance attribution.", caveat: "The model is attribution-first, not a trading recipe." },
  { id: "p007", title: "Value and Momentum Everywhere", authors: "Asness, Moskowitz and Pedersen", year: 2013, url: "https://doi.org/10.1111/jofi.12021", market: "global multi-asset", families: ["value", "momentum"], takeaway: "Value and momentum diversify across asset classes.", caveat: "Crowding and funding stress can dominate." },
  { id: "p008", title: "Time Series Momentum", authors: "Moskowitz, Ooi and Pedersen", year: 2012, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2089463", market: "futures, FX, bonds, equities", families: ["trend"], takeaway: "Own-asset 1-12 month trend is a core CTA-style signal.", caveat: "Sensitive to transaction costs and sharp reversals." },
  { id: "p009", title: "A Century of Evidence on Trend-Following Investing", authors: "Hurst, Ooi and Pedersen", year: 2017, url: "https://ssrn.com/abstract=2993026", market: "multi-asset futures", families: ["trend", "risk"], takeaway: "Diversified trend can persist across long samples.", caveat: "Backtest assumptions and futures access matter." },
  { id: "p010", title: "Simple Technical Trading Rules and Stock Returns", authors: "Brock, Lakonishok and LeBaron", year: 1992, url: "https://doi.org/10.1111/j.1540-6261.1992.tb04681.x", market: "Dow Jones", families: ["trend"], takeaway: "Moving-average and breakout rules can contain signal.", caveat: "Older samples face modern cost and data-mining tests." },
  { id: "p011", title: "Foundations of Technical Analysis", authors: "Lo, Mamaysky and Wang", year: 2000, url: "https://doi.org/10.1111/0022-1082.00265", market: "equities", families: ["trend", "volatility"], takeaway: "Pattern recognition needs formal testing, not chart folklore.", caveat: "Pattern definitions are fragile." },
  { id: "p012", title: "A New Anomaly: The Cross-Sectional Profitability of Technical Analysis", authors: "Han, Yang and Zhou", year: 2013, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1656460", market: "equities", families: ["trend", "volatility"], takeaway: "Technical timing can be stronger in high-volatility portfolios.", caveat: "Needs replication with costs." },
  { id: "p013", title: "Forecasting the Equity Risk Premium: The Role of Technical Indicators", authors: "Neely, Rapach, Tu and Zhou", year: 2014, url: "https://doi.org/10.1287/mnsc.2013.1838", market: "US equity index", families: ["trend", "macro"], takeaway: "Technical indicators can improve aggregate equity premium forecasts.", caveat: "Low-frequency timing gains are modest." },
  { id: "p014", title: "Momentum Has Its Moments", authors: "Barroso and Santa-Clara", year: 2015, url: "https://doi.org/10.1016/j.jfineco.2014.11.002", market: "equities", families: ["momentum", "volatility"], takeaway: "Volatility-scaling can reduce momentum crashes.", caveat: "Leverage and turnover constraints still bind." },
  { id: "p015", title: "Momentum Crashes", authors: "Daniel and Moskowitz", year: 2016, url: "https://doi.org/10.1016/j.jfineco.2015.12.002", market: "global equities", families: ["momentum", "risk"], takeaway: "Momentum crash risk is state-dependent and must be monitored.", caveat: "Crash hedging is hard in real time." },
  { id: "p016", title: "Is Momentum Really Momentum?", authors: "Novy-Marx", year: 2012, url: "https://doi.org/10.1016/j.jfineco.2011.05.003", market: "equities", families: ["momentum"], takeaway: "Intermediate-horizon returns often drive momentum.", caveat: "Signal definition changes results." },
  { id: "p017", title: "Persuasive Evidence of Market Inefficiency", authors: "Rosenberg, Reid and Lanstein", year: 1985, url: "https://doi.org/10.3905/jpm.1985.409007", market: "equities", families: ["value"], takeaway: "Book-to-market value has early empirical support.", caveat: "Older sample and implementation detail limits." },
  { id: "p018", title: "Contrarian Investment, Extrapolation, and Risk", authors: "Lakonishok, Shleifer and Vishny", year: 1994, url: "https://doi.org/10.1111/j.1540-6261.1994.tb04772.x", market: "equities", families: ["value"], takeaway: "Contrarian value can exploit extrapolation.", caveat: "Value can underperform for long periods." },
  { id: "p019", title: "Value Investing: The Use of Historical Financial Statement Information", authors: "Piotroski", year: 2000, url: "https://doi.org/10.2307/2672906", market: "value equities", families: ["value", "quality"], takeaway: "F-score improves quality control in cheap stocks.", caveat: "Accounting data lags and can be restated." },
  { id: "p020", title: "Do Stock Prices Fully Reflect Information in Accruals and Cash Flows?", authors: "Sloan", year: 1996, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2598", market: "equities", families: ["quality"], takeaway: "Accruals help distinguish durable from weak earnings.", caveat: "Definitions and accounting regimes matter." },
  { id: "p021", title: "The Other Side of Value", authors: "Novy-Marx", year: 2013, url: "https://doi.org/10.1016/j.jfineco.2013.01.003", market: "equities", families: ["quality"], takeaway: "Gross profitability is a strong quality signal.", caveat: "Best with robust accounting data." },
  { id: "p022", title: "Asset Growth and the Cross-Section of Stock Returns", authors: "Cooper, Gulen and Schill", year: 2008, url: "https://doi.org/10.1111/j.1540-6261.2008.01370.x", market: "equities", families: ["quality", "value"], takeaway: "Low asset growth predicts higher subsequent returns.", caveat: "Overlaps with value and investment factors." },
  { id: "p023", title: "Share Issuance and Cross-Sectional Returns", authors: "Pontiff and Woodgate", year: 2008, url: "https://doi.org/10.1111/j.1540-6261.2008.01335.x", market: "equities", families: ["value", "event"], takeaway: "Net issuance helps identify dilution pressure.", caveat: "Corporate-action data quality matters." },
  { id: "p024", title: "Betting Against Beta", authors: "Frazzini and Pedersen", year: 2014, url: "https://doi.org/10.1016/j.jfineco.2013.10.005", market: "global multi-asset", families: ["quality", "risk"], takeaway: "Low-beta exposure can outperform risk-adjusted high beta.", caveat: "Funding constraints can reverse the trade." },
  { id: "p025", title: "Quality Minus Junk", authors: "Asness, Frazzini and Pedersen", year: 2019, url: "https://doi.org/10.1007/s11142-018-9470-2", market: "global equities", families: ["quality"], takeaway: "Quality screens improve resilience and returns.", caveat: "Definitions and crowding matter." },
  { id: "p026", title: "The Characteristics That Provide Independent Information about Average U.S. Monthly Stock Returns", authors: "Green, Hand and Zhang", year: 2017, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2262374", market: "equities", families: ["value", "quality", "momentum"], takeaway: "Factor stacks need joint tests, not isolated anecdotes.", caveat: "Microcaps and multiple testing can inflate results." },
  { id: "p027", title: "Digesting Anomalies: An Investment Approach", authors: "Hou, Xue and Zhang", year: 2015, url: "https://doi.org/10.1093/rfs/hhu068", market: "equities", families: ["value", "quality"], takeaway: "Investment and profitability explain many anomalies.", caveat: "Conclusions depend on model choice." },
  { id: "p028", title: "... and the Cross-Section of Expected Returns", authors: "Harvey, Liu and Zhu", year: 2016, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2249314", market: "equity factors", families: ["risk"], takeaway: "Raise the statistical hurdle for new factors.", caveat: "A validation warning, not a trading signal." },
  { id: "p029", title: "Does Academic Research Destroy Stock Return Predictability?", authors: "McLean and Pontiff", year: 2016, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2156623", market: "equity anomalies", families: ["risk"], takeaway: "Post-publication factor returns often decay.", caveat: "Decay varies by liquidity and crowding." },
  { id: "p030", title: "Illiquidity and Stock Returns", authors: "Amihud", year: 2002, url: "https://ideas.repec.org/a/eee/finmar/v5y2002i1p31-56.html", market: "equities", families: ["liquidity"], takeaway: "Illiquidity can price expected returns.", caveat: "Proxy is coarse for modern markets." },
  { id: "p031", title: "Liquidity Risk and Expected Stock Returns", authors: "Pastor and Stambaugh", year: 2003, url: "https://doi.org/10.1086/374184", market: "equities", families: ["liquidity"], takeaway: "Market-wide liquidity risk is priced.", caveat: "Monthly estimation is noisy." },
  { id: "p032", title: "Asset Pricing with Liquidity Risk", authors: "Acharya and Pedersen", year: 2005, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=601116", market: "equities", families: ["liquidity", "risk"], takeaway: "Required returns depend on liquidity covariance.", caveat: "Inputs are hard to estimate live." },
  { id: "p033", title: "The Cross-Section of Volatility and Expected Returns", authors: "Ang, Hodrick, Xing and Zhang", year: 2006, url: "https://doi.org/10.1111/j.1540-6261.2006.00836.x", market: "equities", families: ["volatility"], takeaway: "High idiosyncratic volatility can predict lower returns.", caveat: "Replication is construction-sensitive." },
  { id: "p034", title: "Maxing Out: Stocks as Lotteries and the Cross-Section of Expected Returns", authors: "Bali, Cakici and Whitelaw", year: 2011, url: "https://doi.org/10.1016/j.jfineco.2010.08.014", market: "equities", families: ["volatility", "sentiment"], takeaway: "Extreme positive-return lottery stocks often underperform.", caveat: "May proxy for retail demand." },
  { id: "p035", title: "Volatility-Managed Portfolios", authors: "Moreira and Muir", year: 2017, url: "https://doi.org/10.1111/jofi.12513", market: "factor portfolios", families: ["volatility", "risk"], takeaway: "Scale exposure down when realized volatility is high.", caveat: "Volatility lags and leverage constraints matter." },
  { id: "p036", title: "The Economic Value of Volatility Timing", authors: "Fleming, Kirby and Ostdiek", year: 2001, url: "https://doi.org/10.1111/0022-1082.00327", market: "stocks, bonds and gold", families: ["volatility", "risk"], takeaway: "Volatility forecasts can improve allocation.", caveat: "Benefits depend on costs and forecast quality." },
  { id: "p037", title: "Expected Stock Returns and Variance Risk Premia", authors: "Bollerslev, Tauchen and Zhou", year: 2009, url: "https://doi.org/10.1093/rfs/hhp008", market: "equity index options", families: ["volatility"], takeaway: "Variance risk premium can forecast market returns.", caveat: "Options surface and horizon choices matter." },
  { id: "p038", title: "Variance Risk Premiums", authors: "Carr and Wu", year: 2009, url: "https://academic.oup.com/rfs/article-abstract/22/3/1311/1581057", market: "options and equities", families: ["volatility"], takeaway: "Implied minus realized variance is a risk-premium gauge.", caveat: "Requires liquid options data." },
  { id: "p039", title: "Investor Sentiment and the Cross-Section of Stock Returns", authors: "Baker and Wurgler", year: 2006, url: "https://doi.org/10.1111/j.1540-6261.2006.00885.x", market: "equities", families: ["sentiment"], takeaway: "Sentiment matters most for hard-to-arbitrage stocks.", caveat: "Index construction matters." },
  { id: "p040", title: "Giving Content to Investor Sentiment", authors: "Tetlock", year: 2007, url: "https://doi.org/10.1111/j.1540-6261.2007.01232.x", market: "news and equities", families: ["sentiment"], takeaway: "Media pessimism has short-run market information.", caveat: "Source-specific and horizon-limited." },
  { id: "p041", title: "More Than Words: Quantifying Language to Measure Firms' Fundamentals", authors: "Tetlock, Saar-Tsechansky and Macskassy", year: 2008, url: "https://doi.org/10.1111/j.1540-6261.2008.01362.x", market: "firm news", families: ["sentiment", "event"], takeaway: "News tone can forecast fundamentals and returns.", caveat: "NLP dictionaries age." },
  { id: "p042", title: "When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks", authors: "Loughran and McDonald", year: 2011, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1331573", market: "filings", families: ["sentiment", "quality"], takeaway: "Finance-specific text dictionaries improve filing signals.", caveat: "Boilerplate and timing reduce edge." },
  { id: "p043", title: "Is All That Talk Just Noise?", authors: "Antweiler and Frank", year: 2004, url: "https://doi.org/10.1111/j.1540-6261.2004.00662.x", market: "message boards and equities", families: ["sentiment"], takeaway: "Online bullishness and message volume contain information.", caveat: "Early-internet sample may not generalize." },
  { id: "p044", title: "In Search of Attention", authors: "Da, Engelberg and Gao", year: 2011, url: "https://doi.org/10.1111/j.1540-6261.2011.01679.x", market: "equities", families: ["sentiment"], takeaway: "Search volume can proxy active investor attention.", caveat: "Search behavior changes over time." },
  { id: "p045", title: "All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors", authors: "Barber and Odean", year: 2008, url: "https://doi.org/10.1093/rfs/hhm079", market: "retail equities", families: ["sentiment", "event"], takeaway: "Retail investors chase attention-grabbing assets.", caveat: "Behavioral channel is not direct alpha." },
  { id: "p046", title: "Anomalies and News", authors: "Engelberg, McLean and Pontiff", year: 2018, url: "https://doi.org/10.1111/jofi.12718", market: "equities", families: ["event"], takeaway: "Anomaly returns concentrate around news.", caveat: "News-day definitions matter." },
  { id: "p047", title: "An Empirical Evaluation of Accounting Income Numbers", authors: "Ball and Brown", year: 1968, url: "https://doi.org/10.2307/2490232", market: "earnings", families: ["event"], takeaway: "Earnings news is central to equity repricing.", caveat: "Foundational older market structure." },
  { id: "p048", title: "Post-Earnings-Announcement Drift", authors: "Bernard and Thomas", year: 1989, url: "https://doi.org/10.2307/2491062", market: "earnings", families: ["event", "momentum"], takeaway: "Earnings surprises can drift after announcements.", caveat: "Crowding and costs reduce edge." },
  { id: "p049", title: "Economic Links and Predictable Returns", authors: "Cohen and Frazzini", year: 2008, url: "https://doi.org/10.1111/j.1540-6261.2008.01379.x", market: "customer-supplier equities", families: ["event"], takeaway: "Linked-firm news diffuses slowly.", caveat: "Relationship data coverage is limited." },
  { id: "p050", title: "Event Studies in Economics and Finance", authors: "MacKinlay", year: 1997, url: "https://www.jstor.org/stable/2729691", market: "events", families: ["event", "risk"], takeaway: "Use event-study discipline for news and macro releases.", caveat: "Methodology paper, not a signal." },
  { id: "p051", title: "The Pre-FOMC Announcement Drift", authors: "Lucca and Moench", year: 2015, url: "https://doi.org/10.1111/jofi.12196", market: "equities and FOMC", families: ["macro", "event"], takeaway: "Policy calendars can carry return premia.", caveat: "Regime and calendar dependence are high." },
  { id: "p052", title: "How Much Do Investors Care About Macroeconomic Risk?", authors: "Savor and Wilson", year: 2013, url: "https://doi.org/10.1016/j.jfineco.2013.02.015", market: "equities and bonds", families: ["macro", "event"], takeaway: "Scheduled announcement days carry macro risk premia.", caveat: "Few events make samples fragile." },
  { id: "p053", title: "Business Conditions and Expected Returns on Stocks and Bonds", authors: "Fama and French", year: 1989, url: "https://doi.org/10.1016/0304-405X(89)90095-0", market: "stocks and bonds", families: ["macro"], takeaway: "Expected returns vary with business conditions.", caveat: "Low-frequency timing is difficult." },
  { id: "p054", title: "A Comprehensive Look at the Empirical Performance of Equity Premium Prediction", authors: "Welch and Goyal", year: 2008, url: "https://www.nber.org/papers/w10483", market: "US equity index", families: ["macro", "risk"], takeaway: "Many predictors fail out of sample.", caveat: "A skeptical benchmark, not a signal." },
  { id: "p055", title: "Predicting Excess Stock Returns Out of Sample", authors: "Campbell and Thompson", year: 2008, url: "https://doi.org/10.1093/rfs/hhm055", market: "US equity index", families: ["macro"], takeaway: "Economic restrictions can stabilize forecasts.", caveat: "Forecast gains are usually small." },
  { id: "p056", title: "Out-of-Sample Equity Premium Prediction", authors: "Rapach, Strauss and Zhou", year: 2010, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1257858", market: "US equity index", families: ["macro"], takeaway: "Combining predictors improves stability.", caveat: "Regime failure still occurs." },
  { id: "p057", title: "Consumption, Aggregate Wealth, and Expected Stock Returns", authors: "Lettau and Ludvigson", year: 2001, url: "https://www.newyorkfed.org/research/staff_reports/sr77.html", market: "US equity index", families: ["macro"], takeaway: "cay links consumption wealth to expected returns.", caveat: "Real-time estimation is difficult." },
  { id: "p058", title: "The Dog That Did Not Bark: A Defense of Return Predictability", authors: "Cochrane", year: 2008, url: "https://www.johnhcochrane.com/research-all/the-dog-that-did-not-bark-a-defense-of-return-predictability", market: "US equity index", families: ["macro", "value"], takeaway: "Valuation ratios imply return or cash-flow predictability.", caveat: "Not an implementation recipe." },
  { id: "p059", title: "Market Expectations in the Cross-Section of Present Values", authors: "Kelly and Pruitt", year: 2013, url: "https://doi.org/10.1111/jofi.12060", market: "equities", families: ["macro", "ml"], takeaway: "Cross-sectional valuations can forecast aggregate returns.", caveat: "Model complexity and timing matter." },
  { id: "p060", title: "Carry", authors: "Koijen, Moskowitz, Pedersen and Vrugt", year: 2018, url: "https://doi.org/10.1016/j.jfineco.2017.11.002", market: "global multi-asset", families: ["carry"], takeaway: "Carry is a broad expected-return signal across assets.", caveat: "Crash and funding exposures are real." },
  { id: "p061", title: "Common Risk Factors in Currency Markets", authors: "Lustig, Roussanov and Verdelhan", year: 2011, url: "https://www.nber.org/papers/w14082", market: "FX", families: ["carry", "macro"], takeaway: "FX carry loads on common risk factors.", caveat: "Currency crash risk matters." },
  { id: "p062", title: "Currency Momentum Strategies", authors: "Menkhoff, Sarno, Schmeling and Schrimpf", year: 2012, url: "https://doi.org/10.1016/j.jfineco.2012.06.009", market: "FX", families: ["momentum"], takeaway: "Cross-sectional FX momentum is significant.", caveat: "Transaction costs matter." },
  { id: "p063", title: "The Fundamentals of Commodity Futures Returns", authors: "Gorton, Hayashi and Rouwenhorst", year: 2013, url: "https://doi.org/10.1093/rof/rfs019", market: "commodities", families: ["carry", "macro"], takeaway: "Inventories and basis relate to commodity premia.", caveat: "Commodity fundamentals are hard to source cleanly." },
  { id: "p064", title: "Empirical Asset Pricing via Machine Learning", authors: "Gu, Kelly and Xiu", year: 2020, url: "https://academic.oup.com/rfs/article/33/5/2223/5758276", market: "equities", families: ["ml"], takeaway: "Trees and neural nets can improve return forecasts.", caveat: "Overfit, turnover, and monitoring risks are high." },
  { id: "p065", title: "Dissecting Characteristics Nonparametrically", authors: "Freyberger, Neuhierl and Weber", year: 2020, url: "https://www.nber.org/papers/w23227", market: "equities", families: ["ml", "value", "quality"], takeaway: "Nonlinear characteristic effects can be selected adaptively.", caveat: "Needs careful out-of-sample validation." },
  { id: "p066", title: "Characteristics Are Covariances", authors: "Kelly, Pruitt and Su", year: 2019, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2983919", market: "equities", families: ["ml", "risk"], takeaway: "Characteristics can instrument latent factor loadings.", caveat: "Interpretation depends on factor structure." },
  { id: "p067", title: "Autoencoder Asset Pricing Models", authors: "Gu, Kelly and Xiu", year: 2021, url: "https://doi.org/10.1016/j.jeconom.2020.07.009", market: "equities", families: ["ml"], takeaway: "Autoencoders can learn nonlinear conditional factors.", caveat: "Black-box replication burden is high." },
  { id: "p068", title: "Deep Learning in Asset Pricing", authors: "Chen, Pelger and Zhu", year: 2024, url: "https://doi.org/10.1287/mnsc.2023.4695", market: "equities and macro", families: ["ml", "macro"], takeaway: "No-arbitrage deep nets combine firm and macro data.", caveat: "Requires production-grade monitoring." },
  { id: "p069", title: "Learning to Trade via Direct Reinforcement", authors: "Moody and Saffell", year: 2001, url: "https://doi.org/10.1109/72.935097", market: "equities and FX", families: ["ml", "risk"], takeaway: "Trading policies can optimize risk-adjusted objectives directly.", caveat: "RL overfit risk is severe." },
  { id: "p070", title: "Reinforcement Learning for Optimized Trade Execution", authors: "Nevmyvaka, Feng and Kearns", year: 2006, url: "https://doi.org/10.1145/1143844.1143929", market: "NASDAQ order book", families: ["ml", "microstructure"], takeaway: "RL can adapt execution to order-book state.", caveat: "Execution edge is not alpha generation." },
  { id: "p071", title: "Optimal Execution of Portfolio Transactions", authors: "Almgren and Chriss", year: 2001, url: "https://www.risk.net/journal-risk/2161150/optimal-execution-portfolio-transactions", market: "execution", families: ["risk", "microstructure"], takeaway: "Execution needs impact/risk tradeoff modeling.", caveat: "Impact assumptions are simplified." },
  { id: "p072", title: "High-Frequency Trading in a Limit Order Book", authors: "Avellaneda and Stoikov", year: 2008, url: "https://doi.org/10.1080/14697680701381228", market: "market making", families: ["microstructure", "risk"], takeaway: "Quote placement must balance spread capture and inventory.", caveat: "Stylized order-flow assumptions." },
  { id: "p073", title: "Optimal Versus Naive Diversification", authors: "DeMiguel, Garlappi and Uppal", year: 2009, url: "https://doi.org/10.1093/rfs/hhm075", market: "multi-asset", families: ["risk"], takeaway: "Simple 1/N is hard to beat out of sample.", caveat: "Benchmarks optimization, not alpha." },
  { id: "p074", title: "Honey, I Shrunk the Sample Covariance Matrix", authors: "Ledoit and Wolf", year: 2004, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=433840", market: "portfolio covariance", families: ["risk"], takeaway: "Shrinkage improves covariance stability.", caveat: "Still needs a return model." },
  { id: "p075", title: "Parametric Portfolio Policies", authors: "Brandt, Santa-Clara and Valkanov", year: 2009, url: "https://doi.org/10.1093/rfs/hhp003", market: "equities", families: ["risk", "ml"], takeaway: "Weights can be optimized as functions of characteristics.", caveat: "Utility and turnover assumptions are critical." },
  { id: "p076", title: "Bitcoin: A Peer-to-Peer Electronic Cash System", authors: "Nakamoto", year: 2008, url: "https://bitcoin.org/bitcoin.pdf", market: "Bitcoin", families: ["onchain"], takeaway: "The base protocol defines issuance, settlement, and miner incentives.", caveat: "Whitepaper is protocol design, not a market-return test." },
  { id: "p077", title: "Is Bitcoin a Real Currency?", authors: "Yermack", year: 2015, url: "https://www.nber.org/papers/w19747", market: "Bitcoin", families: ["macro", "volatility"], takeaway: "Bitcoin behaves more like a speculative asset than money in early data.", caveat: "Market structure changed materially post-ETF." },
  { id: "p078", title: "Risks and Returns of Cryptocurrency", authors: "Liu and Tsyvinski", year: 2021, url: "https://www.nber.org/papers/w25882", market: "crypto", families: ["momentum", "sentiment", "macro"], takeaway: "Crypto returns relate to momentum and investor attention more than classic macro alone.", caveat: "Short sample and changing market structure." },
  { id: "p079", title: "Common Risk Factors in Cryptocurrency", authors: "Liu, Tsyvinski and Wu", year: 2022, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3379131", market: "crypto cross-section", families: ["momentum", "risk"], takeaway: "Size, momentum, and crypto-specific common factors help organize returns.", caveat: "Token survivorship and liquidity filters matter." },
  { id: "p080", title: "Trading and Arbitrage in Cryptocurrency Markets", authors: "Makarov and Schoar", year: 2020, url: "https://doi.org/10.1016/j.jfineco.2019.07.001", market: "crypto exchanges", families: ["microstructure", "liquidity"], takeaway: "Cross-venue frictions create persistent spreads and execution constraints.", caveat: "Arbitrage capacity and venue access limit implementation." },
  { id: "p081", title: "Is Bitcoin Really Untethered?", authors: "Griffin and Shams", year: 2020, url: "https://doi.org/10.1111/jofi.12903", market: "Bitcoin and stablecoins", families: ["liquidity", "event"], takeaway: "Stablecoin issuance and market integrity must be monitored.", caveat: "Findings are debated and regime-specific." },
  { id: "p082", title: "The Inefficiency of Bitcoin", authors: "Urquhart", year: 2016, url: "https://doi.org/10.1016/j.econlet.2016.09.019", market: "Bitcoin", families: ["trend", "momentum"], takeaway: "Early Bitcoin markets showed exploitable inefficiency.", caveat: "Efficiency improved as markets matured." },
  { id: "p083", title: "The Inefficiency of Bitcoin Revisited: A Dynamic Approach", authors: "Bariviera", year: 2017, url: "https://doi.org/10.1016/j.econlet.2017.09.013", market: "Bitcoin", families: ["trend", "volatility"], takeaway: "Bitcoin efficiency varies through time.", caveat: "Long-memory estimates are model-sensitive." },
  { id: "p084", title: "On the Inefficiency of Bitcoin", authors: "Nadarajah and Chu", year: 2017, url: "https://doi.org/10.1016/j.econlet.2016.10.033", market: "Bitcoin", families: ["trend"], takeaway: "Efficiency conclusions depend on transformation and test choice.", caveat: "Methodological differences can flip conclusions." },
  { id: "p085", title: "Informational Efficiency of Bitcoin: An Extension", authors: "Tiwari, Jana, Das and Roubaud", year: 2018, url: "https://doi.org/10.1016/j.econlet.2017.12.006", market: "Bitcoin", families: ["trend", "risk"], takeaway: "Bitcoin efficiency evidence is mixed and time-varying.", caveat: "Tests do not directly map to a trade." },
  { id: "p086", title: "Bitcoin, Gold and the Dollar: A GARCH Volatility Analysis", authors: "Dyhrberg", year: 2016, url: "https://doi.org/10.1016/j.frl.2015.10.008", market: "Bitcoin macro", families: ["volatility", "macro"], takeaway: "Bitcoin shares some properties with gold and currency risk.", caveat: "Early sample and volatility-model dependence." },
  { id: "p087", title: "Bitcoin: Medium of Exchange or Speculative Assets?", authors: "Baur, Hong and Lee", year: 2018, url: "https://doi.org/10.1016/j.jimonfin.2017.12.004", market: "Bitcoin", families: ["macro", "sentiment"], takeaway: "Speculative demand dominates transactional use in many periods.", caveat: "Use case mix evolves." },
  { id: "p088", title: "On the Hedge and Safe Haven Properties of Bitcoin", authors: "Bouri, Molnar, Azzi, Roubaud and Hagfors", year: 2017, url: "https://doi.org/10.1016/j.frl.2016.09.025", market: "Bitcoin and global assets", families: ["macro", "risk"], takeaway: "Bitcoin hedge/safe-haven behavior is conditional.", caveat: "Not reliable in every crisis." },
  { id: "p089", title: "Bitcoin Market, Economics and Regulation", authors: "Athey, Parashkevov, Sarukkai and Xia", year: 2016, url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2826674", market: "Bitcoin", families: ["onchain", "macro"], takeaway: "Adoption, use, and regulation shape valuation channels.", caveat: "Market has changed since early adoption." },
  { id: "p090", title: "Cryptocurrency Value Formation: An Empirical Study Leading to a Cost of Production Model for Valuing Bitcoin", authors: "Hayes", year: 2017, url: "https://doi.org/10.1016/j.tele.2016.05.005", market: "Bitcoin mining", families: ["onchain", "value"], takeaway: "Mining cost can anchor long-horizon valuation zones.", caveat: "Cost curves are not short-term timing signals." },
  { id: "p091", title: "From Mining to Markets: The Evolution of Bitcoin Transaction Fees", authors: "Easley, O'Hara and Basu", year: 2019, url: "https://doi.org/10.1016/j.jfineco.2019.03.004", market: "Bitcoin network", families: ["onchain", "microstructure"], takeaway: "Fees connect blockspace demand and miner incentives.", caveat: "Fee spikes can reflect congestion rather than demand quality." },
  { id: "p092", title: "Bitcoin Meets Google Trends and Wikipedia", authors: "Kristoufek", year: 2013, url: "https://doi.org/10.1038/srep03415", market: "Bitcoin", families: ["sentiment"], takeaway: "Search and attention proxies can track Bitcoin demand waves.", caveat: "Attention indicators can invert near euphoric tops." },
  { id: "p093", title: "The Digital Traces of Bubbles: Feedback Cycles between Socio-Economic Signals in the Bitcoin Economy", authors: "Garcia, Tessone, Mavrodiev and Perony", year: 2014, url: "https://doi.org/10.1098/rsif.2014.0623", market: "Bitcoin", families: ["sentiment", "onchain"], takeaway: "Social attention and price can reinforce bubble dynamics.", caveat: "Feedback loops are unstable and reflexive." },
  { id: "p094", title: "How Does Social Media Impact Bitcoin Value?", authors: "Mai, Shan, Bai, Wang and Chiang", year: 2018, url: "https://doi.org/10.1080/07421222.2018.1440774", market: "Bitcoin", families: ["sentiment"], takeaway: "Social media activity can contain price-relevant information.", caveat: "Spam, bots, and platform drift reduce signal quality." },
  { id: "p095", title: "Modelling Bitcoin Price Volatility", authors: "Katsiampa", year: 2017, url: "https://doi.org/10.1016/j.econlet.2017.06.011", market: "Bitcoin", families: ["volatility"], takeaway: "Bitcoin volatility needs explicit modeling for risk sizing.", caveat: "Model choice changes forecasts." },
  { id: "p096", title: "An Extreme Value Analysis of Bitcoin Returns", authors: "Gkillas and Katsiampa", year: 2018, url: "https://doi.org/10.1016/j.econlet.2018.09.020", market: "Bitcoin", families: ["volatility", "risk"], takeaway: "Tail-risk discipline is essential in Bitcoin.", caveat: "Extreme-value estimates need enough data." },
  { id: "p097", title: "Datestamping the Bitcoin and Ethereum Bubbles", authors: "Corbet, Lucey, Yarovaya and Baur", year: 2018, url: "https://doi.org/10.1016/j.frl.2017.12.006", market: "Bitcoin and Ethereum", families: ["sentiment", "risk"], takeaway: "Bubble-detection tools can flag unsustainable regimes.", caveat: "Bubble labels are easier after the fact." },
  { id: "p098", title: "Conditional Tail-Risk in Cryptocurrency Markets", authors: "Borri", year: 2019, url: "https://doi.org/10.1016/j.jempfin.2019.04.002", market: "crypto", families: ["risk", "volatility"], takeaway: "Crypto downside tail risk is state-dependent.", caveat: "Tail models are fragile in new regimes." },
  { id: "p099", title: "Tokenomics: Dynamic Adoption and Valuation", authors: "Cong, Li and Wang", year: 2021, url: "https://doi.org/10.1093/rfs/hhaa089", market: "tokens", families: ["onchain", "value"], takeaway: "Network adoption and token design affect value.", caveat: "Project-specific tokenomics may not generalize to BTC." },
  { id: "p100", title: "Cryptocurrencies as an Asset Class?", authors: "Bianchi", year: 2020, url: "https://doi.org/10.1080/14697688.2020.1757855", market: "crypto", families: ["risk", "macro"], takeaway: "Crypto needs asset-class treatment with distinct risk factors.", caveat: "Asset class composition changes quickly." },
] as const

export const PRACTITIONER_SIGNAL_CORPUS: readonly PractitionerSignalMethod[] = [
  { id: "m001", category: "On-chain", method: "Exchange reserve trend", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-reserve", dataRequired: "BTC exchange wallet balances", interpretation: "Falling reserves reduce immediate sell inventory; rising reserves warn sell pressure.", failureMode: "Custody reshuffles and ETF/custodian flows can mask real intent.", priority: "P0" },
  { id: "m002", category: "On-chain", method: "Exchange netflow", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/exchange-flows", dataRequired: "Exchange inflow minus outflow", interpretation: "Negative netflow supports accumulation; positive netflow warns distribution.", failureMode: "Internal exchange wallet moves create false signals.", priority: "P0" },
  { id: "m003", category: "On-chain", method: "Exchange inflow spike", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-inflow-total", dataRequired: "BTC deposited to exchanges", interpretation: "Large inflows often precede selling or volatility.", failureMode: "OTC deposits and collateral transfers are not spot selling.", priority: "P0" },
  { id: "m004", category: "On-chain", method: "Exchange inflow CDD", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/flow-indicator/exchange-inflow-cdd", dataRequired: "Age-weighted exchange inflows", interpretation: "Old coins sent to exchanges increase distribution risk.", failureMode: "Custody migration can look like old-holder selling.", priority: "P1" },
  { id: "m005", category: "On-chain", method: "Miner reserve trend", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/miner-flows/miner-reserve", dataRequired: "Miner wallet balances", interpretation: "Falling miner reserves can indicate miner selling stress.", failureMode: "Mining-pool wallet tagging changes distort the read.", priority: "P1" },
  { id: "m006", category: "On-chain", method: "Coinbase Premium Index", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/market-data/coinbase-premium-index", dataRequired: "Coinbase BTC/USD versus Binance BTC/USDT", interpretation: "Positive premium suggests stronger US spot demand.", failureMode: "Stablecoin peg and base-currency effects can distort premiums.", priority: "P0" },
  { id: "m007", category: "On-chain", method: "Korea Premium Index", source: "CryptoQuant", url: "https://userguide.cryptoquant.com/cryptoquant-metrics/fund-premium/korea-premium-index", dataRequired: "Korean VWAP versus global VWAP", interpretation: "Extreme premium flags local retail FOMO and top risk.", failureMode: "KRW controls and local liquidity shocks dominate.", priority: "P2" },
  { id: "m008", category: "On-chain", method: "Realized price reclaim/loss", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/market-indicator/realized-price", dataRequired: "Realized cap and supply", interpretation: "Price above realized price supports macro recovery; below marks capitulation risk.", failureMode: "Long sideways bear regimes can sit near the level.", priority: "P0" },
  { id: "m009", category: "On-chain", method: "SOPR 1.0 regime", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/sopr/sopr-spent-output-profit-ratio", dataRequired: "Spent output profit ratio", interpretation: "SOPR above 1 means profit-taking; 1.0 support retest confirms bull demand.", failureMode: "Low on-chain settlement activity weakens the signal.", priority: "P0" },
  { id: "m010", category: "On-chain", method: "Adjusted SOPR retest", source: "Glassnode", url: "https://docs.glassnode.com/basic-api/endpoints/pit", dataRequired: "SOPR excluding young outputs", interpretation: "aSOPR reclaim above 1 confirms demand absorbing profitable coins.", failureMode: "Intraday noise and exchange batching distort outputs.", priority: "P1" },
  { id: "m011", category: "On-chain", method: "LTH/STH SOPR ratio", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/market-indicator/sopr-ratio-lth-sopr-sth-sopr/1000", dataRequired: "LTH-SOPR and STH-SOPR", interpretation: "Long-holder profit-taking versus short-holder stress shows cycle rotation.", failureMode: "Cohort thresholds are blunt.", priority: "P1" },
  { id: "m012", category: "On-chain", method: "MVRV ratio zones", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/mvrv/mvrv-ratio", dataRequired: "Market cap and realized cap", interpretation: "Low MVRV marks value; high MVRV marks profit saturation.", failureMode: "ETF-era structure can shift historic bands.", priority: "P0" },
  { id: "m013", category: "On-chain", method: "STH-MVRV fair value", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/mvrv/sth-mvrv", dataRequired: "Short-holder cost basis", interpretation: "STH-MVRV near or below 1 shows short-holder capitulation/support.", failureMode: "Momentum crashes can remain below 1.", priority: "P0" },
  { id: "m014", category: "On-chain", method: "LTH-MVRV overheating", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/mvrv/lth-mvrv", dataRequired: "Long-holder unrealized profit", interpretation: "High LTH-MVRV raises distribution risk; low values support value zones.", failureMode: "Illiquid old coins distort the ratio.", priority: "P1" },
  { id: "m015", category: "On-chain", method: "NUPL regime", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/unrealized-profit-loss/nupl-net-unrealized-profit-loss", dataRequired: "Unrealized profit/loss and market cap", interpretation: "Euphoria zones reduce reward/risk; capitulation zones improve it.", failureMode: "Thresholds drift across cycles.", priority: "P0" },
  { id: "m016", category: "On-chain", method: "HODL Waves age shift", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/age-distribution/hodl-waves", dataRequired: "Supply by coin age", interpretation: "Young supply rising signals distribution/speculation; old supply rising signals accumulation.", failureMode: "Lost coins and custody batching distort cohorts.", priority: "P1" },
  { id: "m017", category: "On-chain", method: "Realized Cap HODL Waves", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/age-distribution/realized-cap-hodl-waves", dataRequired: "Realized value by age band", interpretation: "New money dominating realized value flags late-cycle heat.", failureMode: "ETF/custody movement changes cohorts.", priority: "P1" },
  { id: "m018", category: "On-chain", method: "Dormancy / old coin movement", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/dormancy/average-coin-dormancy", dataRequired: "Coin age of spent outputs", interpretation: "Dormancy spikes mean experienced holders are moving coins.", failureMode: "Wallet consolidation and security moves are noisy.", priority: "P1" },
  { id: "m019", category: "On-chain", method: "Spent Output Age Bands", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/lifespan/spent-output-age-bands-soab", dataRequired: "Spent volume by age band", interpretation: "Old-band spikes near highs warn distribution.", failureMode: "Exchange UTXO management can fake movement.", priority: "P1" },
  { id: "m020", category: "On-chain", method: "Accumulation Trend Score", source: "Glassnode", url: "https://docs.glassnode.com/basic-api/endpoints/indicators", dataRequired: "Entity balance changes", interpretation: "Large entities accumulating supports trend quality.", failureMode: "Entity clustering errors matter.", priority: "P0" },
  { id: "m021", category: "Derivatives", method: "Perp funding extremes", source: "OKX/Binance/Bybit", url: "https://www.okx.com/learn/bitcoin-funding-rates-market-sentiment", dataRequired: "Funding rates", interpretation: "Very positive funding means crowded longs; very negative means crowded shorts.", failureMode: "Strong trends can stay extreme.", priority: "P0" },
  { id: "m022", category: "Derivatives", method: "OI + funding crowding", source: "OKX", url: "https://www.okx.com/en-us/learn/funding-rates-perpetual-futures-strategies", dataRequired: "Open interest and funding", interpretation: "Rising OI plus extreme funding warns liquidation risk.", failureMode: "Hedged basis positions inflate OI.", priority: "P0" },
  { id: "m023", category: "Derivatives", method: "Negative funding squeeze", source: "QCP", url: "https://www.qcpgroup.com/insights/qcp-market-colour-13/", dataRequired: "Funding, OI, spot price", interpretation: "Price rising while funding is negative can fuel a short squeeze.", failureMode: "Spot-led moves can fade quickly.", priority: "P0" },
  { id: "m024", category: "Derivatives", method: "OI compression breakout", source: "Bitcoin Magazine Pro", url: "https://www.bitcoinmagazinepro.com/charts/btc-open-interest/", dataRequired: "Open interest and price range", interpretation: "Rising OI in a tight range stores leverage for a breakout.", failureMode: "Direction is unknown without flow.", priority: "P1" },
  { id: "m025", category: "Derivatives", method: "OI flush reset", source: "K33", url: "https://k33.com/research/archive/articles/all-time-high-perp-oi-450-000", dataRequired: "OI, liquidations, funding", interpretation: "Sharp OI drop after a cascade means cleaner positioning.", failureMode: "Can be early in a bear trend.", priority: "P1" },
  { id: "m026", category: "Derivatives", method: "Annualized futures basis", source: "CF Benchmarks", url: "https://www.cfbenchmarks.com/blog/revisiting-the-bitcoin-basis-how-momentum-sentiment-impact-the-structural-drivers-of-basis-activity", dataRequired: "Futures versus spot price", interpretation: "High basis shows carry/leverage demand; discount shows stress.", failureMode: "ETF basis trades distort the signal.", priority: "P0" },
  { id: "m027", category: "Derivatives", method: "CME vs offshore basis", source: "K33", url: "https://k33.com/research/archive/articles/cmes-front-month-btc-futures-trading-at-sharpest-discount-ever-recorded", dataRequired: "CME and offshore futures basis", interpretation: "CME premium supports institutional demand; discount warns caution.", failureMode: "Calendar rolls and ETF hedging matter.", priority: "P1" },
  { id: "m028", category: "Derivatives", method: "Dated futures term structure", source: "Laevitas", url: "https://www.laevitas.ch/", dataRequired: "Basis across expiries", interpretation: "Contango shows healthy carry; backwardation shows stress.", failureMode: "Illiquid expiries distort the curve.", priority: "P1" },
  { id: "m029", category: "Derivatives", method: "Cross-exchange funding dispersion", source: "Laevitas", url: "https://app.laevitas.ch/assets/perpswaps/BTC/funding", dataRequired: "OI-weighted funding by venue", interpretation: "Wide dispersion flags localized leverage or arbitrage.", failureMode: "Venue outages and latency can dominate.", priority: "P2" },
  { id: "m030", category: "Derivatives", method: "Liquidation cluster distance", source: "CoinGlass", url: "https://www.coinglass.com/FundingRate", dataRequired: "Liquidation estimates and leverage", interpretation: "Nearby clusters can become volatility magnets.", failureMode: "Cluster estimates rely on assumptions.", priority: "P1" },
  { id: "m031", category: "Derivatives", method: "Coin vs stable-margin OI mix", source: "Coinalyze", url: "https://coinalyze.net/bitcoin/open-interest/", dataRequired: "Coin-margined and stable-margined OI", interpretation: "Coin-margin growth adds convex liquidation risk.", failureMode: "Venue coverage can be incomplete.", priority: "P2" },
  { id: "m032", category: "Derivatives", method: "Top-trader long/short divergence", source: "Binance Futures", url: "https://www.binance.com/en/futures/funding-history/perpetual/real-time-funding-rate", dataRequired: "Top-account ratios and price", interpretation: "One-sided top-trader positioning can be contrarian.", failureMode: "Accounts may hedge elsewhere.", priority: "P2" },
  { id: "m033", category: "Stablecoins", method: "Stablecoin Supply Ratio", source: "CryptoQuant", url: "https://userguide.cryptoquant.com/cryptoquant-metrics/stablecoin/stablecoin-supply-ratio", dataRequired: "BTC cap and stablecoin cap", interpretation: "Low/falling SSR means more sidelined buying power.", failureMode: "Stablecoins are used outside trading.", priority: "P0" },
  { id: "m034", category: "Stablecoins", method: "SSR trend oscillator", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/market-indicator/stablecoin-supply-ratio-ssr", dataRequired: "SSR with moving average or z-score", interpretation: "Falling SSR trend supports risk appetite.", failureMode: "Mint/burn timing creates noise.", priority: "P0" },
  { id: "m035", category: "Stablecoins", method: "Stablecoin exchange reserve", source: "CryptoQuant", url: "https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-reserve", dataRequired: "Stablecoin balances on exchanges", interpretation: "Rising exchange stablecoins create dry powder.", failureMode: "May simply be defensive parking.", priority: "P1" },
  { id: "m036", category: "Stablecoins", method: "Stablecoin exchange netflow", source: "CryptoQuant", url: "https://cryptoquant.com/asset/stablecoin/chart/exchange-flows/exchange-netflow-total", dataRequired: "Stablecoin inflow minus outflow", interpretation: "Positive netflow can precede spot buying.", failureMode: "Capital can remain idle.", priority: "P1" },
  { id: "m037", category: "Stablecoins", method: "Aggregate stablecoin supply growth", source: "Coin Metrics", url: "https://www.talos.com/insights/coin-metrics-introduces-aggregated-stablecoin-metrics", dataRequired: "USDT, USDC and other supply", interpretation: "Expanding supply supports liquidity expansion.", failureMode: "Issuer-specific regulation or incentives distort supply.", priority: "P0" },
  { id: "m038", category: "Stablecoins", method: "USDT vs USDC mix", source: "Coin Metrics", url: "https://github.com/coinmetrics/docs-website/blob/master/asset-metrics/asset-metrics-faqs.md", dataRequired: "Stablecoin supply by issuer and chain", interpretation: "USDT-led growth is more crypto-native; USDC-led growth often tracks US/institutional rails.", failureMode: "Issuer campaigns and migrations distort mix.", priority: "P2" },
  { id: "m039", category: "Stablecoins", method: "Stablecoin depeg pressure", source: "Kaiko", url: "https://www.kaiko.com/resources/defining-depegs-a-new-metric-for-stablecoin-stability", dataRequired: "Stablecoin prices and liquidity", interpretation: "Depegs warn liquidity or contagion stress.", failureMode: "Tiny venues exaggerate prints.", priority: "P1" },
  { id: "m040", category: "Liquidity", method: "1%-2% market depth", source: "Kaiko", url: "https://www.kaiko.com/resources/understanding-centralized-exchange-liquidity-data", dataRequired: "Order-book depth", interpretation: "Rising depth confirms healthier execution and trend capacity.", failureMode: "Spoofing and fast quote pull reduce reliability.", priority: "P0" },
  { id: "m041", category: "Liquidity", method: "Bid-ask spread", source: "Kaiko", url: "https://www.kaiko.com/resources/a-cheatsheet-for-bid-ask-spreads", dataRequired: "Best bid and ask", interpretation: "Widening spreads mean fragile liquidity.", failureMode: "News windows and maintenance create temporary spikes.", priority: "P0" },
  { id: "m042", category: "Liquidity", method: "Slippage simulation", source: "Kaiko", url: "https://docs.kaiko.com/rest-api/data-feeds/level-1-and-level-2-data/level-2-aggregations/raw-order-book-snapshot/raw-order-book-snapshot-%2B-market-depth-bid-ask-spread-and-price-slippage", dataRequired: "Order-book snapshots", interpretation: "Higher simulated slippage means reduce trade size.", failureMode: "Hidden liquidity is not captured.", priority: "P0" },
  { id: "m043", category: "ETF/funds", method: "Daily US BTC ETF net flow", source: "Farside", url: "https://farside.co.uk/btc/", dataRequired: "Daily ETF flows", interpretation: "Large inflows show spot demand; outflows add pressure.", failureMode: "T+1 reporting and basis hedges lag price.", priority: "P0" },
  { id: "m044", category: "ETF/funds", method: "ETF flow streak", source: "Farside", url: "https://farside.co.uk/bitcoin-etf-flow-all-data/", dataRequired: "Rolling 5/10-day ETF flows", interpretation: "Multi-day inflow streak supports trend persistence.", failureMode: "Choppy regimes whipsaw.", priority: "P0" },
  { id: "m045", category: "ETF/funds", method: "Cumulative ETF flow trend", source: "Farside", url: "https://farside.co.uk/bitcoin-etf-flow-all-data/", dataRequired: "Cumulative flows by issuer", interpretation: "Rising cumulative flow shows structural demand.", failureMode: "Impact may already be priced.", priority: "P0" },
  { id: "m046", category: "ETF/funds", method: "Issuer breadth", source: "Farside", url: "https://farside.co.uk/btc/", dataRequired: "Issuer-level ETF flows", interpretation: "Broad issuer inflows are stronger than one-fund flow.", failureMode: "Fund rotations net out.", priority: "P1" },
  { id: "m047", category: "ETF/funds", method: "GBTC outflow drag", source: "Farside", url: "https://farside.co.uk/btc/", dataRequired: "GBTC outflows versus peers", interpretation: "GBTC-heavy outflows can cap BTC demand.", failureMode: "Less relevant as overhang fades.", priority: "P1" },
  { id: "m048", category: "ETF/funds", method: "ETF flow price-impact lag", source: "SSRN", url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6592830", dataRequired: "ETF flows and BTC returns", interpretation: "Lagged large flows may affect returns after reporting.", failureMode: "Structural relation may decay.", priority: "P2" },
  { id: "m049", category: "ETF/funds", method: "Weekly digital asset fund flows", source: "CoinShares", url: "https://coinshares.com/insights/research-data/", dataRequired: "Weekly fund inflow/outflow", interpretation: "Shows institutional appetite by asset and region.", failureMode: "Weekly cadence lags fast markets.", priority: "P1" },
  { id: "m050", category: "ETF/funds", method: "ETF/CME basis unwind", source: "CME", url: "https://www.cmegroup.com/openmarkets/equity-index/2025/Spot-ETFs-Give-Rise-to-Crypto-Basis-Trading.html", dataRequired: "ETF holdings, CME OI, basis", interpretation: "ETF long plus CME short unwind can pressure both legs.", failureMode: "Real hedge books are hard to identify.", priority: "P2" },
  { id: "m051", category: "Macro", method: "Dollar liquidity index", source: "Arthur Hayes / BitMEX", url: "https://www.bitmex.com/blog/teach-me-daddy", dataRequired: "Fed balance sheet, TGA, RRP", interpretation: "Expanding USD liquidity supports BTC beta.", failureMode: "Credit allocation may bypass crypto.", priority: "P0" },
  { id: "m052", category: "Macro", method: "Fed balance sheet trend", source: "FRED", url: "https://fred.stlouisfed.org/series/WALCL", dataRequired: "WALCL", interpretation: "QE or slower QT is a liquidity tailwind.", failureMode: "Crypto-native shocks can dominate.", priority: "P0" },
  { id: "m053", category: "Macro", method: "TGA drain/refill", source: "FRED", url: "https://fred.stlouisfed.org/series/WTREGEN", dataRequired: "Treasury General Account", interpretation: "TGA drain injects liquidity; refill drains it.", failureMode: "Bill issuance can be absorbed by money funds.", priority: "P1" },
  { id: "m054", category: "Macro", method: "Reverse repo drawdown", source: "FRED", url: "https://fred.stlouisfed.org/series/RRPONTSYD", dataRequired: "Reverse repo usage", interpretation: "RRP falling can offset QT liquidity drain.", failureMode: "Usefulness fades as RRP exhausts.", priority: "P1" },
  { id: "m055", category: "Macro", method: "M2/global liquidity", source: "Lyn Alden", url: "https://www.lynalden.com/bitcoin-a-global-liquidity-barometer/", dataRequired: "Global M2 and liquidity proxies", interpretation: "Liquidity expansion is a BTC tailwind; contraction is a headwind.", failureMode: "Correlation changes by regime.", priority: "P0" },
  { id: "m056", category: "Macro", method: "Real yield trend", source: "FRED/Fidelity", url: "https://fred.stlouisfed.org/series/DFII10", dataRequired: "10Y real yield", interpretation: "Rising real yields pressure BTC multiples.", failureMode: "Inflation-hedge narrative periods can override.", priority: "P1" },
  { id: "m057", category: "Macro", method: "Broad dollar/DXY proxy", source: "FRED", url: "https://fred.stlouisfed.org/series/DTWEXBGS", dataRequired: "Trade-weighted dollar", interpretation: "Strong dollar usually tightens crypto liquidity.", failureMode: "Non-US demand shocks can dominate.", priority: "P1" },
  { id: "m058", category: "Macro", method: "FOMC/CPI surprise filter", source: "New York Fed", url: "https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr1052.pdf?sc_lang=en", dataRequired: "Event calendar and intraday BTC", interpretation: "Reduce risk before high-volatility macro releases.", failureMode: "BTC may ignore macro in crypto-native crises.", priority: "P1" },
  { id: "m059", category: "Macro", method: "BTC/Nasdaq risk regime", source: "Fidelity Digital Assets", url: "https://www.fidelitydigitalassets.com/research-and-insights/bitcoins-potential-leading-macro-asset", dataRequired: "Rolling BTC/Nasdaq correlation", interpretation: "High correlation means treat BTC as high-beta tech.", failureMode: "Decoupling happens during crypto catalysts.", priority: "P1" },
  { id: "m060", category: "Macro", method: "Oil/yield shock filter", source: "BitMEX / Arthur Hayes", url: "https://www.bitmex.com/blog", dataRequired: "Oil, yields, USD/JPY and rates", interpretation: "Energy/yield spikes tighten risk appetite.", failureMode: "Narrative-heavy and low precision.", priority: "P2" },
  { id: "m061", category: "Sentiment", method: "Crypto Fear & Greed extreme", source: "Alternative.me", url: "https://alternative.me/crypto/fear-and-greed-index/", dataRequired: "Index level", interpretation: "Extreme fear is contrarian value; greed is trim-risk territory.", failureMode: "Strong trends stay extreme.", priority: "P0" },
  { id: "m062", category: "Sentiment", method: "Fear & Greed momentum", source: "Alternative.me API", url: "https://alternative.me/crypto/api/", dataRequired: "Daily index history", interpretation: "Fear-to-neutral recovery confirms a risk bid.", failureMode: "Methodology changes can shift levels.", priority: "P1" },
  { id: "m063", category: "Sentiment", method: "Social volume spike", source: "Santiment", url: "https://academy.santiment.net/metrics/social-volume/", dataRequired: "Social mention count", interpretation: "Spike during rally warns local top and FOMO risk.", failureMode: "Real news can justify spikes.", priority: "P1" },
  { id: "m064", category: "Sentiment", method: "Social dominance", source: "Santiment", url: "https://academy.santiment.net/metrics/social-dominance/", dataRequired: "Asset mentions versus top assets", interpretation: "BTC dominance spike shows crowd focus; neglect plus oversold can be opportunity.", failureMode: "Meme/news cycles distort dominance.", priority: "P1" },
  { id: "m065", category: "Sentiment", method: "Weighted sentiment divergence", source: "Santiment", url: "https://academy.santiment.net/metrics/sentiment-metrics/weighted-sentiment-metrics/", dataRequired: "Sentiment balance and social volume", interpretation: "Price up with sentiment falling can be a healthy wall of worry.", failureMode: "NLP errors and sarcasm.", priority: "P2" },
  { id: "m066", category: "Sentiment", method: "Google Trends attention", source: "Google", url: "https://trends.google.com/trends/", dataRequired: "Search interest for Bitcoin", interpretation: "Peak search often marks retail late-cycle; low search can mean neglect.", failureMode: "Search behavior changed post-ETF.", priority: "P1" },
  { id: "m067", category: "Sentiment", method: "Narrative topic rotation", source: "Santiment", url: "https://santiment.github.io/articles/", dataRequired: "Trending words and topics", interpretation: "New narratives with rising mentions can lead sector rotation.", failureMode: "Spam and bot campaigns.", priority: "P2" },
  { id: "m068", category: "Sentiment", method: "Whale transaction count", source: "Santiment", url: "https://academy.santiment.net/metrics/whale-transaction-count/", dataRequired: "Large transaction count", interpretation: "Whale spikes near extremes warn volatility or reversal.", failureMode: "Transfers may be non-trading.", priority: "P1" },
  { id: "m069", category: "Order flow", method: "CVD divergence", source: "Binance / TradingRiot", url: "https://www.binance.com/en/square/post/274181", dataRequired: "Aggressor buy/sell volume", interpretation: "Price up with falling CVD is weak; price down with rising CVD suggests absorption.", failureMode: "Venue-specific distortions.", priority: "P0" },
  { id: "m070", category: "Order flow", method: "Taker buy/sell ratio", source: "Binance Futures", url: "https://www.binance.com/en/futures/funding-history/perpetual/real-time-funding-rate", dataRequired: "Taker buy volume / sell volume", interpretation: "Aggressive buy imbalance confirms momentum.", failureMode: "Wash trading and venue skew.", priority: "P1" },
  { id: "m071", category: "Order flow", method: "Order book imbalance", source: "Amberdata", url: "https://blog.amberdata.io/the-rhythm-of-liquidity-temporal-patterns-in-market-depth", dataRequired: "Bid versus ask depth near mid", interpretation: "Bid-heavy books support bounces; ask-heavy books cap rallies.", failureMode: "Spoofing and quote pull.", priority: "P1" },
  { id: "m072", category: "Order flow", method: "Bid wall proximity", source: "Kaiko", url: "https://docs.kaiko.com/rest-api/data-feeds/level-1-and-level-2-data/level-2-aggregations/raw-order-book-snapshot/raw-order-book-snapshot-%2B-market-depth-bid-ask-spread-and-price-slippage", dataRequired: "L2 book depth", interpretation: "Large nearby bid clusters can act as support or magnets.", failureMode: "Walls can vanish.", priority: "P1" },
  { id: "m073", category: "Order flow", method: "Ask wall rejection", source: "Kaiko", url: "https://www.kaiko.com/resources/moving-markets-liquidity-and-large-sell-orders", dataRequired: "L2 ask depth and market orders", interpretation: "Heavy ask depth plus weak taker buy raises rejection risk.", failureMode: "Breakouts consume walls.", priority: "P1" },
  { id: "m074", category: "Order flow", method: "IOMAP support/resistance", source: "IntoTheBlock / Sentora", url: "https://coinmarketcap.com/academy/article/key-metrics-pointing-to-where-crypto-may-be-heading-next-a-data-perspective-by-intotheblock", dataRequired: "Address cost-basis clusters", interpretation: "Large cost-basis clusters near price can act as support/resistance.", failureMode: "Addresses are not equal to traders.", priority: "P1" },
  { id: "m075", category: "Order flow", method: "Large Holder Netflow", source: "IntoTheBlock / Sentora", url: "https://sentora.com/research/articles/bitcoin-on-chain-analysis-correlations-on-chain-profit-and-large-holders", dataRequired: "Large-holder inflow/outflow", interpretation: "Whale net accumulation supports trend quality.", failureMode: "Custody reshuffles distort flows.", priority: "P1" },
  { id: "m076", category: "Order flow", method: "Session liquidity timing", source: "Amberdata", url: "https://blog.amberdata.io/the-rhythm-of-liquidity-temporal-patterns-in-market-depth", dataRequired: "Depth by hour and day", interpretation: "Trade when depth is high; avoid thin windows.", failureMode: "Event risk overrides seasonality.", priority: "P0" },
  { id: "m077", category: "Options/vol", method: "IV vs RV / VRP", source: "Deribit", url: "https://insights.deribit.com/industry/bitcoin-options-finding-edge-in-four-years-of-volatility-regimes/", dataRequired: "Implied and realized volatility", interpretation: "IV far above RV favors premium selling; RV above IV favors long vol.", failureMode: "Jump risk destroys carry.", priority: "P1" },
  { id: "m078", category: "Options/vol", method: "ATM IV regime", source: "Deribit", url: "https://insights.deribit.com/industry/crypto-derivatives-analytics-report-week-8-2026/", dataRequired: "30d/60d/90d ATM IV", interpretation: "Low IV means cheap optionality; high IV means stress or rich premium.", failureMode: "Low volatility can stay low.", priority: "P1" },
  { id: "m079", category: "Options/vol", method: "25-delta risk reversal", source: "CME/Deribit", url: "https://www.cmegroup.com/articles/2026/bitcoin-options-volatility-spikes-and-recovery-signals.html", dataRequired: "25d call IV minus put IV", interpretation: "Negative skew means downside hedge demand; positive skew means upside chase.", failureMode: "Structural hedging baselines shift.", priority: "P0" },
  { id: "m080", category: "Options/vol", method: "IV term structure", source: "Amberdata", url: "https://blog.amberdata.io/utilizing-volatility-term-structure-changes-to-spot-regime-shifts", dataRequired: "IV by expiry", interpretation: "Backwardation means stress/event; contango means normal carry.", failureMode: "Event calendars explain some shape.", priority: "P1" },
  { id: "m081", category: "Options/vol", method: "Skew term structure", source: "Amberdata", url: "https://blog.amberdata.io/crypto-options-front-end-skews-shift-to-put-preference", dataRequired: "Skew by expiry", interpretation: "Front-end put skew shows near-term fear; back-end call skew shows structural upside.", failureMode: "Illiquid wings.", priority: "P1" },
  { id: "m082", category: "Options/vol", method: "Put/call flow ratio", source: "Amberdata", url: "https://www.amberdata.io/ad-derivatives", dataRequired: "Option volume/OI by puts/calls", interpretation: "Put surge flags hedging/fear; call surge flags upside speculation.", failureMode: "Spreads and hedges are hard to classify.", priority: "P2" },
  { id: "m083", category: "Options/vol", method: "Max pain / expiry magnet", source: "CoinDesk / Deribit", url: "https://www.coindesk.com/markets/2026/04/20/here-s-how-bitcoin-s-usd7-9-billion-options-expiry-impact-prices", dataRequired: "Options OI by strike", interpretation: "Price can pin near max pain into expiry.", failureMode: "Strong spot trend overwhelms.", priority: "P2" },
  { id: "m084", category: "Options/vol", method: "Gamma exposure / gamma flip", source: "Laevitas", url: "https://app.laevitas.ch/assets/options/gex/btc/deribit", dataRequired: "Options OI and greeks", interpretation: "Positive gamma pins; negative gamma amplifies moves.", failureMode: "Dealer positioning is inferred.", priority: "P2" },
  { id: "m085", category: "Options/vol", method: "Dealer gamma expiry release", source: "QCP", url: "https://www.qcpgroup.com/insights/qcp-market-colour-7/", dataRequired: "Gamma, expiry, spot", interpretation: "Long-gamma support can vanish after expiry.", failureMode: "Needs accurate dealer model.", priority: "P2" },
  { id: "m086", category: "Options/vol", method: "Options block-flow impulse", source: "Amberdata / Deribit", url: "https://insights.deribit.com/industry/decoding-option-flows-q2-2023/", dataRequired: "Block trades, strikes, maturities", interpretation: "Large directional structures reveal institutional bias.", failureMode: "Notional may be hedged.", priority: "P2" },
  { id: "m087", category: "Cycle/valuation", method: "MVRV Z-score bands", source: "Glassnode / BM Pro", url: "https://docs.glassnode.com/further-information/metric-guides/mvrv/mvrv-z-score", dataRequired: "Market cap, realized cap, standard deviation", interpretation: "High z-score overheats; low/negative z-score signals value.", failureMode: "Fixed bands fail after structural changes.", priority: "P0" },
  { id: "m088", category: "Cycle/valuation", method: "Puell Multiple", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/coin-issuance/puell-multiple", dataRequired: "Miner issuance USD / 365d average", interpretation: "Low values suggest miner capitulation; high values suggest overheated revenue.", failureMode: "Halving and fee regime shifts.", priority: "P1" },
  { id: "m089", category: "Cycle/valuation", method: "Reserve Risk", source: "Glassnode", url: "https://docs.glassnode.com/further-information/metric-guides/coin-days-destroyed/reserve-risk", dataRequired: "Price and HODL bank", interpretation: "Low reserve risk improves long-term reward/risk.", failureMode: "Needs multi-year horizon.", priority: "P1" },
  { id: "m090", category: "Cycle/valuation", method: "RHODL Ratio", source: "Bitcoin Magazine Pro", url: "https://www.bitcoinmagazinepro.com/charts/rhodl-ratio/", dataRequired: "Realized HODL age bands", interpretation: "Very high ratio flags young-money euphoria; low ratio supports bottoming.", failureMode: "Market structure changes shift levels.", priority: "P1" },
  { id: "m091", category: "Cycle/valuation", method: "Pi Cycle Top", source: "Bitcoin Magazine Pro", url: "https://www.bitcoinmagazinepro.com/charts/pi-cycle-top-indicator/", dataRequired: "111DMA and 350DMA x2", interpretation: "Cross warns cycle-top heat.", failureMode: "Can fail or miss peaks.", priority: "P2" },
  { id: "m092", category: "Cycle/valuation", method: "Stock-to-flow deflection", source: "PlanB / BM Pro", url: "https://www.bitcoinmagazinepro.com/charts/stock-to-flow-model/", dataRequired: "Supply schedule and price", interpretation: "Price far below model is a rough undervaluation reference.", failureMode: "Demand and liquidity are ignored.", priority: "P2" },
  { id: "m093", category: "Cycle/valuation", method: "NVT/NVTS", source: "Glassnode / Willy Woo", url: "https://docs.glassnode.com/further-information/metric-guides/nvt/nvt-ratio", dataRequired: "Market cap and transfer volume", interpretation: "High NVT means value ahead of usage; low NVT means network activity support.", failureMode: "Exchange, Lightning, and off-chain volume distort transfer value.", priority: "P1" },
  { id: "m094", category: "Risk", method: "Volatility-targeted sizing", source: "Binance Academy", url: "https://www.binance.com/en/academy/articles/a-beginners-guide-to-understanding-risk-management", dataRequired: "Realized volatility or ATR and account equity", interpretation: "Reduce size when volatility rises; increase only when volatility falls.", failureMode: "Vol jumps faster than rebalance.", priority: "P0" },
  { id: "m095", category: "Risk", method: "Fixed fractional risk", source: "Binance Academy", url: "https://www.binance.com/en/academy/articles/five-risk-management-strategies", dataRequired: "Equity and stop distance", interpretation: "Risk a fixed small percentage per trade.", failureMode: "Gap moves exceed stops.", priority: "P0" },
  { id: "m096", category: "Risk", method: "Stop-loss by invalidation", source: "OKX", url: "https://www.okx.com/en-us/learn/what-is-take-profit-and-stop-loss", dataRequired: "Entry and invalidation level", interpretation: "Size from stop distance, not conviction.", failureMode: "Thin-book stop hunts.", priority: "P0" },
  { id: "m097", category: "Risk", method: "Leverage liquidation buffer", source: "OKX", url: "https://www.okx.com/en-us/learn/leverage-trading-risks-rewards-strategies", dataRequired: "Liquidation price, margin and volatility", interpretation: "Keep liquidation far beyond expected move.", failureMode: "Exchange auto-deleveraging and gaps.", priority: "P0" },
  { id: "m098", category: "Risk", method: "Portfolio drawdown kill switch", source: "Binance Academy", url: "https://www.binance.com/en/academy/articles/a-beginners-guide-to-understanding-risk-management", dataRequired: "Equity curve and max drawdown", interpretation: "Halt or reduce risk after threshold loss.", failureMode: "Can pause during the best rebound.", priority: "P1" },
  { id: "m099", category: "Risk", method: "Hedge spot with CME futures/options", source: "CME", url: "https://www.cmegroup.com/markets/cryptocurrencies/bitcoin/bitcoin.html", dataRequired: "Spot exposure and futures/options", interpretation: "Hedge downside without selling spot.", failureMode: "Basis and margin risks.", priority: "P1" },
  { id: "m100", category: "Risk", method: "Cash/stablecoin reserve rule", source: "Binance Academy", url: "https://www.binance.com/en/academy/articles/a-beginners-guide-to-understanding-risk-management", dataRequired: "Portfolio allocation and volatility regime", interpretation: "Keep dry powder; raise cash in high-risk regimes.", failureMode: "Opportunity cost during strong trends.", priority: "P0" },
] as const

export const SIGNAL_LAYERS: readonly SignalLayer[] = [
  {
    id: "price-confirmation",
    title: "Price, trend, and breadth",
    description: "Start with price because every other signal can be early. Use 7D/30D/90D momentum, drawdown, realized volatility, breadth, and cross-asset confirmation.",
    primaryFamilies: ["trend", "momentum", "volatility"],
    dataSources: ["OKX", "Yahoo Finance", "FRED"],
    actionRule: "Trade with the trend only when momentum, volume, and volatility are not contradicting each other.",
  },
  {
    id: "liquidity-flow",
    title: "Liquidity and flow",
    description: "Confirm whether new capital can support the setup: stablecoin supply, ETF/fund flows, M2, dollar liquidity, exchange reserves, and spot premiums.",
    primaryFamilies: ["liquidity", "macro", "onchain"],
    dataSources: ["DefiLlama", "Farside", "CoinShares", "FRED", "CryptoQuant"],
    actionRule: "Raise confidence when flow expands with price; downgrade rallies when price rises on shrinking liquidity.",
  },
  {
    id: "leverage-crowding",
    title: "Derivatives and crowding",
    description: "Detect whether a move is spot-led or leverage-led using funding, basis, OI, liquidations, long/short ratios, and options skew.",
    primaryFamilies: ["positioning", "carry", "options"],
    dataSources: ["OKX", "Deribit", "CME", "CoinGlass", "Laevitas"],
    actionRule: "High funding plus rising OI is not confirmation; it is a warning to reduce leverage or wait for a flush.",
  },
  {
    id: "valuation-cycle",
    title: "Valuation and cycle position",
    description: "Use slow anchors such as MVRV, realized price, miner cost, NUPL, Puell, value/profitability, and factor valuation.",
    primaryFamilies: ["value", "quality", "onchain"],
    dataSources: ["Glassnode", "Coin Metrics", "Blockchain.info", "mempool.space", "SEC EDGAR"],
    actionRule: "Treat valuation as zone selection; require faster signals for timing.",
  },
  {
    id: "sentiment-event",
    title: "Sentiment and event risk",
    description: "Track news, filings, macro calendars, Fear & Greed, social volume, search attention, whale events, and ETF reporting lags.",
    primaryFamilies: ["sentiment", "event"],
    dataSources: ["Alternative.me", "Santiment", "SEC EDGAR", "NY Fed", "RSS feeds"],
    actionRule: "Use sentiment extremes contrarily only when price and leverage confirm exhaustion.",
  },
  {
    id: "risk-execution",
    title: "Risk, sizing, and execution",
    description: "A signal is useful only after sizing. Use volatility targeting, invalidation stops, drawdown kill switches, slippage, depth, and liquidation buffers.",
    primaryFamilies: ["risk", "microstructure"],
    dataSources: ["Kaiko", "Amberdata", "OKX", "CME"],
    actionRule: "No signal bypasses risk: size from volatility and invalidation first, then decide direction.",
  },
] as const

export const CORE_SOURCE_GROUPS: readonly SourceGroup[] = [
  { id: "okx", title: "OKX public market, Rubik, and derivatives APIs", status: "wired", url: "https://www.okx.com/docs-v5/en/", useCase: "Perp candles, OI, funding, basis, long/short ratios, taker flow, and order-book signals." },
  { id: "fred", title: "FRED series observations", status: "wired", url: "https://fred.stlouisfed.org/docs/api/fred/series_observations.html", useCase: "Rates, inflation, credit, liquidity, dollar, and macro regime data." },
  { id: "yahoo", title: "Yahoo Finance chart/quote endpoints", status: "wired", url: "https://finance.yahoo.com/", useCase: "Equity index, ETF, FX, commodity, and stock proxy coverage." },
  { id: "defillama", title: "DefiLlama stablecoin and TVL data", status: "wired", url: "https://defillama.com/", useCase: "Stablecoin liquidity, DeFi TVL, and crypto-native flow context." },
  { id: "blockchain-mempool", title: "Blockchain.info and mempool.space", status: "wired", url: "https://www.blockchain.com/explorer/api/charts_api", useCase: "BTC price history, network activity, hashrate, fees, and miner-cost modeling." },
  { id: "deribit", title: "Deribit options data", status: "wired", url: "https://docs.deribit.com/", useCase: "DVOL, options OI, max-pain style expiry surfaces, and volatility regimes." },
  { id: "glassnode", title: "Glassnode metric guides/API", status: "planned", url: "https://docs.glassnode.com/", useCase: "MVRV, SOPR, NUPL, HODL waves, Puell, Reserve Risk, and accumulation signals." },
  { id: "cryptoquant", title: "CryptoQuant BTC market/on-chain metrics", status: "planned", url: "https://cryptoquant.com/asset/btc/summary", useCase: "Exchange flows, reserves, Coinbase premium, miner flows, SSR, and cohort ratios." },
  { id: "coinmetrics", title: "Coin Metrics network and market data", status: "planned", url: "https://docs.coinmetrics.io/", useCase: "Realized cap, stablecoin aggregates, supply, network activity, and market reference rates." },
  { id: "kaiko", title: "Kaiko market depth and liquidity feeds", status: "research", url: "https://docs.kaiko.com/", useCase: "Bid-ask spreads, 1%-2% market depth, slippage, and venue liquidity quality." },
  { id: "farside-coinshares", title: "Farside and CoinShares flow reports", status: "research", url: "https://farside.co.uk/btc/", useCase: "Daily BTC ETF flows, issuer breadth, GBTC drag, and weekly fund-flow confirmation." },
  { id: "sec-cftc", title: "SEC EDGAR and CFTC COT", status: "planned", url: "https://data.sec.gov/", useCase: "Filings, company facts, insider events, and futures positioning for stock/macro signals." },
] as const

const REVIEWED_EQUITY_MACRO_PAPER_COUNT = 75
const REVIEWED_CRYPTO_PAPER_COUNT = 61

export const RESEARCH_CORPUS_STATS = {
  paperCount: REVIEWED_EQUITY_MACRO_PAPER_COUNT + REVIEWED_CRYPTO_PAPER_COUNT,
  detailedPaperCount: PAPER_RESEARCH_CORPUS.length,
  equityMacroPaperCount: REVIEWED_EQUITY_MACRO_PAPER_COUNT,
  cryptoPaperCount: REVIEWED_CRYPTO_PAPER_COUNT,
  practitionerMethodCount: PRACTITIONER_SIGNAL_CORPUS.length,
  p0PractitionerMethodCount: PRACTITIONER_SIGNAL_CORPUS.filter((method) => method.priority === "P0").length,
  signalLayerCount: SIGNAL_LAYERS.length,
  sourceGroupCount: CORE_SOURCE_GROUPS.length,
} as const

export function getTopPractitionerMethods(limit: number): PractitionerSignalMethod[] {
  const priorityRank: Record<PractitionerPriority, number> = { P0: 0, P1: 1, P2: 2 }
  return [...PRACTITIONER_SIGNAL_CORPUS]
    .sort((left, right) => {
      const rankDelta = priorityRank[left.priority] - priorityRank[right.priority]
      if (rankDelta !== 0) return rankDelta
      return left.id.localeCompare(right.id)
    })
    .slice(0, limit)
}

export function getPapersByFamily(family: SignalFamily, limit: number): ResearchPaper[] {
  return PAPER_RESEARCH_CORPUS.filter((paper) => paper.families.includes(family)).slice(0, limit)
}
