import type { DiscoverResponse } from "./types"

const snapshotAt = Date.UTC(2026, 6, 28, 0, 0, 0)

export const STATIC_DISCOVER_RESPONSE: DiscoverResponse = {
  updatedAt: snapshotAt,
  nextUpdateAt: snapshotAt,
  minAnnualizedYieldPct: 10,
  riskPolicy: "Static first-release screen while the live scanner deployment is unavailable; verify every quote in your broker before trading.",
  treasuryBillProxyRatePct: 3.8,
  candidates: [
    {
      symbol: "XLK",
      name: "Technology Select Sector SPDR",
      assetType: "ETF",
      sector: "Technology",
      strategy: "cash_secured_put",
      strategyLabel: "Sell cash-secured put",
      price: 174,
      strike: 160,
      expirationDate: "2026-09-18",
      daysToExpiration: 53,
      premiumEstimate: 3.7,
      annualizedYieldPct: 15.9,
      bufferPct: 6.8,
      breakeven: 156.3,
      realizedVolatilityPct: 25.1,
      maxDrawdownPct: 16.2,
      trendScore: 72,
      riskScore: 80,
      riskBand: "low",
      confidence: "medium",
      reasons: [
        "15.9% delayed-chain bid annualized option income clears the 10% first-pass hurdle.",
        "6.8% downside buffer before the selected strike is reached.",
        "Sector ETF exposure keeps single-company event risk lower than a single stock.",
        "One-year realized volatility and drawdown remain inside the first-release risk gate.",
      ],
      cautions: [
        "Confirm executable bid/ask in your broker before trading.",
        "Size each contract against the full 100-share cash obligation.",
        "Assignment means buying shares at strike even if the market falls further.",
      ],
      data: {
        priceSource: "Static fallback snapshot",
        premiumSource: "live_chain",
        premiumSourceLabel: "Delayed option-chain snapshot",
        optionSymbol: "XLK260918P00160000",
        optionBid: 3.7,
        optionAsk: 4.35,
        optionVolume: 31,
        optionOpenInterest: 2862,
        optionSpreadPct: 16.1,
        optionSourceUrl: "https://cdn.cboe.com/api/global/delayed_quotes/options/XLK.json",
        optionQuoteTime: snapshotAt,
        asOf: snapshotAt,
      },
    },
    {
      symbol: "AAPL",
      name: "Apple",
      assetType: "Stock",
      sector: "Consumer technology",
      strategy: "cash_secured_put",
      strategyLabel: "Sell cash-secured put",
      price: 336,
      strike: 310,
      expirationDate: "2026-09-04",
      daysToExpiration: 39,
      premiumEstimate: 3.8,
      annualizedYieldPct: 11.5,
      bufferPct: 7.8,
      breakeven: 306.2,
      realizedVolatilityPct: 25,
      maxDrawdownPct: 13.8,
      trendScore: 74,
      riskScore: 82,
      riskBand: "low",
      confidence: "medium",
      reasons: [
        "11.5% annualized option income clears the 10% first-pass hurdle.",
        "7.8% downside buffer before the selected strike is reached.",
        "Mega-cap liquidity and options depth reduce execution friction versus smaller names.",
        "Historical drawdown is moderate for an equity-option income setup.",
      ],
      cautions: [
        "Single-stock assignments can gap on earnings, guidance, regulation, or product news.",
        "Confirm ex-dividend and earnings dates before opening the trade.",
        "Cash-secured puts still carry full downside below breakeven.",
      ],
      data: {
        priceSource: "Static fallback snapshot",
        premiumSource: "live_chain",
        premiumSourceLabel: "Delayed option-chain snapshot",
        optionSymbol: "AAPL260904P00310000",
        optionBid: 3.8,
        optionAsk: 4.25,
        optionVolume: 64,
        optionOpenInterest: 42,
        optionSpreadPct: 11.2,
        optionSourceUrl: "https://cdn.cboe.com/api/global/delayed_quotes/options/AAPL.json",
        optionQuoteTime: snapshotAt,
        asOf: snapshotAt,
      },
    },
    {
      symbol: "AAPL",
      name: "Apple",
      assetType: "Stock",
      sector: "Consumer technology",
      strategy: "covered_call",
      strategyLabel: "Sell covered call",
      price: 336,
      strike: 360,
      expirationDate: "2026-09-04",
      daysToExpiration: 39,
      premiumEstimate: 4.05,
      annualizedYieldPct: 11.3,
      bufferPct: 7.6,
      breakeven: 331.95,
      realizedVolatilityPct: 25,
      maxDrawdownPct: 13.8,
      trendScore: 74,
      riskScore: 82,
      riskBand: "low",
      confidence: "medium",
      reasons: [
        "11.3% annualized option income clears the 10% first-pass hurdle.",
        "7.6% upside buffer before the selected strike is reached.",
        "Mega-cap liquidity and options depth support repeatable execution checks.",
        "Risk score remains high enough that premium is not the only reason.",
      ],
      cautions: [
        "Covered calls cap upside above strike while stock downside remains.",
        "Confirm executable bid/ask in your broker before trading.",
        "Avoid selling through events where you do not accept capped upside.",
      ],
      data: {
        priceSource: "Static fallback snapshot",
        premiumSource: "live_chain",
        premiumSourceLabel: "Delayed option-chain snapshot",
        optionSymbol: "AAPL260904C00360000",
        optionBid: 4.05,
        optionAsk: 4.4,
        optionVolume: 34,
        optionOpenInterest: 59,
        optionSpreadPct: 8.3,
        optionSourceUrl: "https://cdn.cboe.com/api/global/delayed_quotes/options/AAPL.json",
        optionQuoteTime: snapshotAt,
        asOf: snapshotAt,
      },
    },
    {
      symbol: "NVDA",
      name: "Nvidia",
      assetType: "Stock",
      sector: "Semiconductors",
      strategy: "covered_call",
      strategyLabel: "Sell covered call",
      price: 196,
      strike: 210,
      expirationDate: "2026-09-04",
      daysToExpiration: 39,
      premiumEstimate: 6.55,
      annualizedYieldPct: 31.2,
      bufferPct: 9,
      breakeven: 189.45,
      realizedVolatilityPct: 36.4,
      maxDrawdownPct: 20.2,
      trendScore: 68,
      riskScore: 65,
      riskBand: "moderate",
      confidence: "medium",
      reasons: [
        "High option premium clears the 10% annualized screen with a meaningful upside buffer.",
        "Large-cap liquidity and active options markets support execution checks.",
        "Risk score remains above the first-release minimum despite higher volatility.",
        "Best suited for holders already willing to trim shares above the strike.",
      ],
      cautions: [
        "Semiconductor volatility is materially higher than cash-like assets.",
        "Covered calls can underperform badly in fast upside moves.",
        "Confirm earnings dates and position sizing before trading.",
      ],
      data: {
        priceSource: "Static fallback snapshot",
        premiumSource: "live_chain",
        premiumSourceLabel: "Delayed option-chain snapshot",
        optionSymbol: "NVDA260904C00210000",
        optionBid: 6.55,
        optionAsk: 6.75,
        optionVolume: 429,
        optionOpenInterest: 260,
        optionSpreadPct: 3,
        optionSourceUrl: "https://cdn.cboe.com/api/global/delayed_quotes/options/NVDA.json",
        optionQuoteTime: snapshotAt,
        asOf: snapshotAt,
      },
    },
  ],
  stableYieldAssets: [
    {
      symbol: "SGOV",
      name: "iShares 0-3 Month Treasury Bond ETF",
      category: "Treasury bill ETF",
      issuer: "iShares",
      price: 100.65,
      changePct: 0.01,
      estimatedAnnualYieldPct: 3.72,
      realizedVolatilityPct: 1.07,
      maxDrawdownPct: 0.46,
      riskScore: 88,
      riskBand: "low",
      liquidity: "Intraday ETF liquidity; underlying portfolio is 0-3 month Treasury bills.",
      principalRisk: "Low credit risk, but ETF price can move and shares are not bank deposits.",
      reasons: [
        "Yield guide is anchored to the Treasury-bill proxy instead of a stale static APY.",
        "Tracks very short U.S. Treasury bill exposure.",
        "Low historical volatility makes it a cash-like holding candidate.",
      ],
      cautions: [
        "Use issuer SEC yield and broker executable price before placing an order.",
        "ETF shares are not FDIC-insured deposits.",
      ],
      sourceUrl: "https://www.ishares.com/us/products/314116/ishares-0-3-month-treasury-bond-etf",
      data: { priceSource: "Static fallback snapshot", issuerSource: "iShares", asOf: snapshotAt },
    },
    {
      symbol: "USFR",
      name: "WisdomTree Floating Rate Treasury Fund",
      category: "Floating-rate Treasury ETF",
      issuer: "WisdomTree",
      price: 50.51,
      changePct: 0.05,
      estimatedAnnualYieldPct: 3.82,
      realizedVolatilityPct: 1.06,
      maxDrawdownPct: 0.42,
      riskScore: 85,
      riskBand: "low",
      liquidity: "Intraday ETF liquidity; floating-rate notes reset with short rates.",
      principalRisk: "Treasury credit exposure, but ETF price and rate-reset mechanics still matter.",
      reasons: [
        "Floating-rate Treasury exposure can adjust with short rates.",
        "Low historical drawdown supports cash-like screening.",
        "Issuer page gives a direct fund objective and risk disclosure source.",
      ],
      cautions: [
        "Use issuer SEC yield and broker executable price before placing an order.",
        "Floating-rate mechanics can still create small price moves.",
      ],
      sourceUrl: "https://www.wisdomtree.com/us/products/fixed-income/usfr",
      data: { priceSource: "Static fallback snapshot", issuerSource: "WisdomTree", asOf: snapshotAt },
    },
    {
      symbol: "ICSH",
      name: "iShares Ultra Short-Term Bond ETF",
      category: "Ultrashort bond ETF",
      issuer: "iShares",
      price: 50.5,
      changePct: -0.35,
      estimatedAnnualYieldPct: 3.95,
      realizedVolatilityPct: 1.23,
      maxDrawdownPct: 0.67,
      riskScore: 73,
      riskBand: "moderate",
      liquidity: "Intraday ETF liquidity; active ultrashort bond portfolio.",
      principalRisk: "Adds credit-spread and active-management risk versus Treasury-only funds.",
      reasons: [
        "Higher yield guide than Treasury-only cash ETFs, with still-low realized volatility.",
        "Useful comparison point for investors willing to accept some credit-spread risk.",
        "Issuer page gives direct fund risk disclosures.",
      ],
      cautions: [
        "Credit exposure is higher than Treasury-only funds.",
        "ETF shares are not principal-guaranteed.",
      ],
      sourceUrl: "https://www.ishares.com/us/products/258806/ishares-ultra-short-term-bond-etf",
      data: { priceSource: "Static fallback snapshot", issuerSource: "iShares", asOf: snapshotAt },
    },
  ],
  stableYieldIdeas: [
    {
      id: "treasury-bill-ladder",
      name: "4- to 26-week Treasury bill ladder",
      category: "U.S. Treasury",
      estimatedAnnualYieldPct: 3.8,
      riskBand: "low",
      liquidity: "Matures on schedule; secondary sale possible but price can move.",
      principalRisk: "Backed by the U.S. Treasury when held to maturity.",
      access: "TreasuryDirect or brokered Treasury bills.",
      taxNotes: "Interest is generally exempt from state and local income tax.",
      whyItBelongs: [
        "Best baseline for comparing every other stable-yield idea.",
        "Short maturities reduce duration risk and make reinvestment simple.",
      ],
      watchouts: ["Auction settlement and maturity dates need cash planning."],
      sourceUrl: "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_bill_rates",
    },
    {
      id: "overnight-repo-sweep",
      name: "Overnight Treasury repo or broker cash sweep",
      category: "Overnight cash",
      estimatedAnnualYieldPct: 3.65,
      riskBand: "low",
      liquidity: "Usually overnight or daily liquidity, depending on broker cutoff times.",
      principalRisk: "Depends on repo collateral, sweep bank structure, and broker program terms.",
      access: "Broker cash sweep, Treasury repo fund, or platform cash-management program.",
      taxNotes: "Repo and sweep income is generally taxable; Treasury-backed portions may receive fund-specific reporting.",
      whyItBelongs: [
        "Matches the overnight-cash use case for idle collateral and waiting cash.",
        "Useful benchmark before locking money in CDs or taking ETF duration risk.",
      ],
      watchouts: ["Confirm whether the sweep is FDIC-insured bank cash, a money-market fund, or repo collateral."],
      sourceUrl: "https://home.treasury.gov/treasury-daily-interest-rate-xml-feed",
    },
    {
      id: "fdic-hysa-cd",
      name: "FDIC-insured HYSA or brokered CD ladder",
      category: "Bank deposits",
      estimatedAnnualYieldPct: 3.35,
      riskBand: "low",
      liquidity: "HYSA is flexible; CDs lock cash until maturity unless sold or broken.",
      principalRisk: "FDIC insurance applies within coverage limits at insured banks.",
      access: "Bank account, brokered CDs, or cash-management account.",
      taxNotes: "Interest is generally taxable at federal, state, and local levels.",
      whyItBelongs: [
        "Simple emergency-cash bucket with explicit insurance rules.",
        "Good comparison point before accepting market or credit risk.",
      ],
      watchouts: ["Promotional APYs, balance caps, and withdrawal rules vary."],
      sourceUrl: "https://www.fdic.gov/resources/deposit-insurance",
    },
  ],
  sources: [
    {
      id: "fallback-snapshot",
      name: "Static Discover snapshot",
      status: "degraded",
      url: "https://eatfear.com/discover",
      note: "Temporary production-safe snapshot used while the live scanner API is unavailable.",
    },
    {
      id: "cboe-delayed-options",
      name: "Cboe delayed option chain",
      status: "operational",
      url: "https://www.cboe.com/delayed_quotes/spx/quote_table/",
      note: "Original source for delayed option bid/ask, volume, and open interest.",
    },
    {
      id: "fund-issuer-pages",
      name: "ETF issuer pages",
      status: "operational",
      url: "https://www.ishares.com/us/products/314116/ishares-0-3-month-treasury-bond-etf",
      note: "Linked on stable-asset cards for fund objective, fee, holdings, and issuer risk disclosures.",
    },
  ],
  limitations: [
    "This production-safe first release uses a static fallback snapshot because Vercel is currently failing new function provisioning for this project.",
    "Option quotes can differ from executable broker prices, especially around earnings, dividends, market stress, and wide spreads.",
    "Stable-yield ideas are method screens. Insurance, tax treatment, liquidity, and account eligibility depend on the user's institution and account structure.",
  ],
}
