import type { DiscoverUniverseEntry, StableYieldAssetEntry } from "./types.ts"

export const DISCOVER_MIN_ANNUALIZED_YIELD_PCT = 10

export const DISCOVER_TARGET_DAYS_TO_EXPIRATION = 45

export const DISCOVER_UNIVERSE: DiscoverUniverseEntry[] = [
  { symbol: "SPY", name: "SPDR S&P 500 ETF", assetType: "ETF", sector: "Broad U.S. equity", quality: "broad_index" },
  { symbol: "QQQ", name: "Invesco QQQ Trust", assetType: "ETF", sector: "Large-cap growth", quality: "broad_index" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", assetType: "ETF", sector: "U.S. small cap", quality: "broad_index" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF", assetType: "ETF", sector: "U.S. blue chip", quality: "broad_index" },
  { symbol: "XLK", name: "Technology Select Sector SPDR", assetType: "ETF", sector: "Technology", quality: "sector_etf" },
  { symbol: "XLF", name: "Financial Select Sector SPDR", assetType: "ETF", sector: "Financials", quality: "sector_etf" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR", assetType: "ETF", sector: "Healthcare", quality: "sector_etf" },
  { symbol: "MSFT", name: "Microsoft", assetType: "Stock", sector: "Software", quality: "mega_cap" },
  { symbol: "AAPL", name: "Apple", assetType: "Stock", sector: "Consumer technology", quality: "mega_cap" },
  { symbol: "GOOGL", name: "Alphabet", assetType: "Stock", sector: "Communication services", quality: "mega_cap" },
  { symbol: "AMZN", name: "Amazon", assetType: "Stock", sector: "Consumer / cloud", quality: "mega_cap" },
  { symbol: "META", name: "Meta Platforms", assetType: "Stock", sector: "Communication services", quality: "mega_cap" },
  { symbol: "NVDA", name: "Nvidia", assetType: "Stock", sector: "Semiconductors", quality: "mega_cap" },
  { symbol: "AVGO", name: "Broadcom", assetType: "Stock", sector: "Semiconductors", quality: "mega_cap" },
  { symbol: "JPM", name: "JPMorgan Chase", assetType: "Stock", sector: "Banking", quality: "dividend_quality" },
  { symbol: "COST", name: "Costco", assetType: "Stock", sector: "Consumer staples", quality: "dividend_quality" },
]

export const STABLE_YIELD_ASSET_UNIVERSE: StableYieldAssetEntry[] = [
  {
    symbol: "SGOV",
    name: "iShares 0-3 Month Treasury Bond ETF",
    category: "Treasury bill ETF",
    issuer: "iShares",
    sourceUrl: "https://www.ishares.com/us/products/314116/ishares-0-3-month-treasury-bond-etf",
    yieldOffsetPct: -0.08,
    liquidity: "Intraday ETF liquidity; underlying portfolio is 0-3 month Treasury bills.",
    principalRisk: "Low credit risk, but ETF price can move and shares are not bank deposits.",
    issuerObjective: "Tracks U.S. Treasury bills with maturities of 0-3 months.",
    riskClass: "treasury_cash",
  },
  {
    symbol: "BIL",
    name: "SPDR Bloomberg 1-3 Month T-Bill ETF",
    category: "Treasury bill ETF",
    issuer: "State Street",
    sourceUrl: "https://www.ssga.com/us/en/intermediary/etfs/spdr-bloomberg-1-3-month-t-bill-etf-bil",
    yieldOffsetPct: -0.12,
    liquidity: "Intraday ETF liquidity; short Treasury bill exposure.",
    principalRisk: "Low credit risk, but ETF price and distribution yield can vary.",
    issuerObjective: "Tracks 1-3 month U.S. Treasury bills.",
    riskClass: "treasury_cash",
  },
  {
    symbol: "SHV",
    name: "iShares Short Treasury Bond ETF",
    category: "Short Treasury ETF",
    issuer: "iShares",
    sourceUrl: "https://www.ishares.com/us/products/239466/ishares-short-treasury-bond-etf",
    yieldOffsetPct: -0.18,
    liquidity: "Intraday ETF liquidity; broader short Treasury maturity bucket.",
    principalRisk: "Low credit risk with more duration movement than pure T-bill ETFs.",
    issuerObjective: "Tracks short-maturity U.S. Treasury bonds.",
    riskClass: "treasury_cash",
  },
  {
    symbol: "USFR",
    name: "WisdomTree Floating Rate Treasury Fund",
    category: "Floating-rate Treasury ETF",
    issuer: "WisdomTree",
    sourceUrl: "https://www.wisdomtree.com/us/products/fixed-income/usfr",
    yieldOffsetPct: 0.02,
    liquidity: "Intraday ETF liquidity; floating-rate notes reset with short rates.",
    principalRisk: "Treasury credit exposure, but ETF price and rate-reset mechanics still matter.",
    issuerObjective: "Tracks floating-rate U.S. Treasury notes.",
    riskClass: "floating_treasury",
  },
  {
    symbol: "TFLO",
    name: "iShares Treasury Floating Rate Bond ETF",
    category: "Floating-rate Treasury ETF",
    issuer: "iShares",
    sourceUrl: "https://www.ishares.com/us/products/260652/ishares-treasury-floating-rate-bond-etf",
    yieldOffsetPct: -0.02,
    liquidity: "Intraday ETF liquidity; floating Treasury notes.",
    principalRisk: "Treasury credit exposure, but ETF shares are not principal-guaranteed.",
    issuerObjective: "Tracks U.S. Treasury floating-rate notes.",
    riskClass: "floating_treasury",
  },
  {
    symbol: "ICSH",
    name: "iShares Ultra Short-Term Bond ETF",
    category: "Ultrashort bond ETF",
    issuer: "iShares",
    sourceUrl: "https://www.ishares.com/us/products/258806/ishares-ultra-short-term-bond-etf",
    yieldOffsetPct: 0.15,
    liquidity: "Intraday ETF liquidity; active ultrashort bond portfolio.",
    principalRisk: "Adds credit-spread and active-management risk versus Treasury-only funds.",
    issuerObjective: "Seeks income with limited interest-rate risk through ultrashort bonds.",
    riskClass: "ultrashort_credit",
  },
]
